Yarn.FunctionInfo Class Reference
Public Member Functions
Value Invoke (params Value[] parameters)
Value InvokeWithArray (Value[] parameters)
Package Functions
FunctionInfo (string name, int paramCount, Function implementation)
FunctionInfo (string name, int paramCount, ReturningFunction implementation)
bool IsParameterCountCorrect (int parameterCount)
Properties
string name [get, set]
int paramCount [get, set]
Function function [get, set]
ReturningFunction returningFunction [get, set]
bool returnsValue [get]
Detailed Description
Definition at line 9 of file Library.cs.
Constructor & Destructor Documentation
Yarn.FunctionInfo.FunctionInfo (string name, int paramCount, Function implementation) [package]
Definition at line 65 of file Library.cs.
References Yarn.FunctionInfo.name, and Yarn.FunctionInfo.paramCount.
                                                                                    {
            this.name = name;
            this.paramCount = paramCount;
            this.function = implementation;
            this.returningFunction = null;
        }
Yarn.FunctionInfo.FunctionInfo (string name, int paramCount, ReturningFunction implementation) [package]
Definition at line 72 of file Library.cs.
References Yarn.FunctionInfo.name, and Yarn.FunctionInfo.paramCount.
                                                                                             {
            this.name = name;
            this.paramCount = paramCount;
            this.returningFunction = implementation;
            this.function = null;
        }
Member Function Documentation
Value Yarn.FunctionInfo.Invoke (params Value[] parameters)
Definition at line 32 of file Library.cs.
References Yarn.FunctionInfo.InvokeWithArray().
                                                       {
            return InvokeWithArray(parameters);
        }
Value Yarn.FunctionInfo.InvokeWithArray (Value[] parameters)
Definition at line 36 of file Library.cs.
References Yarn.FunctionInfo.IsParameterCountCorrect(), Yarn.Value.NULL, Yarn.FunctionInfo.returningFunction, and Yarn.FunctionInfo.returnsValue.
Referenced by Yarn.FunctionInfo.Invoke().
                                                         {
            int length;
            if (parameters != null)
                length = parameters.Length;
            else
                length = 0;
            if (IsParameterCountCorrect (length)) {
                if (returnsValue) {
                    return new Value(returningFunction (parameters));
                } else {
                    function (parameters);
                    return Value.NULL; // a null Value
                }
            } else {
                string error = string.Format (
                    "Incorrect number of parameters for function {0} (expected {1}, got {2}",
                    this.name,
                    this.paramCount,
                    parameters.Length);
                throw new InvalidOperationException (error);
            }
        }
bool Yarn.FunctionInfo.IsParameterCountCorrect (int parameterCount) [package]
Definition at line 79 of file Library.cs.
References Yarn.FunctionInfo.paramCount.
Referenced by Yarn.FunctionInfo.InvokeWithArray(), and Yarn.Parser.Expression.Parse().
        {
            return paramCount == parameterCount || paramCount == -1;
        }
Property Documentation
Function Yarn.FunctionInfo.function [get], [set]
Definition at line 22 of file Library.cs.
string Yarn.FunctionInfo.name [get], [set]
Definition at line 12 of file Library.cs.
Referenced by Yarn.FunctionInfo.FunctionInfo().
int Yarn.FunctionInfo.paramCount [get], [set]
Definition at line 16 of file Library.cs.
Referenced by Yarn.FunctionInfo.FunctionInfo(), Yarn.BodyVisitor.HandleFunction(), and Yarn.FunctionInfo.IsParameterCountCorrect().
ReturningFunction Yarn.FunctionInfo.returningFunction [get], [set]
Definition at line 23 of file Library.cs.
Referenced by Yarn.FunctionInfo.InvokeWithArray().
bool Yarn.FunctionInfo.returnsValue [get]
Definition at line 26 of file Library.cs.
Referenced by Yarn.FunctionInfo.InvokeWithArray().
The documentation for this class was generated from the following file:
YarnSpinner/Library.cs