CsvHelper.CsvParser Class Reference
Parses a CSV file.
Public Member Functions
CsvParser (TextReader reader)
Creates a new parser using the given TextReader.
CsvParser (TextReader reader, CsvConfiguration configuration)
Creates a new parser using the given TextReader and CsvConfiguration.
virtual string[] Read ()
Reads a record from the CSV file.
void Dispose ()
Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
Protected Member Functions
virtual void Dispose (bool disposing)
Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
virtual void CheckDisposed ()
Checks if the instance has been disposed of.
virtual void AddFieldToRecord (ref int recordPosition, string field, ref bool fieldIsBad)
Adds the field to the current record.
virtual void AppendField (ref string field, int fieldStartPosition, int length)
Appends the current buffer data to the field.
virtual void UpdateBytePosition (int fieldStartPosition, int length)
Updates the byte position using the data from the reader buffer.
virtual string[] ReadLine ()
Reads the next line.
bool GetChar (out char ch, ref int fieldStartPosition, ref int rawFieldStartPosition, ref string field, ref bool fieldIsBad, bool prevCharWasDelimiter, ref int recordPosition, ref int fieldLength, bool inComment, bool inDelimiter, bool inQuotes, bool isPeek)
Gets the current character from the buffer while advancing the buffer if it ran out.
virtual void ReadExcelSeparator ()
Reads the Excel seperator and sets it to the delimiter.
Properties
virtual CsvConfiguration Configuration [get]
Gets the configuration.
virtual int FieldCount [get, set]
Gets the field count.
virtual long CharPosition [get, set]
Gets the character position that the parser is currently on.
virtual long BytePosition [get, set]
Gets the byte position that the parser is currently on.
virtual int Row [get]
Gets the row of the CSV file that the parser is currently on. This is the logical CSV row.
virtual int RawRow [get]
Gets the row of the CSV file that the parser is currently on. This is the actual file row.
virtual string RawRecord [get, set]
Gets the raw row for the current record that was parsed.
Private Attributes
bool disposed
TextReader reader
readonly char[] readerBuffer
int readerBufferPosition
int charsRead
string[] record
int currentRow
int currentRawRow
readonly CsvConfiguration configuration
char cPrev
char c = '\0'
bool read
bool hasExcelSeparatorBeenRead
Detailed Description
Parses a CSV file.
Definition at line 16 of file CsvParser.cs.
Constructor & Destructor Documentation
CsvHelper.CsvParser.CsvParser (TextReader reader)
Creates a new parser using the given TextReader.
Parameters
reader The TextReader with the CSV file data.
Definition at line 76 of file CsvParser.cs.
: this(reader, new CsvConfiguration()) {}
CsvHelper.CsvParser.CsvParser (TextReader reader, CsvConfiguration configuration)
Creates a new parser using the given TextReader and CsvConfiguration.
Parameters
reader The TextReader with the CSV file data.
configuration The configuration.
Definition at line 84 of file CsvParser.cs.
References CsvHelper.CsvParser.configuration, CsvHelper.CsvParser.reader, and CsvHelper.CsvParser.readerBuffer.
        {
            if(reader == null)
            {
                throw new ArgumentNullException("reader");
            }
            if(configuration == null)
            {
                throw new ArgumentNullException("configuration");
            }
            this.reader = reader;
            this.configuration = configuration;
            readerBuffer = new char[configuration.BufferSize];
        }
Member Function Documentation
virtual void CsvHelper.CsvParser.AddFieldToRecord (ref int recordPosition, string field, ref bool fieldIsBad) [protected], [virtual]
Adds the field to the current record.
Parameters
recordPosition The record position to add the field to.
field The field to add.
Definition at line 187 of file CsvParser.cs.
References CsvHelper.Configuration.CsvConfiguration.BadDataCallback, CsvHelper.CsvParser.configuration, CsvHelper.CsvParser.currentRow, CsvHelper.CsvParser.FieldCount, CsvHelper.CsvParser.record, and CsvHelper.Configuration.CsvConfiguration.ThrowOnBadData.
Referenced by CsvHelper.CsvParser.GetChar(), and CsvHelper.CsvParser.ReadLine().
        {
            if(record.Length < recordPosition + 1)
            {
                // Resize record if it's too small.
                Array.Resize(ref record, recordPosition + 1);
                // Set the field count. If there is a header
                // record, then we can go by the number of
                // headers there is. If there is no header
                // record, then we can go by the first row.
                // Either way, we're using the first row.
                if(currentRow == 1)
                {
                    FieldCount = record.Length;
                }
            }
            if(fieldIsBad && configuration.ThrowOnBadData)
            {
                throw new CsvBadDataException(string.Format("Field: '{0}'", field));
            }
            if(fieldIsBad && configuration.BadDataCallback != null)
            {
                configuration.BadDataCallback(field);
            }
            fieldIsBad = false;
            record[recordPosition] = field;
            recordPosition++;
        }
virtual void CsvHelper.CsvParser.AppendField (ref string field, int fieldStartPosition, int length) [protected], [virtual]
Appends the current buffer data to the field.
Parameters
field The field to append the current buffer to.
fieldStartPosition The start position in the buffer that the .
length The length.
Definition at line 227 of file CsvParser.cs.
References CsvHelper.CsvParser.readerBuffer.
Referenced by CsvHelper.CsvParser.GetChar(), and CsvHelper.CsvParser.ReadLine().
        {
            field += new string(readerBuffer, fieldStartPosition, length);
        }
virtual void CsvHelper.CsvParser.CheckDisposed () [protected], [virtual]
Checks if the instance has been disposed of.
Exceptions
ObjectDisposedException
Definition at line 174 of file CsvParser.cs.
References CsvHelper.CsvParser.disposed.
Referenced by CsvHelper.CsvParser.Read().
        {
            if(disposed)
            {
                throw new ObjectDisposedException(GetType().ToString());
            }
        }
void CsvHelper.CsvParser.Dispose ()
Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
<filterpriority>2</filterpriority>
Definition at line 141 of file CsvParser.cs.
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
virtual void CsvHelper.CsvParser.Dispose (bool disposing) [protected], [virtual]
Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
Parameters
disposing True if the instance needs to be disposed of.
Definition at line 151 of file CsvParser.cs.
References CsvHelper.CsvParser.disposed, and CsvHelper.CsvParser.reader.
        {
            if(disposed)
            {
                return;
            }
            if(disposing)
            {
                if(reader != null)
                {
                    reader.Dispose();
                }
            }
            disposed = true;
            reader = null;
        }
bool CsvHelper.CsvParser.GetChar (out char ch, ref int fieldStartPosition, ref int rawFieldStartPosition, ref string field, ref bool fieldIsBad, bool prevCharWasDelimiter, ref int recordPosition, ref int fieldLength, bool inComment, bool inDelimiter, bool inQuotes, bool isPeek) [protected]
Gets the current character from the buffer while advancing the buffer if it ran out.
Parameters
ch The char that gets the read char set to.
fieldStartPosition The start position of the current field.
rawFieldStartPosition The start position of the raw field.
field The field.
prevCharWasDelimiter A value indicating if the previous char read was a delimiter.
recordPosition The position in the record we are currently at.
fieldLength The length of the field in the buffer.
inComment A value indicating if the row is current a comment row.
isPeek A value indicating if this call is a peek. If true and the end of the record was found no record handling will be done.
Returns
A value indicating if read a char was read. True if a char was read, otherwise false.
Definition at line 538 of file CsvParser.cs.
References CsvHelper.CsvParser.AddFieldToRecord(), CsvHelper.CsvParser.AppendField(), CsvHelper.CsvParser.c, CsvHelper.CsvParser.charsRead, CsvHelper.CsvParser.RawRecord, CsvHelper.CsvParser.readerBuffer, CsvHelper.CsvParser.readerBufferPosition, CsvHelper.CsvParser.record, and CsvHelper.CsvParser.UpdateBytePosition().
Referenced by CsvHelper.CsvParser.ReadLine().
        {
            if(readerBufferPosition == charsRead)
            {
                // We need to read more of the stream.
                if(!inDelimiter && !inComment)
                {
                    // The buffer ran out. Take the current
                    // text and add it to the field.
                    AppendField(ref field, fieldStartPosition, fieldLength);
                }
                UpdateBytePosition(fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                fieldLength = 0;
                RawRecord += new string(readerBuffer, rawFieldStartPosition,
      readerBufferPosition - rawFieldStartPosition);
                charsRead = reader.Read(readerBuffer, 0, readerBuffer.Length);
                readerBufferPosition = 0;
                fieldStartPosition = 0;
                rawFieldStartPosition = 0;
                if(charsRead == 0)
                {
                    // The end of the stream has been reached.
                    if(isPeek)
                    {
                        // Don't do any record handling because we're just looking ahead
                        // and not actually getting the next char to use.
                        ch = '\0';
                        return false;
                    }
                    if((c != '\r' && c != '\n' && c != '\0' && !inComment) || inQuotes)
                    {
                        // If we're in quotes and have reached the end of the file, record the
                        // rest of the record and field.
                        if(prevCharWasDelimiter)
                        {
                            // Handle an empty field at the end of the row.
                            field = "";
                        }
                        AddFieldToRecord(ref recordPosition, field, ref fieldIsBad);
                    }
                    else
                    {
                        RawRecord = null;
                        record = null;
                    }
                    ch = '\0';
                    return false;
                }
            }
            ch = readerBuffer[readerBufferPosition];
            return true;
        }
virtual string [] CsvHelper.CsvParser.Read () [virtual]
Reads a record from the CSV file.
Returns
A List{String} of fields for the record read. If there are no more records, null is returned.
Implements CsvHelper.ICsvParser.
Definition at line 107 of file CsvParser.cs.
References CsvHelper.CsvParser.CheckDisposed(), CsvHelper.CsvParser.configuration, CsvHelper.Configuration.CsvConfiguration.DetectColumnCountChanges, CsvHelper.CsvParser.FieldCount, CsvHelper.Configuration.CsvConfiguration.HasExcelSeparator, CsvHelper.CsvParser.hasExcelSeparatorBeenRead, CsvHelper.CsvParser.ReadExcelSeparator(), and CsvHelper.CsvParser.ReadLine().
        {
            CheckDisposed();
            try
            {
                if(configuration.HasExcelSeparator && !
      hasExcelSeparatorBeenRead)
                {
                    ReadExcelSeparator();
                }
                var row = ReadLine();
                if(configuration.DetectColumnCountChanges && row !=
      null)
                {
                    if(FieldCount > 0 && (FieldCount != row.Length || row.Any(field
      => field == null)))
                    {
                        throw new CsvBadDataException("An inconsistent number of columns has been
       detected.");
                    }
                }
                return row;
            }
            catch(Exception ex)
            {
                ExceptionHelper.AddExceptionDataMessage(ex, this, null, null, null, null);
                throw;
            }
        }
virtual void CsvHelper.CsvParser.ReadExcelSeparator () [protected], [virtual]
Reads the Excel seperator and sets it to the delimiter.
Definition at line 604 of file CsvParser.cs.
References CsvHelper.CsvParser.hasExcelSeparatorBeenRead.
Referenced by CsvHelper.CsvParser.Read().
        {
            // sep=delimiter
            var sepLine = reader.ReadLine();
            if(sepLine != null)
            {
                configuration.Delimiter = sepLine.Substring(4);
            }
            hasExcelSeparatorBeenRead = true;
        }
virtual string [] CsvHelper.CsvParser.ReadLine () [protected], [virtual]
Reads the next line.
Returns
The line separated into fields.
Definition at line 249 of file CsvParser.cs.
References CsvHelper.CsvParser.AddFieldToRecord(), CsvHelper.Configuration.CsvConfiguration.AllowComments, CsvHelper.CsvParser.AppendField(), CsvHelper.CsvParser.c, CsvHelper.CsvParser.CharPosition, CsvHelper.Configuration.CsvConfiguration.Comment, CsvHelper.CsvParser.configuration, CsvHelper.CsvParser.cPrev, CsvHelper.CsvParser.currentRawRow, CsvHelper.CsvParser.currentRow, CsvHelper.Configuration.CsvConfiguration.Delimiter, CsvHelper.CsvParser.FieldCount, CsvHelper.CsvParser.GetChar(), CsvHelper.Configuration.CsvConfiguration.IgnoreBlankLines, CsvHelper.Configuration.CsvConfiguration.IgnoreQuotes, CsvHelper.Configuration.CsvConfiguration.Quote, CsvHelper.CsvParser.RawRecord, CsvHelper.CsvParser.read, CsvHelper.CsvParser.readerBuffer, CsvHelper.CsvParser.readerBufferPosition, CsvHelper.CsvParser.record, CsvHelper.CsvParser.UpdateBytePosition(), and CsvHelper.Configuration.CsvConfiguration.UseExcelLeadingZerosFormatForNumerics.
Referenced by CsvHelper.CsvParser.Read().
        {
            string field = null;
            var fieldStartPosition = readerBufferPosition;
            var rawFieldStartPosition = readerBufferPosition;
            var inQuotes = false;
            var fieldIsEscaped = false;
            var fieldIsBad = false;
            var inComment = false;
            var inDelimiter = false;
            var inExcelLeadingZerosFormat = false;
            var delimiterPosition = 0;
            var prevCharWasDelimiter = false;
            var recordPosition = 0;
            record = new string[FieldCount];
            RawRecord = string.Empty;
            currentRow++;
            currentRawRow++;
            while(true)
            {
                if(read)
                {
                    cPrev = c;
                }
                var fieldLength = readerBufferPosition - fieldStartPosition;
                read = GetChar(out c, ref fieldStartPosition, ref rawFieldStartPosition, ref
      field, ref fieldIsBad,
                    prevCharWasDelimiter, ref recordPosition, ref fieldLength, inComment, inDelimiter,
      inQuotes, false);
                if(!read)
                {
                    break;
                }
                readerBufferPosition++;
                CharPosition++;
                #region Use Excel Leading Zeros Format for Numerics
                // This needs to get in the way and parse things completely different
                // from how a normal CSV field works. This horribly ugly.
                if(configuration.
      UseExcelLeadingZerosFormatForNumerics)
                {
                    if(c == '=' && !inExcelLeadingZerosFormat && (prevCharWasDelimiter ||
      cPrev == '\r' || cPrev == '\n' || cPrev == null))
                    {
                        // The start of the leading zeros format has been hit.
                        fieldLength = readerBufferPosition - fieldStartPosition;
                        char cNext;
                        GetChar(out cNext, ref fieldStartPosition, ref rawFieldStartPosition, ref
      field, ref fieldIsBad,
                            prevCharWasDelimiter, ref recordPosition, ref fieldLength, inComment,
      inDelimiter, inQuotes, true);
                        if(cNext == '"')
                        {
                            inExcelLeadingZerosFormat = true;
                            continue;
                        }
                    }
                    else if(inExcelLeadingZerosFormat)
                    {
                        if(c == '"' && cPrev == '=' || char.IsDigit(c))
                        {
                            // Inside of the field.
                        }
                        else if(c == '"')
                        {
                            // The end of the field has been hit.
                            char cNext;
                            var peekRead = GetChar(out cNext, ref fieldStartPosition, ref
      rawFieldStartPosition, ref field, ref fieldIsBad, prevCharWasDelimiter, ref recordPosition, ref fieldLength,
      inComment, inDelimiter, inQuotes, true);
                            if(cNext == configuration.Delimiter[0] || cNext == '\r'
      || cNext == '\n' || cNext == '\0')
                            {
                                AppendField(ref field, fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                                UpdateBytePosition(fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                                field = field.Trim('=', '"');
                                fieldStartPosition = readerBufferPosition;
                                if(!peekRead)
                                {
                                    AddFieldToRecord(ref recordPosition, field, ref
      fieldIsBad);
                                }
                                inExcelLeadingZerosFormat = false;
                            }
                        }
                        else
                        {
                            inExcelLeadingZerosFormat = false;
                        }
                        continue;
                    }
                }
                #endregion
                if(c == configuration.Quote && !
      configuration.IgnoreQuotes)
                {
                    if(!fieldIsEscaped && (prevCharWasDelimiter || cPrev == '\r' ||
      cPrev == '\n' || cPrev == null))
                    {
                        // The field is escaped only if the first char of
                        // the field is a quote.
                        fieldIsEscaped = true;
                    }
                    if(!fieldIsEscaped)
                    {
                        fieldIsBad = true;
                        // If the field isn't escaped, the quote
                        // is like any other char and we should
                        // just ignore it.
                        continue;
                    }
                    inQuotes = !inQuotes;
                    if(fieldStartPosition != readerBufferPosition - 1)
                    {
                        // Grab all the field chars before the
                        // quote if there are any.
                        AppendField(ref field, fieldStartPosition,
      readerBufferPosition - fieldStartPosition - 1);
                        // Include the quote in the byte count.
                        UpdateBytePosition(fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                    }
                    if(cPrev != configuration.Quote || !inQuotes)
                    {
                        if(inQuotes || cPrev == configuration.
      Quote || readerBufferPosition == 1)
                        {
                            // The quote will be uncounted and needs to be catered for if:
                            // 1. It's the opening quote
                            // 2. It's the closing quote on an empty field ("")
                            // 3. It's the closing quote and has appeared as the first character in the
       buffer
                            UpdateBytePosition(fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                        }
                        // Set the new field start position to
                        // the char after the quote.
                        fieldStartPosition = readerBufferPosition;
                    }
                    prevCharWasDelimiter = false;
                    continue;
                }
                prevCharWasDelimiter = false;
                if(fieldIsEscaped && inQuotes)
                {
                    if(c == '\r' || (c == '\n' && cPrev != '\r'))
                    {
                        currentRawRow++;
                    }
                    // While inside an escaped field,
                    // all chars are ignored.
                    continue;
                }
                if(cPrev == configuration.Quote && !
      configuration.IgnoreQuotes)
                {
                    if(c != configuration.Delimiter[0] &&
      c != '\r' && c != '\n')
                    {
                        fieldIsBad = true;
                    }
                    // If we're not in quotes and the
                    // previous char was a quote, the
                    // field is no longer escaped.
                    fieldIsEscaped = false;
                }
                if(inComment && c != '\r' && c != '\n')
                {
                    // We are on a commented line.
                    // Ignore the character.
                }
                else if(c == configuration.Delimiter[0] || inDelimiter)
                {
                    if(!inDelimiter)
                    {
                        // If we hit the delimiter, we are
                        // done reading the field and can
                        // add it to the record.
                        delimiterPosition = 0;
                        AppendField(ref field, fieldStartPosition,
      readerBufferPosition - fieldStartPosition - 1);
                        // Include the comma in the byte count.
                        UpdateBytePosition(fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                        AddFieldToRecord(ref recordPosition, field, ref fieldIsBad);
                        fieldStartPosition = readerBufferPosition;
                        field = null;
                        inDelimiter = true;
                    }
                    
                    if(delimiterPosition == configuration.
      Delimiter.Length - 1)
                    {
                        // We are done reading the delimeter.
                        // Include the delimiter in the byte count.
                        UpdateBytePosition(fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                        inDelimiter = false;
                        prevCharWasDelimiter = true;
                        fieldStartPosition = readerBufferPosition;
                    }
                    else if(configuration.Delimiter[delimiterPosition] !=
      c)
                    {
                        // We're not actually in a delimiter. Reset things back
                        // to the previous field.
                        recordPosition--;
                        fieldStartPosition -= (delimiterPosition + 1);
                        inDelimiter = false;
                    }
                    else
                    {
                        delimiterPosition++;
                    }
                }
                else if(c == '\r' || c == '\n')
                {
                    fieldLength = readerBufferPosition - fieldStartPosition - 1;
                    if(c == '\r')
                    {
                        char cNext;
                        GetChar(out cNext, ref fieldStartPosition, ref rawFieldStartPosition, ref
      field, ref fieldIsBad, prevCharWasDelimiter, ref recordPosition, ref fieldLength, inComment, inDelimiter,
      inQuotes, true);
                        if(cNext == '\n')
                        {
                            readerBufferPosition++;
                            CharPosition++;
                        }
                    }
                    if(cPrev == '\r' || cPrev == '\n' || inComment ||
      cPrev == null)
                    {
                        // We have hit a blank line. Ignore it.
                        UpdateBytePosition(fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                        fieldStartPosition = readerBufferPosition;
                        inComment = false;
                        if(!configuration.IgnoreBlankLines)
                        {
                            break;
                        }
                        // If blank lines are being ignored, we need to add
                        // to the row count because we're skipping the row
                        // and it won't get added normally.
                        currentRow++;
                        continue;
                    }
                    // If we hit the end of the record, add
                    // the current field and return the record.
                    AppendField(ref field, fieldStartPosition, fieldLength);
                    // Include the \r or \n in the byte count.
                    UpdateBytePosition(fieldStartPosition,
      readerBufferPosition - fieldStartPosition);
                    AddFieldToRecord(ref recordPosition, field, ref fieldIsBad);
                    break;
                }
                else if(configuration.AllowComments &&
      c == configuration.Comment && (cPrev == '\r' || cPrev == '\n' ||
      cPrev == null))
                {
                    inComment = true;
                }
            }
            if(record != null)
            {
                RawRecord += new string(readerBuffer, rawFieldStartPosition,
      readerBufferPosition - rawFieldStartPosition);
            }
            return record;
        }
virtual void CsvHelper.CsvParser.UpdateBytePosition (int fieldStartPosition, int length) [protected], [virtual]
Updates the byte position using the data from the reader buffer.
Parameters
fieldStartPosition The field start position.
length The length.
Definition at line 237 of file CsvParser.cs.
References CsvHelper.CsvParser.BytePosition, CsvHelper.CsvParser.configuration, CsvHelper.Configuration.CsvConfiguration.CountBytes, and CsvHelper.CsvParser.readerBuffer.
Referenced by CsvHelper.CsvParser.GetChar(), and CsvHelper.CsvParser.ReadLine().
        {
            if(configuration.CountBytes)
            {
                BytePosition += configuration.Encoding.GetByteCount(
      readerBuffer, fieldStartPosition, length);
            }
        }
Member Data Documentation
char CsvHelper.CsvParser.c = '\0' [private]
Definition at line 28 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.GetChar(), and CsvHelper.CsvParser.ReadLine().
int CsvHelper.CsvParser.charsRead [private]
Definition at line 22 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.GetChar().
readonly CsvConfiguration CsvHelper.CsvParser.configuration [private]
Definition at line 26 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.AddFieldToRecord(), CsvHelper.CsvParser.CsvParser(), CsvHelper.CsvParser.Read(), CsvHelper.CsvParser.ReadLine(), and CsvHelper.CsvParser.UpdateBytePosition().
char CsvHelper.CsvParser.cPrev [private]
Definition at line 27 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.ReadLine().
int CsvHelper.CsvParser.currentRawRow [private]
Definition at line 25 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.ReadLine().
int CsvHelper.CsvParser.currentRow [private]
Definition at line 24 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.AddFieldToRecord(), and CsvHelper.CsvParser.ReadLine().
bool CsvHelper.CsvParser.disposed [private]
Definition at line 18 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.CheckDisposed(), and CsvHelper.CsvParser.Dispose().
bool CsvHelper.CsvParser.hasExcelSeparatorBeenRead [private]
Definition at line 30 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.Read(), and CsvHelper.CsvParser.ReadExcelSeparator().
bool CsvHelper.CsvParser.read [private]
Definition at line 29 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.ReadLine().
TextReader CsvHelper.CsvParser.reader [private]
Definition at line 19 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.CsvParser(), and CsvHelper.CsvParser.Dispose().
readonly char [] CsvHelper.CsvParser.readerBuffer [private]
Definition at line 20 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.AppendField(), CsvHelper.CsvParser.CsvParser(), CsvHelper.CsvParser.GetChar(), CsvHelper.CsvParser.ReadLine(), and CsvHelper.CsvParser.UpdateBytePosition().
int CsvHelper.CsvParser.readerBufferPosition [private]
Definition at line 21 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.GetChar(), and CsvHelper.CsvParser.ReadLine().
string [] CsvHelper.CsvParser.record [private]
Definition at line 23 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.AddFieldToRecord(), CsvHelper.CsvParser.GetChar(), and CsvHelper.CsvParser.ReadLine().
Property Documentation
virtual long CsvHelper.CsvParser.BytePosition [get], [set]
Gets the byte position that the parser is currently on.
Definition at line 53 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.UpdateBytePosition().
virtual long CsvHelper.CsvParser.CharPosition [get], [set]
Gets the character position that the parser is currently on.
Definition at line 48 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.ReadLine().
virtual CsvConfiguration CsvHelper.CsvParser.Configuration [get]
Gets the configuration.
Definition at line 36 of file CsvParser.cs.
virtual int CsvHelper.CsvParser.FieldCount [get], [set]
Gets the field count.
Definition at line 43 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.AddFieldToRecord(), CsvHelper.CsvParser.Read(), and CsvHelper.CsvParser.ReadLine().
virtual string CsvHelper.CsvParser.RawRecord [get], [set]
Gets the raw row for the current record that was parsed.
Definition at line 70 of file CsvParser.cs.
Referenced by CsvHelper.CsvParser.GetChar(), and CsvHelper.CsvParser.ReadLine().
virtual int CsvHelper.CsvParser.RawRow [get]
Gets the row of the CSV file that the parser is currently on. This is the actual file row.
Definition at line 65 of file CsvParser.cs.
virtual int CsvHelper.CsvParser.Row [get]
Gets the row of the CSV file that the parser is currently on. This is the logical CSV row.
Definition at line 59 of file CsvParser.cs.
The documentation for this class was generated from the following file:
packages/CsvHelper.2.16.0.0/src/CsvHelper/CsvParser.cs