Yarn.Parser.AssignmentStatement Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
AssignmentStatement (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Static Package Functions
static bool CanParse (Parser p)
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
string destinationVariableName [get, set]
Expression valueExpression [get, set]
TokenType operation [get, set]
Static Private Attributes
static TokenType[] validOperators
Detailed Description
Definition at line 1101 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.AssignmentStatement.AssignmentStatement (ParseNode parent, Parser p) [package]
Definition at line 1121 of file Parser.cs.
References Yarn.Parser.AssignmentStatement.destinationVariableName, Yarn.Parser.AssignmentStatement.operation, Yarn.Parser.AssignmentStatement.validOperators, and Yarn.Parser.AssignmentStatement.valueExpression.
                                                                     : base(
      parent, p) {
                p.ExpectSymbol(TokenType.BeginCommand);
                p.ExpectSymbol(TokenType.Set);
                destinationVariableName = p.ExpectSymbol(TokenType.Variable).value
      as string;
                operation = p.ExpectSymbol(validOperators).type;
                valueExpression = Expression.Parse(this, p);
                p.ExpectSymbol(TokenType.EndCommand);
            }
Member Function Documentation
static bool Yarn.Parser.AssignmentStatement.CanParse (Parser p) [static], [package]
Definition at line 1102 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
            {
                return p.NextSymbolsAre (TokenType.BeginCommand, TokenType.Set);
            }
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.AssignmentStatement.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 1132 of file Parser.cs.
References Yarn.Parser.AssignmentStatement.destinationVariableName, Yarn.Parser.AssignmentStatement.operation, and Yarn.Parser.Tab().
            {
                var sb = new StringBuilder ();
                sb.Append (Tab(indentLevel, "Set:"));
                sb.Append (Tab(indentLevel+1, destinationVariableName));
                sb.Append (Tab (indentLevel+1, operation.ToString()));
                sb.Append (valueExpression.PrintTree (indentLevel + 1));
                return sb.ToString ();
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
TokenType [] Yarn.Parser.AssignmentStatement.validOperators [static], [private]
Initial value:
= {
                TokenType.EqualToOrAssign,
                TokenType.AddAssign,
                TokenType.MinusAssign,
                TokenType.DivideAssign,
                TokenType.MultiplyAssign
            }
Definition at line 1113 of file Parser.cs.
Referenced by Yarn.Parser.AssignmentStatement.AssignmentStatement().
Property Documentation
string Yarn.Parser.AssignmentStatement.destinationVariableName [get], [set], [package]
Definition at line 1107 of file Parser.cs.
Referenced by Yarn.Parser.AssignmentStatement.AssignmentStatement(), and Yarn.Parser.AssignmentStatement.PrintTree().
TokenType Yarn.Parser.AssignmentStatement.operation [get], [set], [package]
Definition at line 1111 of file Parser.cs.
Referenced by Yarn.Parser.AssignmentStatement.AssignmentStatement(), and Yarn.Parser.AssignmentStatement.PrintTree().
Expression Yarn.Parser.AssignmentStatement.valueExpression [get], [set], [package]
Definition at line 1109 of file Parser.cs.
Referenced by Yarn.Parser.AssignmentStatement.AssignmentStatement().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs