Yarn.BodyVisitor Class Reference
Public Member Functions
BodyVisitor (AntlrCompiler compiler)
override int VisitLine_statement (YarnSpinnerParser.Line_statementContext context)
Visit a parse tree produced by YarnSpinnerParser.line_statement.
override int VisitOption_statement (YarnSpinnerParser.Option_statementContext context)
Visit a parse tree produced by YarnSpinnerParser.option_statement.
override int VisitSet_statement (YarnSpinnerParser.Set_statementContext context)
Visit a parse tree produced by YarnSpinnerParser.set_statement.
override int VisitAction_statement (YarnSpinnerParser.Action_statementContext context)
Visit a parse tree produced by YarnSpinnerParser.action_statement.
override int VisitFunction_statement (YarnSpinnerParser.Function_statementContext context)
Visit a parse tree produced by YarnSpinnerParser.function_statement.
override int VisitFunction (YarnSpinnerParser.FunctionContext context)
Visit a parse tree produced by YarnSpinnerParser.function.
override int VisitIf_statement (YarnSpinnerParser.If_statementContext context)
Visit a parse tree produced by YarnSpinnerParser.if_statement.
override int VisitShortcut_statement (YarnSpinnerParser.Shortcut_statementContext context)
Visit a parse tree produced by YarnSpinnerParser.shortcut_statement.
override int VisitExpParens (YarnSpinnerParser.ExpParensContext context)
Visit a parse tree produced by the expParens labeled alternative in YarnSpinnerParser.expression.
override int VisitExpNegative (YarnSpinnerParser.ExpNegativeContext context)
Visit a parse tree produced by the expNegative labeled alternative in YarnSpinnerParser.expression.
override int VisitExpNot (YarnSpinnerParser.ExpNotContext context)
Visit a parse tree produced by the expNot labeled alternative in YarnSpinnerParser.expression.
override int VisitExpValue (YarnSpinnerParser.ExpValueContext context)
Visit a parse tree produced by the expValue labeled alternative in YarnSpinnerParser.expression.
override int VisitExpMultDivMod (YarnSpinnerParser.ExpMultDivModContext context)
Visit a parse tree produced by the expMultDivMod labeled alternative in YarnSpinnerParser.expression.
override int VisitExpAddSub (YarnSpinnerParser.ExpAddSubContext context)
Visit a parse tree produced by the expAddSub labeled alternative in YarnSpinnerParser.expression.
override int VisitExpComparison (YarnSpinnerParser.ExpComparisonContext context)
Visit a parse tree produced by the expComparison labeled alternative in YarnSpinnerParser.expression.
override int VisitExpEquality (YarnSpinnerParser.ExpEqualityContext context)
Visit a parse tree produced by the expEquality labeled alternative in YarnSpinnerParser.expression.
override int VisitExpAndOrXor (YarnSpinnerParser.ExpAndOrXorContext context)
Visit a parse tree produced by the expAndOrXor labeled alternative in YarnSpinnerParser.expression.
override int VisitExpMultDivModEquals (YarnSpinnerParser.ExpMultDivModEqualsContext context)
Visit a parse tree produced by the expMultDivModEquals labeled alternative in YarnSpinnerParser.expression.
override int VisitExpPlusMinusEquals (YarnSpinnerParser.ExpPlusMinusEqualsContext context)
Visit a parse tree produced by the expPlusMinusEquals labeled alternative in YarnSpinnerParser.expression.
override int VisitValueVar (YarnSpinnerParser.ValueVarContext context)
Visit a parse tree produced by the valueVar labeled alternative in YarnSpinnerParser.value.
override int VisitValueNumber (YarnSpinnerParser.ValueNumberContext context)
Visit a parse tree produced by the valueNumber labeled alternative in YarnSpinnerParser.value.
override int VisitValueTrue (YarnSpinnerParser.ValueTrueContext context)
Visit a parse tree produced by the valueTrue labeled alternative in YarnSpinnerParser.value.
override int VisitValueFalse (YarnSpinnerParser.ValueFalseContext context)
Visit a parse tree produced by the valueFalse labeled alternative in YarnSpinnerParser.value.
override int VisitVariable (YarnSpinnerParser.VariableContext context)
Visit a parse tree produced by YarnSpinnerParser.variable.
override int VisitValueString (YarnSpinnerParser.ValueStringContext context)
Visit a parse tree produced by the valueString labeled alternative in YarnSpinnerParser.value.
override int VisitValueFunc (YarnSpinnerParser.ValueFuncContext context)
Visit a parse tree produced by the valueFunc labeled alternative in YarnSpinnerParser.value.
override int VisitValueNull (YarnSpinnerParser.ValueNullContext context)
Visit a parse tree produced by the valueNull labeled alternative in YarnSpinnerParser.value.
virtual Result VisitDialogue ([NotNull] YarnSpinnerParser.DialogueContext context)
Visit a parse tree produced by YarnSpinnerParser.dialogue.
virtual Result VisitNode ([NotNull] YarnSpinnerParser.NodeContext context)
Visit a parse tree produced by YarnSpinnerParser.node.
virtual Result VisitHeader ([NotNull] YarnSpinnerParser.HeaderContext context)
Visit a parse tree produced by YarnSpinnerParser.header.
virtual Result VisitHeader_title ([NotNull] YarnSpinnerParser.Header_titleContext context)
Visit a parse tree produced by YarnSpinnerParser.header_title.
virtual Result VisitHeader_tag ([NotNull] YarnSpinnerParser.Header_tagContext context)
Visit a parse tree produced by YarnSpinnerParser.header_tag.
virtual Result VisitHeader_line ([NotNull] YarnSpinnerParser.Header_lineContext context)
Visit a parse tree produced by YarnSpinnerParser.header_line.
virtual Result VisitBody ([NotNull] YarnSpinnerParser.BodyContext context)
Visit a parse tree produced by YarnSpinnerParser.body.
virtual Result VisitStatement ([NotNull] YarnSpinnerParser.StatementContext context)
Visit a parse tree produced by YarnSpinnerParser.statement.
virtual Result VisitShortcut ([NotNull] YarnSpinnerParser.ShortcutContext context)
Visit a parse tree produced by YarnSpinnerParser.shortcut.
virtual Result VisitShortcut_conditional ([NotNull] YarnSpinnerParser.Shortcut_conditionalContext context)
Visit a parse tree produced by YarnSpinnerParser.shortcut_conditional.
virtual Result VisitShortcut_text ([NotNull] YarnSpinnerParser.Shortcut_textContext context)
Visit a parse tree produced by YarnSpinnerParser.shortcut_text.
virtual Result VisitIf_clause ([NotNull] YarnSpinnerParser.If_clauseContext context)
Visit a parse tree produced by YarnSpinnerParser.if_clause.
virtual Result VisitElse_if_clause ([NotNull] YarnSpinnerParser.Else_if_clauseContext context)
Visit a parse tree produced by YarnSpinnerParser.else_if_clause.
virtual Result VisitElse_clause ([NotNull] YarnSpinnerParser.Else_clauseContext context)
Visit a parse tree produced by YarnSpinnerParser.else_clause.
virtual Result VisitText ([NotNull] YarnSpinnerParser.TextContext context)
Visit a parse tree produced by YarnSpinnerParser.text.
virtual Result VisitHashtag_block ([NotNull] YarnSpinnerParser.Hashtag_blockContext context)
Visit a parse tree produced by YarnSpinnerParser.hashtag_block.
virtual Result VisitHashtag ([NotNull] YarnSpinnerParser.HashtagContext context)
Visit a parse tree produced by YarnSpinnerParser.hashtag.
Package Functions
void generateClause (string jumpLabel, YarnSpinnerParser.StatementContext[] children, YarnSpinnerParser.ExpressionContext expression)
void genericExpVisitor (YarnSpinnerParser.ExpressionContext left, YarnSpinnerParser.ExpressionContext right, int op)
void opEquals (string varName, YarnSpinnerParser.ExpressionContext expression, int op)
Package Attributes
AntlrCompiler compiler
Private Member Functions
bool HandleFunction (string functionName, YarnSpinnerParser.ExpressionContext[] parameters)
string ShortcutText (YarnSpinnerParser.Shortcut_textContext context)
void loadOperators ()
Private Attributes
Dictionary< int, TokenType > tokens = new Dictionary<int, TokenType>()
Detailed Description
Definition at line 252 of file AntlrCompiler.cs.
Constructor & Destructor Documentation
Yarn.BodyVisitor.BodyVisitor (AntlrCompiler compiler)
Definition at line 256 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.compiler.
        {
            this.compiler = compiler;
            this.loadOperators();
        }
Member Function Documentation
void Yarn.BodyVisitor.generateClause (string jumpLabel, YarnSpinnerParser.StatementContext[] children, YarnSpinnerParser.ExpressionContext expression) [package]
Definition at line 468 of file AntlrCompiler.cs.
Referenced by Yarn.BodyVisitor.VisitIf_statement().
        {
            string endOfClauseLabel = compiler.RegisterLabel("skipclause");
            // handling the expression (if it has one)
            // will only be called on ifs and elseifs
            if (expression != null)
            {
                Visit(expression);
                compiler.Emit(ByteCode.JumpIfFalse, endOfClauseLabel);
            }
            // running through all of the children statements
            foreach (var child in children)
            {
                Visit(child);
            }
            compiler.Emit(ByteCode.JumpTo, jumpLabel);
            if (expression != null)
            {
                compiler.Emit(ByteCode.Label, endOfClauseLabel);
                compiler.Emit(ByteCode.Pop);
            }
        }
void Yarn.BodyVisitor.genericExpVisitor (YarnSpinnerParser.ExpressionContext left, YarnSpinnerParser.ExpressionContext right, int op) [package]
Definition at line 616 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.tokens.
Referenced by Yarn.BodyVisitor.VisitExpAddSub(), Yarn.BodyVisitor.VisitExpAndOrXor(), Yarn.BodyVisitor.VisitExpComparison(), Yarn.BodyVisitor.VisitExpEquality(), and Yarn.BodyVisitor.VisitExpMultDivMod().
        {
            Visit(left);
            Visit(right);
            // TODO: temp operator call
            compiler.Emit(ByteCode.CallFunc, tokens[op].ToString());
        }
bool Yarn.BodyVisitor.HandleFunction (string functionName, YarnSpinnerParser.ExpressionContext[] parameters) [private]
Definition at line 397 of file AntlrCompiler.cs.
References Yarn.FunctionInfo.paramCount.
        {
            // this will throw an exception if it doesn't exist
            FunctionInfo functionInfo = compiler.library.GetFunction(functionName);
            // if the function is not variadic we need to check it has the right number of params
            if (functionInfo.paramCount != -1)
            {
                if (parameters.Length != functionInfo.paramCount)
                {
                    // invalid function, return false
                    return false;
                }
            }
            // generate the instructions for all of the parameters
            foreach (var parameter in parameters)
            {
                Visit(parameter);
            }
            // if the function is variadic we push the parameter number onto the stack
            // variadic functions are those with paramCount of -1
            if (functionInfo.paramCount == -1)
            {
                compiler.Emit(ByteCode.PushNumber, parameters.Length);
            }
            // then call the function itself
            compiler.Emit(ByteCode.CallFunc, functionName);
            // everything went fine, return true
            return true;
        }
void Yarn.BodyVisitor.loadOperators () [private]
Definition at line 767 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.tokens.
        {
            // operators for the standard expressions
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_LESS_THAN_EQUALS] = TokenType.LessThanOrEqualTo;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_GREATER_THAN_EQUALS] =
      TokenType.GreaterThanOrEqualTo;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_LESS] = TokenType.LessThan;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_GREATER] = TokenType.GreaterThan;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_EQUALS] = TokenType.EqualTo;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_NOT_EQUALS] = TokenType.NotEqualTo;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_AND] = TokenType.And;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_OR] = TokenType.Or;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_XOR] = TokenType.Xor;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_ADDITION] = TokenType.Add;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_SUBTRACTION] = TokenType.Minus;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_MULTIPLICATION] = TokenType.Multiply;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_DIVISION] = TokenType.Divide;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_MODULUS] = TokenType.Modulo;
            // operators for the set expressions
            // these map directly to the operator if they didn't have the =
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_ADDITION_EQUALS] = TokenType.Add;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_SUBTRACTION_EQUALS] = TokenType.Minus;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_MULTIPLICATION_EQUALS] = TokenType.Multiply;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_DIVISION_EQUALS] = TokenType.Divide;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_MODULUS_EQUALS] = TokenType.Modulo;
        }
void Yarn.BodyVisitor.opEquals (string varName, YarnSpinnerParser.ExpressionContext expression, int op) [package]
Definition at line 668 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.tokens.
Referenced by Yarn.BodyVisitor.VisitExpMultDivModEquals(), and Yarn.BodyVisitor.VisitExpPlusMinusEquals().
        {
            // Get the current value of the variable
            compiler.Emit(ByteCode.PushVariable, varName);
            // run the expression
            Visit(expression);
            // Stack now contains [currentValue, expressionValue]
            // now we evaluate the operator
            // op will match to one of + - / * %
            compiler.Emit(ByteCode.CallFunc, tokens[op].ToString());
            // Stack now has the destination value
            // now store the variable and clean up the stack
            compiler.Emit(ByteCode.StoreVariable, varName);
            compiler.Emit(ByteCode.Pop);
        }
string Yarn.BodyVisitor.ShortcutText (YarnSpinnerParser.Shortcut_textContext context) [private]
Definition at line 497 of file AntlrCompiler.cs.
Referenced by Yarn.BodyVisitor.VisitShortcut_statement().
        {
            return context.SHORTCUT_TEXT().GetText().Trim();
        }
override int Yarn.BodyVisitor.VisitAction_statement (YarnSpinnerParser.Action_statementContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.action_statement.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 351 of file AntlrCompiler.cs.
        {
            char[] trimming = { '<', '>' };
            string action = context.GetText().Trim(trimming);
            // TODO: look into replacing this as it seems a bit odd
            switch (action)
            {
                case "stop":
                    compiler.Emit(ByteCode.Stop);
                    break;
                case "shuffleNextOptions":
                    compiler.Emit(ByteCode.PushBool, true);
                    compiler.Emit(ByteCode.StoreVariable, VirtualMachine.SpecialVariables.ShuffleOptions);
                    compiler.Emit(ByteCode.Pop);
                    compiler.flags.DisableShuffleOptionsAfterNextSet = true;
                    break;
                default:
                    compiler.Emit(ByteCode.RunCommand, action);
                    break;
            }
            return 0;
        }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitBody ([NotNull] YarnSpinnerParser.BodyContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.body.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 105 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitDialogue ([NotNull] YarnSpinnerParser.DialogueContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.dialogue.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 45 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitElse_clause ([NotNull] YarnSpinnerParser.Else_clauseContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.else_clause.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 195 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitElse_if_clause ([NotNull] YarnSpinnerParser.Else_if_clauseContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.else_if_clause.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 185 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
override int Yarn.BodyVisitor.VisitExpAddSub (YarnSpinnerParser.ExpAddSubContext context) [virtual]
Visit a parse tree produced by the expAddSub labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 632 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.genericExpVisitor().
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.
      Type);
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpAndOrXor (YarnSpinnerParser.ExpAndOrXorContext context) [virtual]
Visit a parse tree produced by the expAndOrXor labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 653 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.genericExpVisitor().
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.
      Type);
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpComparison (YarnSpinnerParser.ExpComparisonContext context) [virtual]
Visit a parse tree produced by the expComparison labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 639 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.genericExpVisitor().
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.
      Type);
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpEquality (YarnSpinnerParser.ExpEqualityContext context) [virtual]
Visit a parse tree produced by the expEquality labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 646 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.genericExpVisitor().
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.
      Type);
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpMultDivMod (YarnSpinnerParser.ExpMultDivModContext context) [virtual]
Visit a parse tree produced by the expMultDivMod labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 625 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.genericExpVisitor().
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.
      Type);
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpMultDivModEquals (YarnSpinnerParser.ExpMultDivModEqualsContext context) [virtual]
Visit a parse tree produced by the expMultDivModEquals labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 688 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.opEquals().
        {
            // call the helper to deal with this
            opEquals(context.variable().GetText(), context.expression(), context.op.Type);
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpNegative (YarnSpinnerParser.ExpNegativeContext context) [virtual]
Visit a parse tree produced by the expNegative labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 586 of file AntlrCompiler.cs.
        {
            Visit(context.expression());
            // TODO: temp operator call
            compiler.Emit(ByteCode.CallFunc, TokenType.UnaryMinus.ToString());
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpNot (YarnSpinnerParser.ExpNotContext context) [virtual]
Visit a parse tree produced by the expNot labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 596 of file AntlrCompiler.cs.
        {
            Visit(context.expression());
            // TODO: temp operator call
            compiler.Emit(ByteCode.CallFunc, TokenType.Not.ToString());
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpParens (YarnSpinnerParser.ExpParensContext context) [virtual]
Visit a parse tree produced by the expParens labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 581 of file AntlrCompiler.cs.
        {
            return Visit(context.expression());
        }
override int Yarn.BodyVisitor.VisitExpPlusMinusEquals (YarnSpinnerParser.ExpPlusMinusEqualsContext context) [virtual]
Visit a parse tree produced by the expPlusMinusEquals labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 695 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.opEquals().
        {
            // call the helper to deal with this
            opEquals(context.variable().GetText(), context.expression(), context.op.Type);
            return 0;
        }
override int Yarn.BodyVisitor.VisitExpValue (YarnSpinnerParser.ExpValueContext context) [virtual]
Visit a parse tree produced by the expValue labeled alternative in YarnSpinnerParser.expression.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 606 of file AntlrCompiler.cs.
        {
            return Visit(context.value());
        }
override int Yarn.BodyVisitor.VisitFunction (YarnSpinnerParser.FunctionContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.function.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 431 of file AntlrCompiler.cs.
        {
            string functionName = context.FUNC_ID().GetText();
            this.HandleFunction(functionName, context.expression());
            return 0;
        }
override int Yarn.BodyVisitor.VisitFunction_statement (YarnSpinnerParser.Function_statementContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.function_statement.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 380 of file AntlrCompiler.cs.
References preprocessor.output.
        {
            char[] lTrim = { '<' };
            char[] rTrim = { '(' };
            string functionName = context.GetChild(0).GetText().TrimStart(lTrim).TrimEnd(rTrim);
            var output = this.HandleFunction(functionName, context.expression());
            // failed to handle the function
            if (output == false)
            {
                Yarn.ParseException.Make(context, "Invalid number of parameters for " + functionName);
            }
            return 0;
        }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitHashtag ([NotNull] YarnSpinnerParser.HashtagContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.hashtag.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 285 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitHashtag_block ([NotNull] YarnSpinnerParser.Hashtag_blockContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.hashtag_block.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 275 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitHeader ([NotNull] YarnSpinnerParser.HeaderContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.header.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 65 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitHeader_line ([NotNull] YarnSpinnerParser.Header_lineContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.header_line.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 95 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitHeader_tag ([NotNull] YarnSpinnerParser.Header_tagContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.header_tag.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 85 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitHeader_title ([NotNull] YarnSpinnerParser.Header_titleContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.header_title.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 75 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitIf_clause ([NotNull] YarnSpinnerParser.If_clauseContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.if_clause.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 175 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
override int Yarn.BodyVisitor.VisitIf_statement (YarnSpinnerParser.If_statementContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.if_statement.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 442 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.generateClause().
        {
            // label to give us a jump point for when the if finishes
            string endOfIfStatementLabel = compiler.RegisterLabel("endif");
            // handle the if
            var ifClause = context.if_clause();
            generateClause(endOfIfStatementLabel, ifClause.statement(), ifClause.expression()
      );
            // all elseifs
            foreach (var elseIfClause in context.else_if_clause())
            {
                generateClause(endOfIfStatementLabel, elseIfClause.statement(),
      elseIfClause.expression());
            }
            // the else, if there is one
            var elseClause = context.else_clause();
            if (elseClause != null)
            {
                generateClause(endOfIfStatementLabel, elseClause.statement(), null);
            }
            compiler.Emit(ByteCode.Label, endOfIfStatementLabel);
            return 0;
        }
override int Yarn.BodyVisitor.VisitLine_statement (YarnSpinnerParser.Line_statementContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.line_statement.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 263 of file AntlrCompiler.cs.
        {
            // grabbing the line of text and stripping off any "'s if they had them
            string lineText = context.text().GetText().Trim('"');
            // getting the lineID from the hashtags if it has one
            string lineID = compiler.GetLineID(context.hashtag_block());
            // technically this only gets the line the statement started on
            int lineNumber = context.Start.Line;
            // TODO: why is this called num?
            string num = compiler.program.RegisterString(lineText, compiler.currentNode.name, lineID,
      lineNumber, true);
            compiler.Emit(ByteCode.RunLine, num);
            return 0;
        }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitNode ([NotNull] YarnSpinnerParser.NodeContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.node.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 55 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
override int Yarn.BodyVisitor.VisitOption_statement (YarnSpinnerParser.Option_statementContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.option_statement.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 284 of file AntlrCompiler.cs.
        {
            // if it is a split style option
            if (context.OPTION_LINK() != null)
            {
                string destination = context.OPTION_LINK().GetText();
                string label = context.OPTION_TEXT().GetText();
                int lineNumber = context.Start.Line;
                // getting the lineID from the hashtags if it has one
                string lineID = compiler.GetLineID(context.hashtag_block());
                string stringID = compiler.program.RegisterString(label, compiler.currentNode.name, lineID,
       lineNumber, true);
                compiler.Emit(ByteCode.AddOption, stringID, destination);
            }
            else
            {
                string destination = context.OPTION_TEXT().GetText();
                compiler.Emit(ByteCode.RunNode, destination);
            }
            return 0;
        }
override int Yarn.BodyVisitor.VisitSet_statement (YarnSpinnerParser.Set_statementContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.set_statement.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 313 of file AntlrCompiler.cs.
        {
            // if it is the first form
            // a regular << SET $varName TO expression >>
            if (context.variable() != null)
            {
                // add the expression (whatever it resolves to)
                Visit(context.expression());
                // now store the variable and clean up the stack
                string variableName = context.variable().GetText();
                compiler.Emit(ByteCode.StoreVariable, variableName);
                compiler.Emit(ByteCode.Pop);
            }
            // it is the second form
            else
            {
                // checking the expression is of the correct form
                var expression = context.expression();
                // TODO: is there really no more elegant way of doing this?!
                if (expression is YarnSpinnerParser.ExpMultDivModEqualsContext ||
                    expression is YarnSpinnerParser.ExpPlusMinusEqualsContext)
                {
                    // run the expression, it handles it from here
                    Visit(expression);
                }
                else
                {
                    // throw an error
                    throw Yarn.ParseException.Make(context,"Invalid expression inside assignment statement"
      );
                }
            }
            return 0;
        }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitShortcut ([NotNull] YarnSpinnerParser.ShortcutContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.shortcut.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 135 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitShortcut_conditional ([NotNull] YarnSpinnerParser.Shortcut_conditionalContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.shortcut_conditional.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 145 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
override int Yarn.BodyVisitor.VisitShortcut_statement (YarnSpinnerParser.Shortcut_statementContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.shortcut_statement.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 503 of file AntlrCompiler.cs.
References Yarn.BodyVisitor.compiler, Yarn.AntlrCompiler.CompileFlags.DisableShuffleOptionsAfterNextSet, Yarn.AntlrCompiler.flags, and Yarn.BodyVisitor.ShortcutText().
        {
            string endOfGroupLabel = compiler.RegisterLabel("group_end");
            var labels = new List<string>();
            int optionCount = 0;
            foreach (var shortcut in context.shortcut())
            {
                string optionDestinationLabel = compiler.RegisterLabel("option_" + (optionCount + 1));
                labels.Add(optionDestinationLabel);
                string endOfClauseLabel = null;
                if (shortcut.shortcut_conditional() != null)
                {
                    endOfClauseLabel = compiler.RegisterLabel("conditional_" + optionCount);
                    Visit(shortcut.shortcut_conditional().expression());
                    compiler.Emit(ByteCode.JumpIfFalse, endOfClauseLabel);
                }
                // getting the lineID from the hashtags if it has one
                string lineID = compiler.GetLineID(shortcut.hashtag_block());
                string shortcutLine = ShortcutText(shortcut.shortcut_text());
                string labelStringID = compiler.program.RegisterString(shortcutLine,
      compiler.currentNode.name, lineID, shortcut.Start.Line, true);
                compiler.Emit(ByteCode.AddOption, labelStringID, optionDestinationLabel);
                if (shortcut.shortcut_conditional() != null)
                {
                    compiler.Emit(ByteCode.Label, endOfClauseLabel);
                    compiler.Emit(ByteCode.Pop);
                }
                optionCount++;
            }
            compiler.Emit(ByteCode.ShowOptions);
            // TODO: investigate a cleaner way because this is odd...
            if (compiler.flags.DisableShuffleOptionsAfterNextSet
       == true)
            {
                compiler.Emit(ByteCode.PushBool, false);
                compiler.Emit(ByteCode.StoreVariable, VirtualMachine.SpecialVariables.ShuffleOptions);
                compiler.Emit(ByteCode.Pop);
                compiler.flags.DisableShuffleOptionsAfterNextSet = false;
            }
            compiler.Emit(ByteCode.Jump);
            optionCount = 0;
            foreach (var shortcut in context.shortcut())
            {
                compiler.Emit(ByteCode.Label, labels[optionCount]);
                // running through all the children statements of the shortcut
                foreach (var child in shortcut.statement())
                {
                    Visit(child);
                }
                compiler.Emit(ByteCode.JumpTo, endOfGroupLabel);
                optionCount++;
            }
            compiler.Emit(ByteCode.Label, endOfGroupLabel);
            compiler.Emit(ByteCode.Pop);
            return 0;
        }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitShortcut_text ([NotNull] YarnSpinnerParser.Shortcut_textContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.shortcut_text.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 155 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitStatement ([NotNull] YarnSpinnerParser.StatementContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.statement.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 115 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
virtual Result YarnSpinnerParserBaseVisitor< Result >.VisitText ([NotNull] YarnSpinnerParser.TextContext context) [virtual], [inherited]
Visit a parse tree produced by YarnSpinnerParser.text.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Implements IYarnSpinnerParserVisitor< Result >.
Definition at line 255 of file YarnSpinnerParserBaseVisitor.cs.
{ return VisitChildren(context); }
override int Yarn.BodyVisitor.VisitValueFalse (YarnSpinnerParser.ValueFalseContext context) [virtual]
Visit a parse tree produced by the valueFalse labeled alternative in YarnSpinnerParser.value.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 726 of file AntlrCompiler.cs.
        {
            compiler.Emit(ByteCode.PushBool, false);
            return 0;
        }
override int Yarn.BodyVisitor.VisitValueFunc (YarnSpinnerParser.ValueFuncContext context) [virtual]
Visit a parse tree produced by the valueFunc labeled alternative in YarnSpinnerParser.value.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 751 of file AntlrCompiler.cs.
        {
            Visit(context.function());
            return 0;
        }
override int Yarn.BodyVisitor.VisitValueNull (YarnSpinnerParser.ValueNullContext context) [virtual]
Visit a parse tree produced by the valueNull labeled alternative in YarnSpinnerParser.value.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 758 of file AntlrCompiler.cs.
        {
            compiler.Emit(ByteCode.PushNull);
            return 0;
        }
override int Yarn.BodyVisitor.VisitValueNumber (YarnSpinnerParser.ValueNumberContext context) [virtual]
Visit a parse tree produced by the valueNumber labeled alternative in YarnSpinnerParser.value.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 713 of file AntlrCompiler.cs.
        {
            float number = float.Parse(context.BODY_NUMBER().GetText(), CultureInfo.InvariantCulture);
            compiler.Emit(ByteCode.PushNumber, number);
            return 0;
        }
override int Yarn.BodyVisitor.VisitValueString (YarnSpinnerParser.ValueStringContext context) [virtual]
Visit a parse tree produced by the valueString labeled alternative in YarnSpinnerParser.value.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 738 of file AntlrCompiler.cs.
        {
            // stripping the " off the front and back
            // actually is this what we want?
            string stringVal = context.COMMAND_STRING().GetText().Trim('"');
            int lineNumber = context.Start.Line;
            string id = compiler.program.RegisterString(stringVal, compiler.currentNode.name, null,
      lineNumber, false);
            compiler.Emit(ByteCode.PushString, id);
            return 0;
        }
override int Yarn.BodyVisitor.VisitValueTrue (YarnSpinnerParser.ValueTrueContext context) [virtual]
Visit a parse tree produced by the valueTrue labeled alternative in YarnSpinnerParser.value.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 720 of file AntlrCompiler.cs.
        {
            compiler.Emit(ByteCode.PushBool, true);
            return 0;
        }
override int Yarn.BodyVisitor.VisitValueVar (YarnSpinnerParser.ValueVarContext context) [virtual]
Visit a parse tree produced by the valueVar labeled alternative in YarnSpinnerParser.value.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 709 of file AntlrCompiler.cs.
        {
            return Visit(context.variable());
        }
override int Yarn.BodyVisitor.VisitVariable (YarnSpinnerParser.VariableContext context) [virtual]
Visit a parse tree produced by YarnSpinnerParser.variable.
The default implementation returns the result of calling AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode) on context .
Parameters
context The parse tree.
<return>The visitor result.</return>
Reimplemented from YarnSpinnerParserBaseVisitor< Result >.
Definition at line 731 of file AntlrCompiler.cs.
        {
            string variableName = context.VAR_ID().GetText();
            compiler.Emit(ByteCode.PushVariable, variableName);
            return 0;
        }
Member Data Documentation
AntlrCompiler Yarn.BodyVisitor.compiler [package]
Definition at line 254 of file AntlrCompiler.cs.
Referenced by Yarn.BodyVisitor.BodyVisitor(), and Yarn.BodyVisitor.VisitShortcut_statement().
Dictionary<int, TokenType> Yarn.BodyVisitor.tokens = new Dictionary<int, TokenType>() [private]
Definition at line 766 of file AntlrCompiler.cs.
Referenced by Yarn.BodyVisitor.genericExpVisitor(), Yarn.BodyVisitor.loadOperators(), and Yarn.BodyVisitor.opEquals().
The documentation for this class was generated from the following file:
YarnSpinner/AntlrCompiler.cs