Yarn.Parser.Block Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
Block (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Static Package Functions
static bool CanParse (Parser p)
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
IEnumerable< Statement > statements [get]
Private Attributes
List< Statement > _statements = new List<Statement> ()
Detailed Description
Definition at line 436 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.Block.Block (ParseNode parent, Parser p) [package]
Definition at line 447 of file Parser.cs.
References Yarn.Parser.NextSymbolIs().
                                                       : base(parent, p) {
                // Read the indent token
                p.ExpectSymbol(TokenType.Indent);
                // Keep reading statements until we hit a dedent
                while (p.NextSymbolIs(TokenType.Dedent) == false) {
                    // fun fact! because Blocks are a type of Statement,
                    // we get nested block parsing for free! \:D/
                    _statements.Add(new Statement(this, p));
                }
                // Tidy up by reading the dedent
                p.ExpectSymbol(TokenType.Dedent);
            }
Member Function Documentation
static bool Yarn.Parser.Block.CanParse (Parser p) [static], [package]
Definition at line 437 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
            {
                return p.NextSymbolIs (TokenType.Indent);
            }
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.Block.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 464 of file Parser.cs.
References Yarn.Parser.Block._statements, and Yarn.Parser.Tab().
            {
                var sb = new StringBuilder ();
                sb.Append (Tab(indentLevel, "Block {"));
                foreach (var statement in _statements) {
                    sb.Append (statement.PrintTree (indentLevel + 1));
                }
                sb.Append (Tab(indentLevel, "}"));
                return sb.ToString ();
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
List<Statement> Yarn.Parser.Block._statements = new List<Statement> () [private]
Definition at line 445 of file Parser.cs.
Referenced by Yarn.Parser.Block.PrintTree().
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Property Documentation
IEnumerable<Statement> Yarn.Parser.Block.statements [get], [package]
Definition at line 443 of file Parser.cs.
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs