Yarn.Dialogue Class Reference
The Dialogue class is the main thing that clients will use.
Classes
class CommandResult
The client should run a command (it's up to them to parse the string)
class LineResult
The client should run a line of dialogue.
class NodeCompleteResult
We've reached the end of this node.
class OptionSetResult
The client should show a list of options, and call setSelectedOptionDelegate before asking for the next line. It's an error if you don't.
class RunnerResult
Represents something for the end user (`client`) of the Dialogue class to do.
class StandardLibrary
The standard, built-in library of functions and operators.
Public Types
enum CompiledFormat { CompiledFormat.V1
 }
Public Member Functions
Dialogue (Yarn.VariableStorage continuity)
void LoadFile (string fileName, bool showTokens=false, bool showParseTree=false, string onlyConsiderNode=null)
Load a file from disk.
void LoadCompiledProgram (byte[] bytes, string fileName, CompiledFormat format=LATEST_FORMAT)
void LoadString (string text, string fileName=`<input>`, bool showTokens=false, bool showParseTree=false, string onlyConsiderNode=null)
Ask the loader to parse a string.
IEnumerable
*
< Yarn.Dialogue.RunnerResult > Run (string startNode=DEFAULT_START)
Use this in a for-each construct; each time you iterate over it, you'll get a line, command, or set of options.
void Stop ()
Dictionary< string, string > GetTextForAllNodes ()
string GetTextForNode (string nodeName)
Returns the source code for the node 'nodeName', if that node was tagged with rawText.
Dictionary< string,
*
IEnumerable< string > > GetTagsForAllNodes ()
IEnumerable< string > GetTagsForNode (string nodeName)
Returns the tags for the node 'nodeName'.
void AddStringTable (Dictionary< string, string > stringTable)
Dictionary< string, string > GetStringTable ()
byte[] GetCompiledProgram (CompiledFormat format=LATEST_FORMAT)
void UnloadAll (bool clearVisitedNodes=true)
Unloads ALL nodes.
String Compile ()
String GetByteCode ()
bool NodeExists (string nodeName)
void Analyse (Analysis.Context context)
Public Attributes
bool experimentalMode = false
We'll ask this object for the state of variables.
Logger LogDebugMessage
Delegates used for logging.
Logger LogErrorMessage
const string DEFAULT_START = `Start`
The node we start from.
Library library
The library contains all of the functions and operators we know about.
Dictionary< String, int > visitedNodeCount = new Dictionary<string, int>()
The collection of nodes that we've seen.
const CompiledFormat LATEST_FORMAT = CompiledFormat.V1
Package Functions
Dictionary< string, LineInfo > GetStringInfoTable ()
Package Attributes
VariableStorage continuity
Loader loader
The loader contains all of the nodes we're going to run.
Program program
The Program is the compiled Yarn program.
Properties
IEnumerable< string > visitedNodes [get, set]
IEnumerable< string > allNodes [get]
string currentNode [get]
Private Member Functions
object YarnFunctionNodeVisitCount (Value[] parameters)
A function exposed to Yarn that returns the number of times a node has been run.
object YarnFunctionIsNodeVisited (Value[] parameters)
A Yarn function that returns true if the named node, or the current node if no parameters were provided, has been visited at least once.
void LoadCompiledProgramV1 (byte[] bytes)
byte[] GetCompiledProgramV1 ()
Private Attributes
VirtualMachine vm
Detailed Description
The Dialogue class is the main thing that clients will use.
Definition at line 130 of file Dialogue.cs.
Member Enumeration Documentation
enum Yarn.Dialogue.CompiledFormat
Enumerator
V1
Definition at line 552 of file Dialogue.cs.
        {
            V1
        }
Constructor & Destructor Documentation
Yarn.Dialogue.Dialogue (Yarn.VariableStorage continuity)
Definition at line 254 of file Dialogue.cs.
References Yarn.Dialogue.continuity, Yarn.Dialogue.library, Yarn.Dialogue.loader, Yarn.ReturningFunction(), Yarn.Dialogue.YarnFunctionIsNodeVisited(), and Yarn.Dialogue.YarnFunctionNodeVisitCount().
                                                         {
            this.continuity = continuity;
            loader = new Loader (this);
            library = new Library ();
            library.ImportLibrary (new StandardLibrary ());
            // Register the "visited" function, which returns true if we've visited
            // a node previously (nodes are marked as visited when we leave them)
            library.RegisterFunction ("visited", -1, (ReturningFunction)
      YarnFunctionIsNodeVisited);
            // Register the "visitCount" function, which returns the number of times
            // a node has been run (which increments when a node ends). If called with
            // no parameters, check the CURRENT node.
            library.RegisterFunction ("visitCount", -1, (ReturningFunction)
      YarnFunctionNodeVisitCount);
        }
Member Function Documentation
void Yarn.Dialogue.AddStringTable (Dictionary< string, string > stringTable)
Definition at line 539 of file Dialogue.cs.
        {
            program.LoadStrings(stringTable);
        }
void Yarn.Dialogue.Analyse (Analysis.Context context)
Definition at line 617 of file Dialogue.cs.
                                                      {
            context.AddProgramToAnalysis (this.program);
        }
String Yarn.Dialogue.Compile ()
Definition at line 595 of file Dialogue.cs.
References Yarn.Dialogue.library.
                                {
            return program.DumpCode (library);
        }
String Yarn.Dialogue.GetByteCode ()
Definition at line 599 of file Dialogue.cs.
References Yarn.Dialogue.library.
                                    {
            return program.DumpCode (library);
        }
byte [] Yarn.Dialogue.GetCompiledProgram (CompiledFormat format = LATEST_FORMAT)
Definition at line 559 of file Dialogue.cs.
References Yarn.Dialogue.GetCompiledProgramV1().
        {
            switch (format)
            {
                case CompiledFormat.V1:
                    return GetCompiledProgramV1();
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }
byte [] Yarn.Dialogue.GetCompiledProgramV1 () [private]
Definition at line 571 of file Dialogue.cs.
Referenced by Yarn.Dialogue.GetCompiledProgram().
        {
            using (var outputStream = new System.IO.MemoryStream())
            {
                using (var bsonWriter = new Newtonsoft.Json.Bson.BsonWriter(outputStream))
                {
                    var s = new Newtonsoft.Json.JsonSerializer();
                    s.Serialize(bsonWriter, this.program);
                }
                return outputStream.ToArray();
            }
        }
Dictionary<string,LineInfo> Yarn.Dialogue.GetStringInfoTable () [package]
Definition at line 548 of file Dialogue.cs.
                                                                  {
            return program.lineInfo;
        }
Dictionary<string,string> Yarn.Dialogue.GetStringTable ()
Definition at line 544 of file Dialogue.cs.
                                                          {
            return program.strings;
        }
Dictionary<string, IEnumerable<string> > Yarn.Dialogue.GetTagsForAllNodes ()
Definition at line 511 of file Dialogue.cs.
References Yarn.Program.nodes, and Yarn.Dialogue.program.
                                                                            {
            var d = new Dictionary<string,IEnumerable<string>>();
            foreach (var node in program.nodes) {
                var tags = program.GetTagsForNode(node.Key);
                if (tags == null)
                    continue;
                d [node.Key] = tags;
            }
            return d;
        }
IEnumerable<string> Yarn.Dialogue.GetTagsForNode (string nodeName)
Returns the tags for the node 'nodeName'.
Definition at line 527 of file Dialogue.cs.
References Yarn.Dialogue.LogErrorMessage, Yarn.Program.nodes, and Yarn.Dialogue.program.
                                                                   {
            if (program.nodes.Count == 0) {
                LogErrorMessage ("No nodes are loaded!");
                return null;
            } else if (program.nodes.ContainsKey(nodeName)) {
                return program.GetTagsForNode (nodeName);
            } else {
                LogErrorMessage ("No node named " + nodeName);
                return null;
            }
        }
Dictionary<string, string> Yarn.Dialogue.GetTextForAllNodes ()
Definition at line 483 of file Dialogue.cs.
References Yarn.Program.nodes, and Yarn.Dialogue.program.
                                                               {
            var d = new Dictionary<string,string>();
            foreach (var node in program.nodes) {
                var text = program.GetTextForNode(node.Key);
                if (text == null)
                    continue;
                d [node.Key] = text;
            }
            return d;
        }
string Yarn.Dialogue.GetTextForNode (string nodeName)
Returns the source code for the node 'nodeName', if that node was tagged with rawText.
Definition at line 499 of file Dialogue.cs.
References Yarn.Dialogue.LogErrorMessage, Yarn.Program.nodes, and Yarn.Dialogue.program.
                                                      {
            if (program.nodes.Count == 0) {
                LogErrorMessage ("No nodes are loaded!");
                return null;
            } else if (program.nodes.ContainsKey(nodeName)) {
                return program.GetTextForNode (nodeName);
            } else {
                LogErrorMessage ("No node named " + nodeName);
                return null;
            }
        }
void Yarn.Dialogue.LoadCompiledProgram (byte[] bytes, string fileName, CompiledFormat format = LATEST_FORMAT)
Definition at line 295 of file Dialogue.cs.
References Yarn.Dialogue.LoadCompiledProgramV1(), Yarn.Dialogue.LogDebugMessage, and Yarn.Dialogue.LogErrorMessage.
Referenced by Yarn.Dialogue.LoadFile().
        {
            if (LogDebugMessage == null)
            {
                throw new YarnException("LogDebugMessage must be set before loading");
            }
            if (LogErrorMessage == null)
            {
                throw new YarnException("LogErrorMessage must be set before loading");
            }
            switch (format)
            {
                case CompiledFormat.V1:
                    LoadCompiledProgramV1(bytes);
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }
void Yarn.Dialogue.LoadCompiledProgramV1 (byte[] bytes) [private]
Definition at line 319 of file Dialogue.cs.
References Yarn.Dialogue.LogErrorMessage, and Yarn.Dialogue.program.
Referenced by Yarn.Dialogue.LoadCompiledProgram().
        {
            using (var stream = new System.IO.MemoryStream(bytes))
            {
                using (var reader = new Newtonsoft.Json.Bson.BsonReader(stream))
                {
                    var serializer = new Newtonsoft.Json.JsonSerializer();
                    try
                    {
                        // Load the stored program
                        var newProgram = serializer.Deserialize<Program>(reader);
                        // Merge it with our existing one, if present
                        if (program != null)
                        {
                            program.Include(newProgram);
                        }
                        else {
                            program = newProgram;
                        }
                    }
                    catch (Newtonsoft.Json.JsonReaderException e)
                    {
                        LogErrorMessage(string.Format(CultureInfo.CurrentCulture, "Cannot
       load compiled program: {0}", e.Message));
                    }
                }
            }
        }
void Yarn.Dialogue.LoadFile (string fileName, bool showTokens = false, bool showParseTree = false, string onlyConsiderNode = null)
Load a file from disk.
Definition at line 273 of file Dialogue.cs.
References Yarn.Dialogue.LoadCompiledProgram(), and Yarn.Dialogue.LoadString().
                                                                                                           
                            {
            // Is this a compiled program file?
            if (fileName.EndsWith(".yarn.bytes", StringComparison.InvariantCulture)) {
                var bytes = System.IO.File.ReadAllBytes(fileName);
                LoadCompiledProgram(bytes, fileName);
                return;
            } else {
                // It's source code, either a single node in text form or a JSON file
                string inputString;
                using (System.IO.StreamReader reader = new System.IO.StreamReader(fileName))
                {
                    inputString = reader.ReadToEnd();
                }
                LoadString(inputString, fileName, showTokens, showParseTree, onlyConsiderNode);
            }
        }
void Yarn.Dialogue.LoadString (string text, string fileName = `<input>`, bool showTokens = false, bool showParseTree = false, string onlyConsiderNode = null)
Ask the loader to parse a string.
Returns the number of nodes that were loaded.
Definition at line 352 of file Dialogue.cs.
References Yarn.Dialogue.library, Yarn.Dialogue.LogDebugMessage, Yarn.Dialogue.LogErrorMessage, and Yarn.Dialogue.program.
Referenced by Yarn.Dialogue.LoadFile().
                                                                                                           
                                                 {
            if (LogDebugMessage == null) {
                throw new YarnException ("LogDebugMessage must be set before loading");
            }
            if (LogErrorMessage == null) {
                throw new YarnException ("LogErrorMessage must be set before loading");
            }
            // Try to infer the type
            NodeFormat format;
            if (text.StartsWith("[", StringComparison.Ordinal)) {
                // starts with a {? this is probably a JSON array
                format = NodeFormat.JSON;
            } else if (text.Contains("---")) {
                // contains a --- delimiter? probably multi node text
                format = NodeFormat.Text;
            } else {
                // fall back to the single node format
                format = NodeFormat.SingleNodeText;
            }
            program = loader.Load(text, library, fileName, program, showTokens,
      showParseTree, onlyConsiderNode, format, this.experimentalMode);
        }
bool Yarn.Dialogue.NodeExists (string nodeName)
Definition at line 603 of file Dialogue.cs.
References Yarn.Dialogue.LogDebugMessage, Yarn.Dialogue.LogErrorMessage, Yarn.Program.nodes, and Yarn.Dialogue.program.
Referenced by Yarn.Dialogue.YarnFunctionNodeVisitCount().
                                                {
            if (program == null) {
                LogErrorMessage ("Tried to call NodeExists, but no nodes " +
                                 "have been compiled!");
                return false;
            }
            if (program.nodes == null || program.nodes.Count == 0) {
                LogDebugMessage ("Called NodeExists, but there are zero nodes. " +
                                 "This may be an error.");
                return false;
            }
            return program.nodes.ContainsKey(nodeName);
        }
IEnumerable<Yarn.Dialogue.RunnerResult> Yarn.Dialogue.Run (string startNode = DEFAULT_START)
Use this in a for-each construct; each time you iterate over it, you'll get a line, command, or set of options.
Definition at line 387 of file Dialogue.cs.
References Yarn.VirtualMachine.executionState, Yarn.Dialogue.LogDebugMessage, Yarn.Dialogue.LogErrorMessage, Yarn.Dialogue.program, Yarn.VirtualMachine.SetNode(), Yarn.Dialogue.visitedNodeCount, and Yarn.Dialogue.vm.
Referenced by Yarn.YarnSpinnerConsole.Run().
                                                                                             {
            if (LogDebugMessage == null) {
                throw new YarnException ("LogDebugMessage must be set before running");
            }
            if (LogErrorMessage == null) {
                throw new YarnException ("LogErrorMessage must be set before running");
            }
            if (program == null) {
                LogErrorMessage ("Dialogue.Run was called, but no program was loaded.
       Stopping.");
                yield break;
            }
            vm = new VirtualMachine (this, program);
            RunnerResult latestResult;
            vm.lineHandler = delegate(LineResult result) {
                latestResult = result;
            };
            vm.commandHandler = delegate(CommandResult result) {
                // Is it the special custom command "<<stop>>"?
                if (result is CommandResult && (result as CommandResult).command.text == "stop") {
                    vm.Stop();
                }
                latestResult = result;
            };
            vm.nodeCompleteHandler = delegate(NodeCompleteResult result) {
                // get the count if it's there, otherwise it defaults to 0
                int count = 0;
                visitedNodeCount.TryGetValue(vm.currentNodeName, out count);
                visitedNodeCount[vm.currentNodeName] = count + 1;
                latestResult = result;
            };
            vm.optionsHandler = delegate(OptionSetResult result) {
                latestResult = result;
            };
            if (vm.SetNode (startNode) == false) {
                yield break;
            }
            // Run until the program stops, pausing to yield important
            // results
            do {
                latestResult = null;
                vm.RunNext ();
                if (latestResult != null)
                    yield return latestResult;
            } while (vm.executionState != VirtualMachine.ExecutionState.Stopped);
        }
void Yarn.Dialogue.Stop ()
Definition at line 449 of file Dialogue.cs.
References Yarn.Dialogue.vm.
                           {
            if (vm != null)
                vm.Stop();
        }
void Yarn.Dialogue.UnloadAll (bool clearVisitedNodes = true)
Unloads ALL nodes.
Definition at line 586 of file Dialogue.cs.
References Yarn.Dialogue.program.
                                                             {
            if (clearVisitedNodes)
                visitedNodeCount.Clear();
            program = null;
        }
object Yarn.Dialogue.YarnFunctionIsNodeVisited (Value[] parameters) [private]
A Yarn function that returns true if the named node, or the current node if no parameters were provided, has been visited at least once.
Definition at line 249 of file Dialogue.cs.
References Yarn.Dialogue.YarnFunctionNodeVisitCount().
Referenced by Yarn.Dialogue.Dialogue().
        {
            return (int)YarnFunctionNodeVisitCount(parameters) > 0;
        }
object Yarn.Dialogue.YarnFunctionNodeVisitCount (Value[] parameters) [private]
A function exposed to Yarn that returns the number of times a node has been run.
If no parameters are supplied, returns the number of time the current node has been run.
Definition at line 215 of file Dialogue.cs.
References Yarn.Dialogue.LogErrorMessage, and Yarn.Dialogue.NodeExists().
Referenced by Yarn.Dialogue.Dialogue(), and Yarn.Dialogue.YarnFunctionIsNodeVisited().
        {
            // Determine the node we're checking
            string nodeName;
            if (parameters.Length == 0) {
                // No parameters? Check the current node
                nodeName = vm.currentNodeName;
            } else if (parameters.Length == 1) {
                // A parameter? Check the named node
                nodeName = parameters [0].AsString;
                // Ensure this node exists
                if (NodeExists (nodeName) == false) {
                    var errorMessage = string.Format (CultureInfo.CurrentCulture, "The node {0} does not "
      + "exist.", nodeName);
                    LogErrorMessage (errorMessage);
                    return 0;
                }
            } else {
                // We got too many parameters
                var errorMessage = string.Format (CultureInfo.CurrentCulture, "Incorrect number of
       parameters to " + "visitCount (expected 0 or 1, got {0})", parameters.Length);
                LogErrorMessage (errorMessage);
                return 0;
            }
            // Figure out how many times this node was run
            int visitCount = 0;
            visitedNodeCount.TryGetValue (nodeName, out visitCount);
            return visitCount;
        }
Member Data Documentation
VariableStorage Yarn.Dialogue.continuity [package]
Definition at line 133 of file Dialogue.cs.
Referenced by Yarn.Dialogue.Dialogue(), and Yarn.VirtualMachine.RunInstruction().
const string Yarn.Dialogue.DEFAULT_START = `Start`
The node we start from.
Definition at line 197 of file Dialogue.cs.
bool Yarn.Dialogue.experimentalMode = false
We'll ask this object for the state of variables.
Definition at line 135 of file Dialogue.cs.
const CompiledFormat Yarn.Dialogue.LATEST_FORMAT = CompiledFormat.V1
Definition at line 557 of file Dialogue.cs.
Library Yarn.Dialogue.library
The library contains all of the functions and operators we know about.
Definition at line 206 of file Dialogue.cs.
Referenced by Yarn.Dialogue.Compile(), Yarn.Dialogue.Dialogue(), Yarn.Dialogue.GetByteCode(), Yarn.Dialogue.LoadString(), and Yarn.VirtualMachine.RunInstruction().
Loader Yarn.Dialogue.loader [package]
The loader contains all of the nodes we're going to run.
Definition at line 200 of file Dialogue.cs.
Referenced by Yarn.Dialogue.Dialogue().
Logger Yarn.Dialogue.LogDebugMessage
Delegates used for logging.
Definition at line 193 of file Dialogue.cs.
Referenced by Yarn.Dialogue.LoadCompiledProgram(), Yarn.Dialogue.LoadString(), Yarn.Dialogue.NodeExists(), and Yarn.Dialogue.Run().
Logger Yarn.Dialogue.LogErrorMessage
Definition at line 194 of file Dialogue.cs.
Referenced by Yarn.Dialogue.GetTagsForNode(), Yarn.Dialogue.GetTextForNode(), Yarn.Dialogue.LoadCompiledProgram(), Yarn.Dialogue.LoadCompiledProgramV1(), Yarn.Dialogue.LoadString(), Yarn.Dialogue.NodeExists(), Yarn.Dialogue.Run(), and Yarn.Dialogue.YarnFunctionNodeVisitCount().
Program Yarn.Dialogue.program [package]
The Program is the compiled Yarn program.
Definition at line 203 of file Dialogue.cs.
Referenced by Yarn.Dialogue.GetTagsForAllNodes(), Yarn.Dialogue.GetTagsForNode(), Yarn.Dialogue.GetTextForAllNodes(), Yarn.Dialogue.GetTextForNode(), Yarn.Dialogue.LoadCompiledProgramV1(), Yarn.Dialogue.LoadString(), Yarn.Dialogue.NodeExists(), Yarn.Dialogue.Run(), and Yarn.Dialogue.UnloadAll().
Dictionary<String, int> Yarn.Dialogue.visitedNodeCount = new Dictionary<string, int>()
The collection of nodes that we've seen.
Definition at line 209 of file Dialogue.cs.
Referenced by Yarn.Dialogue.Run().
VirtualMachine Yarn.Dialogue.vm [private]
Definition at line 381 of file Dialogue.cs.
Referenced by Yarn.Dialogue.Run(), and Yarn.Dialogue.Stop().
Property Documentation
IEnumerable<string> Yarn.Dialogue.allNodes [get]
Definition at line 466 of file Dialogue.cs.
string Yarn.Dialogue.currentNode [get]
Definition at line 472 of file Dialogue.cs.
IEnumerable<string> Yarn.Dialogue.visitedNodes [get], [set]
Definition at line 454 of file Dialogue.cs.
The documentation for this class was generated from the following file:
YarnSpinner/Dialogue.cs