Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation Class Reference
Public Member Functions
ConsoleRunnerImplementation (bool waitForLines=false)
void RunLine (Yarn.Line lineText)
void RunOptions (Options optionsGroup, OptionChooser optionChooser)
void RunCommand (string command)
void DialogueComplete ()
void HandleErrorMessage (string error)
void HandleDebugMessage (string message)
virtual void SetNumber (string variableName, float number)
virtual float GetNumber (string variableName)
virtual void SetValue (string variableName, Value value)
virtual Value GetValue (string variableName)
void Clear ()
Public Attributes
int numberOfExpectedOptions = -1
int autoSelectOptionNumber = -1
string expectedNextLine = null
string expectedNextCommand = null
bool autoSelectFirstOption = false
Private Attributes
bool waitForLines = false
Yarn.MemoryVariableStore variableStore
Detailed Description
Definition at line 504 of file Main.cs.
Constructor & Destructor Documentation
Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.ConsoleRunnerImplementation (bool waitForLines = false)
Definition at line 525 of file Main.cs.
References Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.waitForLines.
            {
                this.variableStore = new MemoryVariableStore();
                this.waitForLines = waitForLines;
            }
Member Function Documentation
void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.Clear ()
Implements Yarn.VariableStorage.
Definition at line 680 of file Main.cs.
            {
                variableStore.Clear();
            }
void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.DialogueComplete ()
Definition at line 645 of file Main.cs.
            {
                // All done
            }
virtual float Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.GetNumber (string variableName) [virtual]
Implements Yarn.VariableStorage.
Definition at line 665 of file Main.cs.
            {
                return variableStore.GetValue(variableName).AsNumber;
            }
virtual Value Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.GetValue (string variableName) [virtual]
Implements Yarn.VariableStorage.
Definition at line 675 of file Main.cs.
            {
                return variableStore.GetValue(variableName);
            }
void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.HandleDebugMessage (string message)
Definition at line 655 of file Main.cs.
References Yarn.YarnSpinnerConsole.Note().
            {
                Note(message);
            }
void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.HandleErrorMessage (string error)
Definition at line 650 of file Main.cs.
References Yarn.YarnSpinnerConsole.Error().
            {
                Error(error);
            }
void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunCommand (string command)
Definition at line 630 of file Main.cs.
References Yarn.YarnSpinnerConsole.Error(), and Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.expectedNextCommand.
            {
                if (expectedNextCommand != null &&
      expectedNextCommand != command)
                {
                    // TODO: Output diagnostic info here
                    Error(string.Format(CultureInfo.CurrentCulture, "Unexpected command.\n\tExpected:
       {0}\n\tReceived: {1}",
                                        expectedNextCommand, command));
                }
                expectedNextCommand = null;
                Console.WriteLine("Command: <<" + command + ">>");
            }
void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunLine (Yarn.Line lineText)
Definition at line 531 of file Main.cs.
References Yarn.YarnSpinnerConsole.Error(), Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.expectedNextLine, and Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.waitForLines.
            {
                if (expectedNextLine != null && expectedNextLine !=
      lineText.text)
                {
                    // TODO: Output diagnostic info here
                    Error(string.Format(CultureInfo.CurrentCulture, "Unexpected line.\nExpected: {0}\n
      Received: {1}",
                        expectedNextLine, lineText.text));
                }
                expectedNextLine = null;
                Console.WriteLine(lineText.text);
                if (waitForLines == true)
                {
                    Console.Read();
                }
            }
void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunOptions (Options optionsGroup, OptionChooser optionChooser)
Definition at line 551 of file Main.cs.
References Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.autoSelectFirstOption, Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.autoSelectOptionNumber, Yarn.YarnSpinnerConsole.Error(), Yarn.YarnSpinnerConsole.Note(), Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.numberOfExpectedOptions, and Yarn.Options.options.
            {
                Console.WriteLine("Options:");
                for (int i = 0; i < optionsGroup.options.Count; i++)
                {
                    var optionDisplay = string.Format(CultureInfo.CurrentCulture, "{0}. {1}", i + 1,
      optionsGroup.options[i]);
                    Console.WriteLine(optionDisplay);
                }
                // Check to see if the number of expected options
                // is what we're expecting to see
                if (numberOfExpectedOptions != -1 &&
                    optionsGroup.options.Count != numberOfExpectedOptions)
                {
                    // TODO: Output diagnostic info here
                    Error(string.Format(CultureInfo.CurrentCulture, "[ERROR: Expected {0} options, but
       received {1}]", numberOfExpectedOptions, optionsGroup.options.Count));
                }
                // If we were told to automatically select an option, do so
                if (autoSelectOptionNumber != -1)
                {
                    Note(string.Format(CultureInfo.CurrentCulture, "[Received {0} options, choosing
       option {1}]", optionsGroup.options.Count, autoSelectOptionNumber));
                    optionChooser(autoSelectOptionNumber);
                    autoSelectOptionNumber = -1;
                    return;
                }
                // Reset the expected options counter
                numberOfExpectedOptions = -1;
                if (autoSelectFirstOption == true)
                {
                    Note("[automatically choosing option 1]");
                    optionChooser(0);
                    return;
                }
                do
                {
                    Console.Write("? ");
                    try
                    {
                        var selectedKey = Console.ReadKey().KeyChar.ToString(CultureInfo.InvariantCulture);
                        int selection;
                        if (int.TryParse(selectedKey, out selection) == true)
                        {
                            Console.WriteLine();
                            // we present the list as 1,2,3, but the API expects
                            // answers as 0,1,2
                            selection -= 1;
                            if (selection > optionsGroup.options.Count)
                            {
                                Console.WriteLine("Invalid option.");
                            }
                            else
                            {
                                optionChooser(selection);
                                break;
                            }
                        }
                    }
                    catch (FormatException) { }
                } while (true);
            }
virtual void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.SetNumber (string variableName, float number) [virtual]
Implements Yarn.VariableStorage.
Definition at line 660 of file Main.cs.
            {
                variableStore.SetValue(variableName, new Value(number));
            }
virtual void Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.SetValue (string variableName, Value value) [virtual]
Implements Yarn.VariableStorage.
Definition at line 670 of file Main.cs.
            {
                variableStore.SetValue(variableName, value);
            }
Member Data Documentation
bool Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.autoSelectFirstOption = false
Definition at line 523 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunOptions().
int Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.autoSelectOptionNumber = -1
Definition at line 517 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunOptions().
string Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.expectedNextCommand = null
Definition at line 521 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunCommand().
string Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.expectedNextLine = null
Definition at line 519 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunLine().
int Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.numberOfExpectedOptions = -1
Definition at line 513 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunOptions().
Yarn.MemoryVariableStore Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.variableStore [private]
Definition at line 509 of file Main.cs.
bool Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.waitForLines = false [private]
Definition at line 507 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.ConsoleRunnerImplementation(), and Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunLine().
The documentation for this class was generated from the following file:
YarnSpinnerConsole/Main.cs