ExampleVariableStorage Class Reference
An extremely simple implementation of DialogueUnityVariableStorage, which just stores everything in a Dictionary.
Classes
class DefaultVariable
A default value to apply when the object wakes up, or when ResetToDefaults is called. More...
Public Member Functions
override void ResetToDefaults ()
Erase all variables and reset to default values.
override void SetValue (string variableName, Yarn.Value value)
Set a variable's value.
override Yarn.Value GetValue (string variableName)
Get a variable's value.
override void Clear ()
Erase all variables.
virtual void SetNumber (string variableName, float number)
Not implemented here.
virtual float GetNumber (string variableName)
Not implemented here.
Public Attributes
DefaultVariable[] defaultVariables
Our list of default variables, for debugging.
UnityEngine.UI.Text debugTextView
A UI.Text that can show the current list of all variables. Optional.
Private Member Functions
void Awake ()
Reset to our default values when the game starts.
void Update ()
If we have a debug view, show the list of all variables in it.
Private Attributes
Dictionary< string, Yarn.Value > variables = new Dictionary<string, Yarn.Value> ()
Where we actually keeping our variables.
Detailed Description
An extremely simple implementation of DialogueUnityVariableStorage, which just stores everything in a Dictionary.
Definition at line 34 of file ExampleVariableStorage.cs.
Class Documentation
class ExampleVariableStorage::DefaultVariable
A default value to apply when the object wakes up, or when ResetToDefaults is called.
Definition at line 43 of file ExampleVariableStorage.cs.
Class Members
string
name
Name of the variable.
Value
type
Type of the variable.
string
value
Value of the variable.
Member Function Documentation
void ExampleVariableStorage.Awake () [private]
Reset to our default values when the game starts.
Definition at line 61 of file ExampleVariableStorage.cs.
References ResetToDefaults().
    {
        ResetToDefaults ();
    }
override void ExampleVariableStorage.Clear () [virtual]
Erase all variables.
Reimplemented from Yarn.Unity.VariableStorageBehaviour.
Definition at line 135 of file ExampleVariableStorage.cs.
Referenced by ResetToDefaults().
    {
        variables.Clear ();
    }
virtual float Yarn.Unity.VariableStorageBehaviour.GetNumber (string variableName) [virtual], [inherited]
Not implemented here.
Implements Yarn.VariableStorage.
Definition at line 493 of file DialogueRunner.cs.
        {
            throw new System.NotImplementedException ();
        }
override Yarn.Value ExampleVariableStorage.GetValue (string variableName) [virtual]
Get a variable's value.
Reimplemented from Yarn.Unity.VariableStorageBehaviour.
Definition at line 125 of file ExampleVariableStorage.cs.
References variables.
    {
        // If we don't have a variable with this name, return the null value
        if (variables.ContainsKey(variableName) == false)
            return Yarn.Value.NULL;
        
        return variables [variableName];
    }
override void ExampleVariableStorage.ResetToDefaults () [virtual]
Erase all variables and reset to default values.
Implements Yarn.Unity.VariableStorageBehaviour.
Definition at line 67 of file ExampleVariableStorage.cs.
References Clear(), defaultVariables, and SetValue().
Referenced by Awake().
    {
        Clear ();
        // For each default variable that's been defined, parse the string
        // that the user typed in in Unity and store the variable
        foreach (var variable in defaultVariables) {
            
            object value;
            switch (variable.type) {
            case Yarn.Value.Type.Number:
                float f = 0.0f;
                float.TryParse(variable.value, out f);
                value = f;
                break;
            case Yarn.Value.Type.String:
                value = variable.value;
                break;
            case Yarn.Value.Type.Bool:
                bool b = false;
                bool.TryParse(variable.value, out b);
                value = b;
                break;
            case Yarn.Value.Type.Variable:
                // We don't support assigning default variables from other variables
                // yet
                Debug.LogErrorFormat("Can't set variable {0} to {1}: You can't " +
                    "set a default variable to be another variable, because it " +
                    "may not have been initialised yet.", variable.name, variable.value);
                continue;
            case Yarn.Value.Type.Null:
                value = null;
                break;
            default:
                throw new System.ArgumentOutOfRangeException ();
            }
            var v = new Yarn.Value(value);
            SetValue ("$" + variable.name, v);
        }
    }
virtual void Yarn.Unity.VariableStorageBehaviour.SetNumber (string variableName, float number) [virtual], [inherited]
Not implemented here.
Implements Yarn.VariableStorage.
Definition at line 487 of file DialogueRunner.cs.
        {
            throw new System.NotImplementedException ();
        }
override void ExampleVariableStorage.SetValue (string variableName, Yarn.Value value) [virtual]
Set a variable's value.
Reimplemented from Yarn.Unity.VariableStorageBehaviour.
Definition at line 118 of file ExampleVariableStorage.cs.
References variables.
Referenced by ResetToDefaults().
    {
        // Copy this value into our list
        variables[variableName] = new Yarn.Value(value);
    }
void ExampleVariableStorage.Update () [private]
If we have a debug view, show the list of all variables in it.
Definition at line 141 of file ExampleVariableStorage.cs.
References debugTextView, and variables.
    {
        if (debugTextView != null) {
            var stringBuilder = new System.Text.StringBuilder ();
            foreach (KeyValuePair<string,Yarn.Value> item in variables) {
                stringBuilder.AppendLine (string.Format ("{0} = {1}",
                                                         item.Key,
                                                         item.Value));
            }
            debugTextView.text = stringBuilder.ToString ();
        }
    }
Member Data Documentation
UnityEngine.UI.Text ExampleVariableStorage.debugTextView
A UI.Text that can show the current list of all variables. Optional.
Definition at line 58 of file ExampleVariableStorage.cs.
Referenced by Update().
DefaultVariable [] ExampleVariableStorage.defaultVariables
Our list of default variables, for debugging.
Definition at line 54 of file ExampleVariableStorage.cs.
Referenced by ResetToDefaults().
Dictionary<string, Yarn.Value> ExampleVariableStorage.variables = new Dictionary<string, Yarn.Value> () [private]
Where we actually keeping our variables.
Definition at line 38 of file ExampleVariableStorage.cs.
Referenced by GetValue(), SetValue(), and Update().
The documentation for this class was generated from the following file:
Unity/Assets/YarnSpinner/Examples/DemoScripts/ExampleVariableStorage.cs