Yarn.BaseVariableStorage Class Reference
Public Member Functions
virtual void SetValue (string variableName, string stringValue)
virtual void SetValue (string variableName, float floatValue)
virtual void SetValue (string variableName, bool boolValue)
abstract void SetValue (string variableName, Value value)
abstract Value GetValue (string variableName)
abstract void Clear ()
Detailed Description
Definition at line 77 of file Dialogue.cs.
Member Function Documentation
abstract void Yarn.BaseVariableStorage.Clear () [pure virtual]
Implements Yarn.VariableStorage.
Implemented in Yarn.MemoryVariableStore.
abstract Value Yarn.BaseVariableStorage.GetValue (string variableName) [pure virtual]
Implements Yarn.VariableStorage.
Implemented in Yarn.MemoryVariableStore.
virtual void Yarn.BaseVariableStorage.SetValue (string variableName, string stringValue) [virtual]
Implements Yarn.VariableStorage.
Reimplemented in Yarn.MemoryVariableStore.
Definition at line 78 of file Dialogue.cs.
Referenced by Yarn.BaseVariableStorage.SetValue().
        {
            Value val = new Yarn.Value(stringValue);
            SetValue(variableName, val);
        }
virtual void Yarn.BaseVariableStorage.SetValue (string variableName, float floatValue) [virtual]
Implements Yarn.VariableStorage.
Reimplemented in Yarn.MemoryVariableStore.
Definition at line 83 of file Dialogue.cs.
References Yarn.BaseVariableStorage.SetValue().
        {
            Value val = new Yarn.Value(floatValue);
            SetValue(variableName, val);
        }
virtual void Yarn.BaseVariableStorage.SetValue (string variableName, bool boolValue) [virtual]
Implements Yarn.VariableStorage.
Reimplemented in Yarn.MemoryVariableStore.
Definition at line 88 of file Dialogue.cs.
References Yarn.BaseVariableStorage.SetValue().
        {
            Value val = new Yarn.Value(boolValue);
            SetValue(variableName, val);
        }
abstract void Yarn.BaseVariableStorage.SetValue (string variableName, Value value) [pure virtual]
Implements Yarn.VariableStorage.
Implemented in Yarn.MemoryVariableStore.
The documentation for this class was generated from the following file:
YarnSpinner/Dialogue.cs