Yarn.Parser.CustomCommand Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Types
enum Type { Type.Expression,
Type.ClientCommand
 }
Package Functions
CustomCommand (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Static Package Functions
static bool CanParse (Parser p)
Package Attributes
Type type
ParseNode parent
int lineNumber
string[] tags = {}
Properties
Expression expression [get, set]
string clientCommand [get, set]
Detailed Description
Definition at line 266 of file Parser.cs.
Member Enumeration Documentation
enum Yarn.Parser.CustomCommand.Type [package]
Enumerator
Expression
ClientCommand
Definition at line 268 of file Parser.cs.
                               {
                Expression,
                ClientCommand
            }
Constructor & Destructor Documentation
Yarn.Parser.CustomCommand.CustomCommand (ParseNode parent, Parser p) [package]
Definition at line 284 of file Parser.cs.
References Yarn.Parser.CustomCommand.expression, Yarn.Parser.library, Yarn.Parser.NextSymbolIs(), Yarn.Parser.Parser(), and Yarn.Parser.CustomCommand.type.
                                                               : base(parent, p) {
                p.ExpectSymbol(TokenType.BeginCommand);
                // Custom commands can have ANY token in them. Read them all until we hit the
                // end command token.
                var commandTokens = new List<Token>();
                do {
                    commandTokens.Add(p.ExpectSymbol());
                } while (p.NextSymbolIs(TokenType.EndCommand) == false);
                p.ExpectSymbol(TokenType.EndCommand);
                // If the first token is an identifier and the second is
                // a left paren, it may be a function call expression;
                // evaluate it as such
                if (commandTokens.Count > 1 &&
                    commandTokens[0].type == TokenType.Identifier &&
                    commandTokens[1].type == TokenType.LeftParen) {
                    var parser = new Parser(commandTokens, p.library);
                    var expression = Expression.Parse(this, parser);
                    type = Type.Expression;
                    this.expression = expression;
                } else {
                    // Otherwise, evaluate it as a command
                    type = Type.ClientCommand;
                    this.clientCommand = commandTokens[0].value;
                }
            }
Member Function Documentation
static bool Yarn.Parser.CustomCommand.CanParse (Parser p) [static], [package]
Definition at line 278 of file Parser.cs.
References Yarn.Parser.NextSymbolsAre().
Referenced by Yarn.Parser.Statement.Statement().
            {
                return p.NextSymbolsAre (TokenType.BeginCommand, TokenType.Text) ||
                    p.NextSymbolsAre (TokenType.BeginCommand, TokenType.Identifier);
            }
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.CustomCommand.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 315 of file Parser.cs.
References Yarn.Parser.CustomCommand.clientCommand, Yarn.Parser.Tab(), and Yarn.Parser.CustomCommand.type.
            {
                switch (type) {
                case Type.Expression:
                    return Tab (indentLevel, "Expression: ") + expression.PrintTree (indentLevel + 1);
                case Type.ClientCommand:
                    return Tab (indentLevel, "Command: " + clientCommand);
                }
                return "";
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Type Yarn.Parser.CustomCommand.type [package]
Definition at line 273 of file Parser.cs.
Referenced by Yarn.Parser.CustomCommand.CustomCommand(), and Yarn.Parser.CustomCommand.PrintTree().
Property Documentation
string Yarn.Parser.CustomCommand.clientCommand [get], [set], [package]
Definition at line 276 of file Parser.cs.
Referenced by Yarn.Parser.CustomCommand.PrintTree().
Expression Yarn.Parser.CustomCommand.expression [get], [set], [package]
Definition at line 275 of file Parser.cs.
Referenced by Yarn.Parser.CustomCommand.CustomCommand().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs