Yarn.Parser.OptionStatement Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
OptionStatement (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Static Package Functions
static bool CanParse (Parser p)
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
string destination [get, set]
string label [get, set]
Detailed Description
Definition at line 480 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.OptionStatement.OptionStatement (ParseNode parent, Parser p) [package]
Definition at line 489 of file Parser.cs.
References Yarn.Parser.OptionStatement.destination, Yarn.Parser.OptionStatement.label, Yarn.Parser.NextSymbolIs(), and Yarn.String.
                                                                 : base(parent, p) {
                // The meaning of the string(s) we have changes
                // depending on whether we have one or two, so
                // keep them both and decide their meaning once
                // we know more
                string firstString;
                string secondString;
                // Parse "[[LABEL"
                p.ExpectSymbol(TokenType.OptionStart);
                firstString = p.ExpectSymbol(TokenType.Text).value as String;
                // If there's a | in there, get the string that comes after it
                if (p.NextSymbolIs(TokenType.OptionDelimit)) {
                    p.ExpectSymbol(TokenType.OptionDelimit);
                    secondString = p.ExpectSymbol(TokenType.Text, TokenType.Identifier).value as
      String;
                    // Two strings mean that the first is the label, and the second
                    // is the name of the node that we should head to if this option
                    // is selected
                    label = firstString;
                    destination = secondString;
                } else {
                    // One string means we don't have a label
                    label = null;
                    destination = firstString;
                }
                // Parse the closing ]]
                p.ExpectSymbol(TokenType.OptionEnd);
            }
Member Function Documentation
static bool Yarn.Parser.OptionStatement.CanParse (Parser p) [static], [package]
Definition at line 481 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
            {
                return p.NextSymbolIs (TokenType.OptionStart);
            }
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.OptionStatement.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 524 of file Parser.cs.
References Yarn.Parser.OptionStatement.destination, Yarn.Parser.OptionStatement.label, and Yarn.Parser.Tab().
            {
                if (label != null) {
                    return Tab (indentLevel, string.Format (CultureInfo.CurrentCulture, "Option: \"{0}\"
       -> {1}", label, destination));
                } else {
                    return Tab (indentLevel, string.Format (CultureInfo.CurrentCulture, "Option: -> {0}"
      , destination));
                }
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Property Documentation
string Yarn.Parser.OptionStatement.destination [get], [set], [package]
Definition at line 486 of file Parser.cs.
Referenced by Yarn.Parser.OptionStatement.OptionStatement(), and Yarn.Parser.OptionStatement.PrintTree().
string Yarn.Parser.OptionStatement.label [get], [set], [package]
Definition at line 487 of file Parser.cs.
Referenced by Yarn.Parser.OptionStatement.OptionStatement(), and Yarn.Parser.OptionStatement.PrintTree().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs