Yarn.Dialogue.StandardLibrary Class Reference
The standard, built-in library of functions and operators.
Public Member Functions
StandardLibrary ()
FunctionInfo GetFunction (string name)
void ImportLibrary (Library otherLibrary)
void RegisterFunction (FunctionInfo function)
void RegisterFunction (string name, int parameterCount, ReturningFunction implementation)
void RegisterFunction (string name, int parameterCount, Function implementation)
bool FunctionExists (string name)
void DeregisterFunction (string name)
Detailed Description
The standard, built-in library of functions and operators.
Definition at line 598 of file Dialogue.cs.
Constructor & Destructor Documentation
Yarn.Dialogue.StandardLibrary.StandardLibrary ()
Definition at line 600 of file Dialogue.cs.
                                     {
                #region Operators
                this.RegisterFunction(TokenType.Add.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0] + parameters[1];
                });
                this.RegisterFunction(TokenType.Minus.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0] - parameters[1];
                });
                this.RegisterFunction(TokenType.UnaryMinus.ToString(), 1, delegate(Value[] parameters) {
                    return -parameters[0];
                });
                this.RegisterFunction(TokenType.Divide.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0] / parameters[1];
                });
                this.RegisterFunction(TokenType.Multiply.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0] * parameters[1];
                });
                this.RegisterFunction(TokenType.Modulo.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0] % parameters[1];
                });
                this.RegisterFunction(TokenType.EqualTo.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0].Equals(parameters[1]);
                });
                this.RegisterFunction(TokenType.NotEqualTo.ToString(), 2, delegate(Value[] parameters) {
                    // Return the logical negative of the == operator's result
                    var equalTo = this.GetFunction(TokenType.EqualTo.ToString());
                    return !equalTo.Invoke(parameters).AsBool;
                });
                this.RegisterFunction(TokenType.GreaterThan.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0] > parameters[1];
                });
                this.RegisterFunction(TokenType.GreaterThanOrEqualTo.ToString(), 2, delegate(Value[]
      parameters) {
                    return parameters[0] >= parameters[1];
                });
                this.RegisterFunction(TokenType.LessThan.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0] < parameters[1];
                });
                this.RegisterFunction(TokenType.LessThanOrEqualTo.ToString(), 2, delegate(Value[]
      parameters) {
                    return parameters[0] <= parameters[1];
                });
                this.RegisterFunction(TokenType.And.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0].AsBool && parameters[1].AsBool;
                });
                this.RegisterFunction(TokenType.Or.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0].AsBool || parameters[1].AsBool;
                });
                this.RegisterFunction(TokenType.Xor.ToString(), 2, delegate(Value[] parameters) {
                    return parameters[0].AsBool ^ parameters[1].AsBool;
                });
                this.RegisterFunction(TokenType.Not.ToString(), 1, delegate(Value[] parameters) {
                    return !parameters[0].AsBool;
                });
                #endregion Operators
            }
Member Function Documentation
void Yarn.Library.DeregisterFunction (string name) [inherited]
Definition at line 129 of file Library.cs.
References Yarn.Library.functions.
                                                    {
            if (functions.ContainsKey(name))
                functions.Remove (name);
        }
bool Yarn.Library.FunctionExists (string name) [inherited]
Definition at line 125 of file Library.cs.
                                                {
            return functions.ContainsKey (name);
        }
FunctionInfo Yarn.Library.GetFunction (string name) [inherited]
Definition at line 94 of file Library.cs.
References Yarn.Library.functions.
Referenced by Yarn.VirtualMachine.RunInstruction().
                                                     {
            try {
                return functions [name];
            } catch (KeyNotFoundException) {
                throw new InvalidOperationException (name + " is not a valid function");
            }
        }
void Yarn.Library.ImportLibrary (Library otherLibrary) [inherited]
Definition at line 105 of file Library.cs.
References Yarn.Library.functions.
                                                        {
            foreach (var entry in otherLibrary.functions) {
                functions [entry.Key] = entry.Value;
            }
        }
void Yarn.Library.RegisterFunction (FunctionInfo function) [inherited]
Definition at line 111 of file Library.cs.
References Yarn.Library.functions.
Referenced by Yarn.Library.RegisterFunction().
                                                            {
            functions [function.name] = function;
        }
void Yarn.Library.RegisterFunction (string name, int parameterCount, ReturningFunction implementation) [inherited]
Definition at line 115 of file Library.cs.
References Yarn.Library.RegisterFunction().
                                                                                                        {
            var info = new FunctionInfo (name, parameterCount, implementation);
            RegisterFunction (info);
        }
void Yarn.Library.RegisterFunction (string name, int parameterCount, Function implementation) [inherited]
Definition at line 120 of file Library.cs.
References Yarn.Library.RegisterFunction().
                                                                                               {
            var info = new FunctionInfo (name, parameterCount, implementation);
            RegisterFunction (info);
        }
The documentation for this class was generated from the following file:
YarnSpinner/Dialogue.cs