Yarn.Parser.ShortcutOptionGroup Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
ShortcutOptionGroup (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Static Package Functions
static bool CanParse (Parser p)
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
IEnumerable< ShortcutOption > options [get]
Private Attributes
List< ShortcutOption > _options = new List<ShortcutOption>()
Detailed Description
Definition at line 331 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.ShortcutOptionGroup.ShortcutOptionGroup (ParseNode parent, Parser p) [package]
Definition at line 342 of file Parser.cs.
References Yarn.Parser.NextSymbolIs(), and Yarn.ShortcutOption.
                                                                     : base(
      parent, p) {
                // keep parsing options until we can't, but expect at least one (otherwise it's
                // not actually a list of options)
                int shortcutIndex = 1; // give each option a number so it can name itself
                do {
                    _options.Add(new ShortcutOption(shortcutIndex++, this, p));
                } while (p.NextSymbolIs(TokenType.ShortcutOption));
            }
Member Function Documentation
static bool Yarn.Parser.ShortcutOptionGroup.CanParse (Parser p) [static], [package]
Definition at line 332 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
            {
                return p.NextSymbolIs (TokenType.ShortcutOption);
            }
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.ShortcutOptionGroup.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 352 of file Parser.cs.
References Yarn.Parser.ShortcutOptionGroup.options, and Yarn.Parser.Tab().
            {
                var sb = new StringBuilder ();
                sb.Append (Tab (indentLevel, "Shortcut option group {"));
                foreach (var option in options) {
                    sb.Append (option.PrintTree (indentLevel + 1));
                }
                sb.Append (Tab (indentLevel, "}"));
                return sb.ToString ();
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
List<ShortcutOption> Yarn.Parser.ShortcutOptionGroup._options = new List<ShortcutOption>() [private]
Definition at line 340 of file Parser.cs.
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Property Documentation
IEnumerable<ShortcutOption> Yarn.Parser.ShortcutOptionGroup.options [get], [package]
Definition at line 337 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOptionGroup.PrintTree().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs