Yarn.Loader Class Reference
Classes
struct EmissionTuple
struct NodeInfo
Public Member Functions
Loader (Dialogue dialogue)
Program Load (string text, Library library, string fileName, Program includeProgram, bool showTokens, bool showParseTree, string onlyConsiderNode, NodeFormat format, bool experimentalMode=false)
Package Functions
NodeInfo[] GetNodesFromText (string text, NodeFormat format)
Static Package Functions
static NodeFormat GetFormatFromFileName (string fileName)
Properties
Program program [get, set]
Private Member Functions
void PrintTokenList (IEnumerable< Token > tokenList)
void PrintParseTree (Yarn.Parser.ParseNode rootNode)
string preprocessor (string nodeText)
Private Attributes
Dialogue dialogue
Detailed Description
Definition at line 55 of file Loader.cs.
Constructor & Destructor Documentation
Yarn.Loader.Loader (Dialogue dialogue)
Definition at line 83 of file Loader.cs.
References Yarn.Loader.dialogue.
                                         {
            if (dialogue == null)
                throw new ArgumentNullException (nameof(dialogue));
            this.dialogue = dialogue;
        }
Member Function Documentation
static NodeFormat Yarn.Loader.GetFormatFromFileName (string fileName) [static], [package]
Definition at line 392 of file Loader.cs.
Referenced by Yarn.FileFormatConverter.ConvertToJSON(), Yarn.FileFormatConverter.ConvertToYarn(), and Yarn.Loader.Load().
        {
            NodeFormat format;
            if (fileName.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
            {
                format = NodeFormat.JSON;
            }
            else if (fileName.EndsWith(".yarn.txt", StringComparison.OrdinalIgnoreCase))
            {
                format = NodeFormat.Text;
            }
            else if (fileName.EndsWith(".node", StringComparison.OrdinalIgnoreCase))
            {
                format = NodeFormat.SingleNodeText;
            }
            else {
                throw new FormatException(string.Format(CultureInfo.CurrentCulture, "Unknown file format
       for file '{0}'", fileName));
            }
            return format;
        }
NodeInfo [] Yarn.Loader.GetNodesFromText (string text, NodeFormat format) [package]
Definition at line 416 of file Loader.cs.
Referenced by Yarn.Loader.Load().
        {
            // All the nodes we found in this file
            var nodes = new List<NodeInfo> ();
            switch (format)
            {
                case NodeFormat.SingleNodeText:
                    // If it starts with a comment, treat it as a single-node file
                    var nodeInfo = new NodeInfo();
                    nodeInfo.title = "Start";
                    nodeInfo.body = text;
                    nodes.Add(nodeInfo);
                    break;
                case NodeFormat.JSON:
                    // Parse it as JSON
                    try
                    {
                        nodes = JsonConvert.DeserializeObject<List<NodeInfo>>(text);
                    }
                    catch (JsonReaderException e)
                    {
                        dialogue.LogErrorMessage("Error parsing Yarn input: " + e.Message);
                    }
                    break;
                case NodeFormat.Text:
                    // check for the existence of at least one "---"+newline sentinel, which divides
                    // the headers from the body
                    // we use a regex to match either \r\n or \n line endings
                    if (System.Text.RegularExpressions.Regex.IsMatch(text, "---.?\n") == false) {
                        dialogue.LogErrorMessage("Error parsing input: text appears corrupt (no header
       sentinel)");
                        break;
                    }
                    var headerRegex = new System.Text.RegularExpressions.Regex("(?<field>.*): *(?<value>.*)
      ");
                    var nodeProperties = typeof(NodeInfo).GetProperties();
                    int lineNumber = 0;
                    using (var reader = new System.IO.StringReader(text))
                    {
                        string line;
                        while ((line = reader.ReadLine()) != null)
                        {
                            // Create a new node
                            NodeInfo node = new NodeInfo();
                            // Read header lines
                            do
                            {
                                lineNumber++;
                                // skip empty lines
                                if (line.Length == 0)
                                {
                                    continue;
                                }
                                // Attempt to parse the header
                                var headerMatches = headerRegex.Match(line);
                                if (headerMatches == null)
                                {
                                    dialogue.LogErrorMessage(string.Format(CultureInfo.CurrentCulture, "
      Line {0}: Can't parse header '{1}'", lineNumber, line));
                                    continue;
                                }
                                var field = headerMatches.Groups["field"].Value;
                                var value = headerMatches.Groups["value"].Value;
                                // Attempt to set the appropriate property using this field
                                foreach (var property in nodeProperties)
                                {
                                    if (property.Name != field) {
                                        continue;
                                    }
                                    // skip properties that can't be written to
                                    if (property.CanWrite == false)
                                    {
                                        continue;
                                    }
                                    try
                                    {
                                        var propertyType = property.PropertyType;
                                        object convertedValue;
                                        if (propertyType.IsAssignableFrom(typeof(string)))
                                        {
                                            convertedValue = value;
                                        }
                                        else if (propertyType.IsAssignableFrom(typeof(int)))
                                        {
                                            convertedValue = int.Parse(value, CultureInfo.InvariantCulture)
      ;
                                        }
                                        else if (propertyType.IsAssignableFrom(typeof(NodeInfo.Position)))
                                        {
                                            var components = value.Split(',');
                                            // we expect 2 components: x and y
                                            if (components.Length != 2)
                                            {
                                                throw new FormatException();
                                            }
                                            var position = new NodeInfo.Position();
                                            position.x = int.Parse(components[0],
      CultureInfo.InvariantCulture);
                                            position.y = int.Parse(components[1],
      CultureInfo.InvariantCulture);
                                            convertedValue = position;
                                        }
                                        else {
                                            throw new NotSupportedException();
                                        }
                                        // we need to box this because structs are value types,
                                        // so calling SetValue using 'node' would just modify a copy of
       'node'
                                        object box = node;
                                        property.SetValue(box, convertedValue, null);
                                        node = (NodeInfo)box;
                                        break;
                                    }
                                    catch (FormatException)
                                    {
                                        dialogue.LogErrorMessage(string.Format(CultureInfo.CurrentCulture,
      "{0}: Error setting '{1}': invalid value '{2}'", lineNumber, field, value));
                                    }
                                    catch (NotSupportedException)
                                    {
                                        dialogue.LogErrorMessage(string.Format(CultureInfo.CurrentCulture,
      "{0}: Error setting '{1}': This property cannot be set", lineNumber, field));
                                    }
                                }
                            } while ((line = reader.ReadLine()) != "---");
                            lineNumber++;
                            // We're past the header; read the body
                            var lines = new List<string>();
                            // Read header lines until we hit the end of node sentinel or the end of the
       file
                            while ((line = reader.ReadLine()) != "===" && line != null)
                            {
                                lineNumber++;
                                lines.Add(line);
                            }
                            // We're done reading the lines! Zip 'em up into a string and
                            // store it in the body
                            node.body = string.Join("\n", lines.ToArray());
                            // And add this node to the list
                            nodes.Add(node);
                            // And now we're ready to move on to the next line!
                        }
                    }
                    break;
                default:
                    throw new InvalidOperationException("Unknown format " + format.ToString());
            }
            // hooray we're done
            return nodes.ToArray();
        }
Program Yarn.Loader.Load (string text, Library library, string fileName, Program includeProgram, bool showTokens, bool showParseTree, string onlyConsiderNode, NodeFormat format, bool experimentalMode = false)
Definition at line 218 of file Loader.cs.
References Yarn.Loader.GetFormatFromFileName(), Yarn.Loader.GetNodesFromText(), Yarn.ErrorListener.Instance, Yarn.Loader.preprocessor(), Yarn.Loader.PrintParseTree(), Yarn.Loader.PrintTokenList(), Yarn.Loader.NodeInfo.tags, and Yarn.Loader.NodeInfo.title.
        {
            if (format == NodeFormat.Unknown)
            {
                format = GetFormatFromFileName(fileName);
            }
            // currently experimental node can only be used on yarn.txt yarn files and single nodes
            if (experimentalMode && (format == NodeFormat.Text || format ==
      NodeFormat.SingleNodeText))
            {
                // this isn't the greatest...
                if (format == NodeFormat.SingleNodeText)
                {
                    // it is just the body
                    // need to add a dummy header and body delimiters
                    StringBuilder builder = new StringBuilder();
                    builder.Append("title:Start\n");
                    builder.Append("---\n");
                    builder.Append(text);
                    builder.Append("\n===\n");
                    text = builder.ToString();
                }
                string inputString = preprocessor(text);
                ICharStream input = CharStreams.fromstring(inputString);
                YarnSpinnerLexer lexer = new YarnSpinnerLexer(input);
                CommonTokenStream tokens = new CommonTokenStream(lexer);
                YarnSpinnerParser parser = new YarnSpinnerParser(tokens);
                // turning off the normal error listener and using ours
                parser.RemoveErrorListeners();
                parser.AddErrorListener(ErrorListener.Instance);
                IParseTree tree = parser.dialogue();
                AntlrCompiler antlrcompiler = new AntlrCompiler(library);
                antlrcompiler.Compile(tree);
                // merging in the other program if requested
                if (includeProgram != null)
                {
                    antlrcompiler.program.Include(includeProgram);
                }
                return antlrcompiler.program;
            }
            else
            {
                // The final parsed nodes that were in the file we were given
                Dictionary<string, Yarn.Parser.Node> nodes = new Dictionary<string,
      Parser.Node>();
                // Load the raw data and get the array of node title-text pairs
                var nodeInfos = GetNodesFromText(text, format);
                int nodesLoaded = 0;
                foreach (NodeInfo nodeInfo in nodeInfos)
                {
                    if (onlyConsiderNode != null && nodeInfo.title != onlyConsiderNode)
                        continue;
                    // Attempt to parse every node; log if we encounter any errors
#if CATCH_EXCEPTIONS
                    try
                    {
#endif
                        if (nodes.ContainsKey(nodeInfo.title))
                        {
                            throw new InvalidOperationException("Attempted to load a node called " +
                                nodeInfo.title + ", but a node with that name has already been loaded!");
                        }
                        var lexer = new Lexer();
                        var tokens = lexer.Tokenise(nodeInfo.title, nodeInfo.body);
                        if (showTokens)
                            PrintTokenList(tokens);
                        var node = new Parser(tokens, library).Parse();
                        // If this node is tagged "rawText", then preserve its source
                        if (string.IsNullOrEmpty(nodeInfo.tags) == false &&
                            nodeInfo.tags.Contains("rawText"))
                        {
                            node.source = nodeInfo.body;
                        }
                        node.name = nodeInfo.title;
                        node.nodeTags = nodeInfo.tagsList;
                        if (showParseTree)
                            PrintParseTree(node);
                        nodes[nodeInfo.title] = node;
                        nodesLoaded++;
#if CATCH_EXCEPTIONS
                    }
                    catch (Yarn.TokeniserException t)
                    {
                        // Add file information
                        var message = string.Format(CultureInfo.CurrentCulture, "In file {0}: Error reading
       node {1}: {2}", fileName, nodeInfo.title, t.Message);
                        throw new Yarn.TokeniserException(message);
                    }
                    catch (Yarn.ParseException p)
                    {
                        var message = string.Format(CultureInfo.CurrentCulture, "In file {0}: Error parsing
       node {1}: {2}", fileName, nodeInfo.title, p.Message);
                        throw new Yarn.ParseException(message);
                    }
                    catch (InvalidOperationException e)
                    {
                        var message = string.Format(CultureInfo.CurrentCulture, "In file {0}: Error reading
       node {1}: {2}", fileName, nodeInfo.title, e.Message);
                        throw new InvalidOperationException(message);
                    }
#endif
                }
                var compiler = new Yarn.Compiler(fileName);
                foreach (var node in nodes)
                {
                    compiler.CompileNode(node.Value);
                }
                if (includeProgram != null)
                {
                    compiler.program.Include(includeProgram);
                }
                return compiler.program;
            }
        }
string Yarn.Loader.preprocessor (string nodeText) [private]
Definition at line 106 of file Loader.cs.
References preprocessor.DEDENT, preprocessor.INDENT, preprocessor.indents, preprocessor.OPTION, preprocessor.shouldTrackNextIndentation, and preprocessor.topLevel.
Referenced by Yarn.Loader.Load().
        {
            string processed = null;
            using (StringReader reader = new StringReader(nodeText))
            {
                // a list to hold outputLines once they have been cleaned up
                List<string> outputLines = new List<string>();
                // a stack to keep track of how far indented we are
                // made up of ints and bools
                // ints track the depth, bool tracks if we emitted an indent token
                // starts with 0 and false so we can never fall off the end of the stack
                Stack<EmissionTuple> indents = new Stack<EmissionTuple>();
                indents.Push(new EmissionTuple(0, false));
                // a bool to determine if we are in a mode where we need to track indents
                bool shouldTrackNextIndentation = false;
                char INDENT = '\a';
                char DEDENT = '\v';
                //string INDENT = "{";
                //string DEDENT = "}";
                string OPTION = "->";
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    // replacing \t with 4 spaces
                    string tweakedLine = line.Replace("\t", " ");
                    // stripping of any trailing newlines, will add them back in later
                    tweakedLine = tweakedLine.TrimEnd('\r', '\n');
                    // getting the number of indents on this line
                    int lineIndent = tweakedLine.TakeWhile(Char.IsWhiteSpace).Count();
                    // working out if it is an option (ie does it start with ->)
                    bool isOption = tweakedLine.TrimStart(' ').StartsWith(OPTION, StringComparison.
      InvariantCulture);
                    // are we in a state where we need to track indents?
                    var previous = indents.Peek();
                    if (shouldTrackNextIndentation && (lineIndent > previous.depth))
                    {
                        indents.Push(new EmissionTuple(lineIndent, true));
                        // adding an indent to the stream
                        // tries to add it to the end of the previous line where possible
                        if (outputLines.Count == 0)
                        {
                            tweakedLine = INDENT + tweakedLine;
                        }
                        else
                        {
                            outputLines[outputLines.Count - 1] = outputLines[outputLines.Count - 1] +
      INDENT;
                        }
                        shouldTrackNextIndentation = false;
                    }
                    // have we finished with the current block of statements
                    else if (lineIndent < previous.depth)
                    {
                        while (lineIndent < indents.Peek().depth)
                        {
                            var topLevel = indents.Pop();
                            if (topLevel.emitted)
                            {
                                // adding dedents
                                if (outputLines.Count == 0)
                                {
                                    tweakedLine = DEDENT + tweakedLine;
                                }
                                else
                                {
                                    outputLines[outputLines.Count - 1] = outputLines[outputLines.Count - 1]
       + DEDENT;
                                }
                            }
                        }
                    }
                    else
                    {
                        shouldTrackNextIndentation = false;
                    }
                    // do we need to track the indents for the next statement?
                    if (isOption)
                    {
                        shouldTrackNextIndentation = true;
                        if (indents.Peek().depth < lineIndent)
                        {
                            indents.Push(new EmissionTuple(lineIndent, false));
                        }
                    }
                    outputLines.Add(tweakedLine);
                }
                // mash it all back together now
                StringBuilder builder = new StringBuilder();
                foreach (string outLine in outputLines)
                {
                    builder.Append(outLine);
                    builder.Append("\n");
                }
                processed = builder.ToString();
            }
            return processed;
        }
void Yarn.Loader.PrintParseTree (Yarn.Parser.ParseNode rootNode) [private]
Definition at line 76 of file Loader.cs.
Referenced by Yarn.Loader.Load().
                                                            {
            dialogue.LogDebugMessage("Parse Tree:");
            dialogue.LogDebugMessage(rootNode.PrintTree(0));
        }
void Yarn.Loader.PrintTokenList (IEnumerable< Token > tokenList) [private]
Definition at line 62 of file Loader.cs.
Referenced by Yarn.Loader.Load().
                                                          {
            // Sum up the result
            var sb = new System.Text.StringBuilder();
            foreach (var t in tokenList) {
                sb.AppendLine (string.Format(CultureInfo.CurrentCulture, "{0} ({1} line {2})", t.ToString (
      ), t.context, t.lineNumber));
            }
            // Let's see what we got
            dialogue.LogDebugMessage("Tokens:");
            dialogue.LogDebugMessage(sb.ToString());
        }
Member Data Documentation
Dialogue Yarn.Loader.dialogue [private]
Definition at line 57 of file Loader.cs.
Referenced by Yarn.Loader.Loader().
Property Documentation
Program Yarn.Loader.program [get], [set]
Definition at line 59 of file Loader.cs.
The documentation for this class was generated from the following file:
YarnSpinner/Loader.cs