Yarn.Parser.IfStatement Class Reference
Classes
struct Clause
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
IfStatement (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Static Package Functions
static bool CanParse (Parser p)
Package Attributes
List< Clause > clauses = new List<Clause>()
ParseNode parent
int lineNumber
string[] tags = {}
Detailed Description
Definition at line 537 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.IfStatement.IfStatement (ParseNode parent, Parser p) [package]
Definition at line 565 of file Parser.cs.
References Yarn.Parser.NextSymbolIs(), and Yarn.Parser.NextSymbolsAre().
                                                             : base(parent, p) {
                // All if statements begin with "<<if EXPRESSION>>", so parse that
                Clause primaryClause = new Clause();
                p.ExpectSymbol(TokenType.BeginCommand);
                p.ExpectSymbol(TokenType.If);
                primaryClause.expression = Expression.Parse(this, p);
                p.ExpectSymbol(TokenType.EndCommand);
                // Read the statements for this clause until we hit an <<endif or <<else
                // (which could be an "<<else>>" or an "<<else if"
                var statements = new List<Statement>();
                while (p.NextSymbolsAre(TokenType.BeginCommand,
      TokenType.EndIf) == false &&
                    p.NextSymbolsAre(TokenType.BeginCommand, TokenType.Else) == false &&
                    p.NextSymbolsAre(TokenType.BeginCommand, TokenType.ElseIf) == false)
      {
                    statements.Add(new Statement(this, p));
                    // Ignore any dedents
                    while (p.NextSymbolIs(TokenType.Dedent)) {
                        p.ExpectSymbol(TokenType.Dedent);
                    }
                }
                primaryClause.statements = statements;
                clauses.Add(primaryClause);
                // Handle as many <<elseif clauses as we find
                while (p.NextSymbolsAre(TokenType.BeginCommand,
      TokenType.ElseIf)) {
                    var elseIfClause = new Clause();
                    // Parse the syntax for this clause's condition
                    p.ExpectSymbol(TokenType.BeginCommand);
                    p.ExpectSymbol(TokenType.ElseIf);
                    elseIfClause.expression = Expression.Parse(this, p);
                    p.ExpectSymbol(TokenType.EndCommand);
                    // Read statements until we hit an <<endif, <<else or another <<elseif
                    var clauseStatements = new List<Statement>();
                    while (p.NextSymbolsAre(TokenType.BeginCommand,
      TokenType.EndIf) == false &&
                        p.NextSymbolsAre(TokenType.BeginCommand, TokenType.Else) == false &&
                        p.NextSymbolsAre(TokenType.BeginCommand,
      TokenType.ElseIf) == false) {
                        clauseStatements.Add(new Statement(this, p));
                        // Ignore any dedents
                        while (p.NextSymbolIs(TokenType.Dedent)) {
                            p.ExpectSymbol(TokenType.Dedent);
                        }
                    }
                    elseIfClause.statements = clauseStatements;
                    clauses.Add(elseIfClause);
                }
                // Handle <<else>> if we have it
                if (p.NextSymbolsAre(TokenType.BeginCommand, TokenType.Else,
      TokenType.EndCommand)) {
                    // parse the syntax (no expression this time, just "<<else>>"
                    p.ExpectSymbol(TokenType.BeginCommand);
                    p.ExpectSymbol(TokenType.Else);
                    p.ExpectSymbol(TokenType.EndCommand);
                    // and parse statements until we hit "<<endif"
                    var elseClause = new Clause();
                    var clauseStatements = new List<Statement>();
                    while (p.NextSymbolsAre(TokenType.BeginCommand,
      TokenType.EndIf) == false) {
                        clauseStatements.Add(new Statement(this, p));
                    }
                    elseClause.statements = clauseStatements;
                    this.clauses.Add(elseClause);
                    // Ignore any dedents
                    while (p.NextSymbolIs(TokenType.Dedent)) {
                        p.ExpectSymbol(TokenType.Dedent);
                    }
                }
                // Finish up by reading the <<endif>>
                p.ExpectSymbol(TokenType.BeginCommand);
                p.ExpectSymbol(TokenType.EndIf);
                p.ExpectSymbol(TokenType.EndCommand);
            }
Member Function Documentation
static bool Yarn.Parser.IfStatement.CanParse (Parser p) [static], [package]
Definition at line 538 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
            {
                return p.NextSymbolsAre (TokenType.BeginCommand, TokenType.If);
            }
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.IfStatement.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 652 of file Parser.cs.
References Yarn.Parser.IfStatement.clauses, and Yarn.Parser.Tab().
            {
                var sb = new StringBuilder ();
                var first = true;
                foreach (var clause in clauses) {
                    if (first) {
                        sb.Append (Tab (indentLevel, "If:"));
                        first = false;
                    } else if (clause.expression != null) {
                        sb.Append (Tab (indentLevel, "Else If:"));
                    } else {
                        sb.Append (Tab (indentLevel, "Else:"));
                    }
                    sb.Append (clause.PrintTree (indentLevel + 1));
                }
                return sb.ToString ();
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
List<Clause> Yarn.Parser.IfStatement.clauses = new List<Clause>() [package]
Definition at line 563 of file Parser.cs.
Referenced by Yarn.Parser.IfStatement.PrintTree().
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs