Yarn.Parser.ParseNode Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
ParseNode (ParseNode parent, Parser p)
abstract string PrintTree (int indentLevel)
Node NodeParent ()
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Detailed Description
Definition at line 56 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.ParseNode.ParseNode (ParseNode parent, Parser p) [package]
Definition at line 65 of file Parser.cs.
References Yarn.Parser.ParseNode.lineNumber, Yarn.Parser.ParseNode.parent, and Yarn.Parser.tokens.
                                                           {
                this.parent = parent;
                if (p.tokens.Count > 0)
                    this.lineNumber = p.tokens.Peek().lineNumber;
                else
                    this.lineNumber = -1;
            }
Member Function Documentation
Node Yarn.Parser.ParseNode.NodeParent () [package]
Definition at line 100 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
abstract string Yarn.Parser.ParseNode.PrintTree (int indentLevel) [package], [pure virtual]
Implemented in Yarn.Parser.Operator, Yarn.Parser.AssignmentStatement, Yarn.Parser.Expression, Yarn.Parser.ValueNode, Yarn.Parser.IfStatement, Yarn.Parser.OptionStatement, Yarn.Parser.Block, Yarn.Parser.ShortcutOption, Yarn.Parser.ShortcutOptionGroup, Yarn.Parser.CustomCommand, Yarn.Parser.Statement, and Yarn.Parser.Node.
string Yarn.Parser.ParseNode.TagsToString (int indentLevel)
Definition at line 78 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString ()
Definition at line 94 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
int Yarn.Parser.ParseNode.lineNumber [package]
Definition at line 61 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package]
Definition at line 58 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package]
Definition at line 76 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs