Yarn.Parser Class Reference
Classes
class AssignmentStatement
class Block
class CustomCommand
class Expression
class IfStatement
class Node
class Operator
class OptionStatement
class ParseNode
class ShortcutOption
class ShortcutOptionGroup
class Statement
class ValueNode
Package Functions
Parser (ICollection< Token > tokens, Library library)
Node Parse ()
Private Member Functions
bool NextSymbolIs (params TokenType[] validTypes)
bool NextSymbolsAre (params TokenType[] validTypes)
Token ExpectSymbol (TokenType type)
Token ExpectSymbol ()
Token ExpectSymbol (params TokenType[] validTypes)
Static Private Member Functions
static string Tab (int indentLevel, string input, bool newLine=true)
Private Attributes
Queue< Token > tokens
Library library
Detailed Description
Definition at line 38 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.Parser (ICollection< Token > tokens, Library library) [package]
Definition at line 1265 of file Parser.cs.
References Yarn.Parser.library, and Yarn.Parser.tokens.
Referenced by Yarn.Parser.CustomCommand.CustomCommand().
                                                                    {
            this.tokens = new Queue<Token>(tokens);
            this.library = library;
        }
Member Function Documentation
Token Yarn.Parser.ExpectSymbol (TokenType type) [private]
Definition at line 1302 of file Parser.cs.
                                           {
            var t = this.tokens.Dequeue();
            if (t.type != type) {
                throw ParseException.Make(t, type);
            }
            return t;
        }
Token Yarn.Parser.ExpectSymbol () [private]
Definition at line 1312 of file Parser.cs.
                             {
            var token = this.tokens.Dequeue ();
            if (token.type == TokenType.EndOfInput) {
                throw ParseException.Make (token, "Unexpected end of input");
            }
            return token;
        }
Token Yarn.Parser.ExpectSymbol (params TokenType[] validTypes) [private]
Definition at line 1322 of file Parser.cs.
                                                          {
            var t = this.tokens.Dequeue();
            foreach (var validType in validTypes) {
                if (t.type == validType) {
                    return t;
                }
            }
            throw ParseException.Make(t, validTypes);
        }
bool Yarn.Parser.NextSymbolIs (params TokenType[] validTypes) [private]
Definition at line 1277 of file Parser.cs.
Referenced by Yarn.Parser.Block.Block(), Yarn.Parser.CustomCommand.CustomCommand(), Yarn.Parser.IfStatement.IfStatement(), Yarn.Parser.Node.Node(), Yarn.Parser.OptionStatement.OptionStatement(), Yarn.Parser.Expression.Parse(), Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.ShortcutOptionGroup.ShortcutOptionGroup(), and Yarn.Parser.Statement.Statement().
                                                         {
            var t = this.tokens.Peek().type;
            foreach (var validType in validTypes) {
                if (t == validType) {
                    return true;
                }
            }
            return false;
        }
bool Yarn.Parser.NextSymbolsAre (params TokenType[] validTypes) [private]
Definition at line 1291 of file Parser.cs.
References Yarn.Parser.tokens.
Referenced by Yarn.Parser.CustomCommand.CanParse(), Yarn.Parser.IfStatement.IfStatement(), and Yarn.Parser.ShortcutOption.ShortcutOption().
                                                           {
            var tempQueue = new Queue<Token> (tokens);
            foreach (var type in validTypes) {
                if (tempQueue.Dequeue ().type != type)
                    return false;
            }
            return true;
        }
Node Yarn.Parser.Parse () [package]
Definition at line 1270 of file Parser.cs.
Referenced by Yarn.Parser.ValueNode.UseToken().
                              {
            // Kick off the parsing process by trying to parse a whole node
            return new Node("Start", null, this);
        }
static string Yarn.Parser.Tab (int indentLevel, string input, bool newLine = true) [static], [private]
Definition at line 41 of file Parser.cs.
Referenced by Yarn.Parser.Node.PrintTree(), Yarn.Parser.Statement.PrintTree(), Yarn.Parser.CustomCommand.PrintTree(), Yarn.Parser.ShortcutOptionGroup.PrintTree(), Yarn.Parser.ShortcutOption.PrintTree(), Yarn.Parser.Block.PrintTree(), Yarn.Parser.OptionStatement.PrintTree(), Yarn.Parser.IfStatement.Clause.PrintTree(), Yarn.Parser.IfStatement.PrintTree(), Yarn.Parser.ValueNode.PrintTree(), Yarn.Parser.Expression.PrintTree(), Yarn.Parser.AssignmentStatement.PrintTree(), Yarn.Parser.Operator.PrintTree(), and Yarn.Parser.ParseNode.TagsToString().
                                                                                      {
            var sb = new StringBuilder();
            for (int i = 0; i < indentLevel; i++) {
                sb.Append ("| ");
            }
            sb.Append (input);
            if (newLine)
                sb.Append ("\n");
            return sb.ToString ();
        }
Member Data Documentation
Library Yarn.Parser.library [private]
Definition at line 1260 of file Parser.cs.
Referenced by Yarn.Parser.CustomCommand.CustomCommand(), Yarn.Parser.Expression.Parse(), and Yarn.Parser.Parser().
Queue<Token> Yarn.Parser.tokens [private]
Definition at line 1258 of file Parser.cs.
Referenced by Yarn.Parser.NextSymbolsAre(), Yarn.Parser.Node.Node(), Yarn.Parser.Expression.Parse(), Yarn.Parser.ParseNode.ParseNode(), Yarn.Parser.Parser(), and Yarn.Parser.Statement.Statement().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs