Yarn.Parser.ValueNode Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
ValueNode (ParseNode parent, Token t, Parser p)
ValueNode (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
Value value [get, set]
Private Member Functions
void UseToken (Token t)
Detailed Description
Definition at line 673 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.ValueNode.ValueNode (ParseNode parent, Token t, Parser p) [package]
Definition at line 714 of file Parser.cs.
References Yarn.Parser.ValueNode.UseToken().
                                                                    : base (
      parent, p) {
                UseToken(t);
            }
Yarn.Parser.ValueNode.ValueNode (ParseNode parent, Parser p) [package]
Definition at line 719 of file Parser.cs.
References Yarn.Parser.ValueNode.UseToken().
                                                           : base(parent, p) {
                Token t = p.ExpectSymbol(TokenType.Number, TokenType.Variable, TokenType.String);
                UseToken(t);
            }
Member Function Documentation
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.ValueNode.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 726 of file Parser.cs.
References Yarn.Value.boolValue, Yarn.Value.numberValue, Yarn.Value.stringValue, Yarn.Parser.Tab(), Yarn.Value.type, Yarn.Parser.ValueNode.value, and Yarn.Value.variableName.
            {
                switch (value.type) {
                case Value.Type.Number:
                    return Tab (indentLevel, value.numberValue.ToString(CultureInfo.
      CurrentCulture));
                case Value.Type.String:
                    return Tab(indentLevel, string.Format(CultureInfo.CurrentCulture, "\"{0}\"",
      value.stringValue));
                case Value.Type.Bool:
                    return Tab (indentLevel, value.boolValue.ToString(CultureInfo.
      CurrentCulture));
                case Value.Type.Variable:
                    return Tab (indentLevel, value.variableName);
                case Value.Type.Null:
                    return Tab (indentLevel, "(null)");
                }
                throw new ArgumentException ();
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
void Yarn.Parser.ValueNode.UseToken (Token t) [private]
Definition at line 677 of file Parser.cs.
References Yarn.Value.NULL, Yarn.Parser.Parse(), Yarn.String, Yarn.Token.type, Yarn.Token.value, and Yarn.Parser.ValueNode.value.
Referenced by Yarn.Parser.ValueNode.ValueNode().
                                           {
                // Store the value depending on token's type
                switch (t.type) {
                case TokenType.Number:
                    value = new Value (float.Parse (t.value as string, CultureInfo.
      InvariantCulture));
                    break;
                case TokenType.String:
                    value = new Value (t.value as String);
                    break;
                case TokenType.False:
                    value = new Value (false);
                    break;
                case TokenType.True:
                    value = new Value (true);
                    break;
                case TokenType.Variable:
                    value = new Value ();
                    value.type = Value.Type.Variable;
                    value.variableName = t.value as String;
                    break;
                case TokenType.Null:
                    value = Value.NULL;
                    break;
                default:
                    throw ParseException.Make (t, "Invalid token type " + t.ToString ());
                }
            }
Member Data Documentation
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Property Documentation
Value Yarn.Parser.ValueNode.value [get], [set]
Definition at line 675 of file Parser.cs.
Referenced by Yarn.Parser.ValueNode.PrintTree(), and Yarn.Parser.ValueNode.UseToken().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs