Yarn.Parser.Node Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
Node (string name, ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
string name [get, set]
string source [get, set]
List< string > nodeTags [get, set]
IEnumerable< Statement > statements [get]
Private Attributes
List< Statement > _statements = new List<Statement> ()
Detailed Description
Definition at line 117 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.Node.Node (string name, ParseNode parent, Parser p) [package]
Definition at line 132 of file Parser.cs.
References Yarn.Parser.Node.name, Yarn.Parser.NextSymbolIs(), and Yarn.Parser.tokens.
                                                                   : base(parent, p) {
                this.name = name;
                // Consume statements until we run out of input or we hit a dedent
                while (p.tokens.Count > 0 && p.NextSymbolIs(TokenType.Dedent,
      TokenType.EndOfInput) == false) {
                    _statements.Add(new Statement(this, p));
                }
            }
Member Function Documentation
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 100 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.Node.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 142 of file Parser.cs.
References Yarn.Parser.Node._statements, Yarn.Parser.Node.name, and Yarn.Parser.Tab().
            {
                var sb = new StringBuilder ();
                sb.Append (Tab (indentLevel, "Node "+name+" {"));
                foreach (var statement in _statements) {
                    sb.Append(statement.PrintTree (indentLevel + 1));
                }
                sb.Append (Tab (indentLevel, "}"));
                return sb.ToString();
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 78 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 94 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
List<Statement> Yarn.Parser.Node._statements = new List<Statement> () [private]
Definition at line 130 of file Parser.cs.
Referenced by Yarn.Parser.Node.PrintTree().
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 61 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 58 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 76 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Property Documentation
string Yarn.Parser.Node.name [get], [set], [package]
Definition at line 119 of file Parser.cs.
Referenced by Yarn.Parser.Node.Node(), and Yarn.Parser.Node.PrintTree().
List<string> Yarn.Parser.Node.nodeTags [get], [set], [package]
Definition at line 124 of file Parser.cs.
string Yarn.Parser.Node.source [get], [set], [package]
Definition at line 121 of file Parser.cs.
IEnumerable<Statement> Yarn.Parser.Node.statements [get], [package]
Definition at line 127 of file Parser.cs.
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs