CsvHelper.ReflectionHelper Class Reference
Common reflection tasks.
Static Public Member Functions
static T CreateInstance< T > (params object[] args)
Creates an instance of type T.
static object CreateInstance (Type type, params object[] args)
Creates an instance of the specified type.
static T GetAttribute< T > (PropertyInfo property, bool inherit)
Gets the first attribute of type T on property.
static T[] GetAttributes< T > (PropertyInfo property, bool inherit)
Gets the attributes of type T on property.
static NewExpression GetConstructor< T > (Expression< Func< T >> expression)
Gets the constructor NewExpression from the give Expression.
static PropertyInfo GetProperty< TModel > (Expression< Func< TModel, object >> expression)
Gets the property from the expression.
Static Private Member Functions
static MemberExpression GetMemberExpression< TModel, T > (Expression< Func< TModel, T >> expression)
Gets the member expression.
Detailed Description
Common reflection tasks.
Definition at line 19 of file ReflectionHelper.cs.
Member Function Documentation
static object CsvHelper.ReflectionHelper.CreateInstance (Type type, params object[] args) [static]
Creates an instance of the specified type.
Parameters
type The type of instance to create.
args The constructor arguments.
Returns
A new instance of the specified type.
Definition at line 42 of file ReflectionHelper.cs.
Referenced by CsvHelper.Configuration.CsvConfiguration.AutoMap(), CsvHelper.Configuration.CsvClassMap.AutoMapInternal(), CsvHelper.ReflectionHelper.CreateInstance< T >(), CsvHelper.Configuration.CsvClassMap< T >.References(), CsvHelper.Configuration.CsvConfiguration.RegisterClassMap(), and CsvHelper.Configuration.CsvPropertyMap.TypeConverter< T >().
        {
#if NET_2_0
            return Activator.CreateInstance(type, args);
#else
            var argumentTypes = args.Select(a => a.GetType()).ToArray();
            var argumentExpressions = argumentTypes.Select((t, i) => Expression.Parameter(t, "var" + i
      )).ToArray();
            var constructorInfo = type.GetConstructor(argumentTypes);
            var constructor = Expression.New(constructorInfo, argumentExpressions);
            var compiled = Expression.Lambda(constructor, argumentExpressions).Compile();
            try
            {
                return compiled.DynamicInvoke(args);
            }
            catch(TargetInvocationException ex)
            {
                throw ex.InnerException;
            }
#endif
        }
static T CsvHelper.ReflectionHelper.CreateInstance< T > (params object[] args) [static]
Creates an instance of type T.
Template Parameters
T The type of instance to create.
Parameters
args The constructor arguments.
Returns
A new instance of type T.
Definition at line 27 of file ReflectionHelper.cs.
References CsvHelper.ReflectionHelper.CreateInstance().
        {
#if NET_2_0
            return Activator.CreateInstance<T>();
#else
            return (T)CreateInstance(typeof(T), args);
#endif
        }
static T CsvHelper.ReflectionHelper.GetAttribute< T > (PropertyInfo property, bool inherit) [static]
Gets the first attribute of type T on property.
Template Parameters
T Type of attribute to get.
Parameters
property The PropertyInfo to get the attribute from.
inherit True to search inheritance tree, otherwise false.
Returns
The first attribute of type T, otherwise null.
Type Constraints
T : Attribute
Definition at line 72 of file ReflectionHelper.cs.
                                                                                       : Attribute
        {
            T attribute = null;
            var attributes = property.GetCustomAttributes(typeof(T), inherit).ToList();
            if(attributes.Count > 0)
            {
                attribute = attributes[0] as T;
            }
            return attribute;
        }
static T [] CsvHelper.ReflectionHelper.GetAttributes< T > (PropertyInfo property, bool inherit) [static]
Gets the attributes of type T on property.
Template Parameters
T Type of attribute to get.
Parameters
property The PropertyInfo to get the attribute from.
inherit True to search inheritance tree, otherwise false.
Returns
The attributes of type T.
Type Constraints
T : Attribute
Definition at line 90 of file ReflectionHelper.cs.
                                                                                          : Attribute
        {
            var attributes = property.GetCustomAttributes(typeof(T), inherit);
            return attributes.Cast<T>().ToArray();
        }
static NewExpression CsvHelper.ReflectionHelper.GetConstructor< T > (Expression< Func< T >> expression) [static]
Gets the constructor NewExpression from the give Expression.
Template Parameters
T The Type of the object that will be constructed.
Parameters
expression The constructor Expression.
Returns
A constructor NewExpression.
Exceptions
System.ArgumentException Not a constructor expression.;expression
Definition at line 103 of file ReflectionHelper.cs.
        {
            var newExpression = expression.Body as NewExpression;
            if(newExpression == null)
            {
                throw new ArgumentException("Not a constructor expression.", nameof(expression));
            }
            return newExpression;
        }
static MemberExpression CsvHelper.ReflectionHelper.GetMemberExpression< TModel, T > (Expression< Func< TModel, T >> expression) [static], [private]
Gets the member expression.
Template Parameters
TModel The type of the model.
T
Parameters
expression The expression.
Returns
Definition at line 139 of file ReflectionHelper.cs.
        {
            MemberExpression memberExpression = null;
            if(expression.Body.NodeType == ExpressionType.Convert)
            {
                var body = (UnaryExpression)expression.Body;
                memberExpression = body.Operand as MemberExpression;
            }
            else if(expression.Body.NodeType == ExpressionType.MemberAccess)
            {
                memberExpression = expression.Body as MemberExpression;
            }
            if(memberExpression == null)
            {
                throw new ArgumentException("Not a member access", nameof(expression));
            }
            return memberExpression;
        }
static PropertyInfo CsvHelper.ReflectionHelper.GetProperty< TModel > (Expression< Func< TModel, object >> expression) [static]
Gets the property from the expression.
Template Parameters
TModel The type of the model.
Parameters
expression The expression.
Returns
The PropertyInfo for the expression.
Definition at line 120 of file ReflectionHelper.cs.
        {
            var member = GetMemberExpression(expression).Member;
            var property = member as PropertyInfo;
            if(property == null)
            {
                throw new CsvConfigurationException($"'{member.Name}' is not a
       property. Did you try to map a field by accident?");
            }
            return property;
        }
The documentation for this class was generated from the following file:
packages/CsvHelper.2.16.0.0/src/CsvHelper/ReflectionHelper.cs