Yarn.Value Class Reference
Public Types
enum Type {
*
Type.Number,
Type.String,
Type.Bool,
Type.Variable,
*
Type.Null
 }
Public Member Functions
Value ()
Value (object value)
virtual int CompareTo (object obj)
virtual int CompareTo (Value other)
override bool Equals (object obj)
override int GetHashCode ()
override string ToString ()
Static Public Member Functions
static Value operator+ (Value a, Value b)
static Value operator- (Value a, Value b)
static Value operator* (Value a, Value b)
static Value operator/ (Value a, Value b)
static Value operator% (Value a, Value b)
static Value operator- (Value a)
static bool operator> (Value operand1, Value operand2)
static bool operator< (Value operand1, Value operand2)
static bool operator>= (Value operand1, Value operand2)
static bool operator<= (Value operand1, Value operand2)
Static Public Attributes
static readonly Value NULL = new Value()
Properties
Value.Type type [get, set]
float numberValue [get, set]
string variableName [get, set]
string stringValue [get, set]
bool boolValue [get, set]
object backingValue [get]
float AsNumber [get]
bool AsBool [get]
string AsString [get]
Detailed Description
Definition at line 7 of file Value.cs.
Member Enumeration Documentation
enum Yarn.Value.Type
Enumerator
Number
String
Bool
Variable
Null
Definition at line 10 of file Value.cs.
                         {
            Number, // a constant number
            String, // a string
            Bool, // a boolean value
            Variable, // the name of a variable; will be expanded at runtime
            Null, // the null value
        }
Constructor & Destructor Documentation
Yarn.Value.Value ()
Definition at line 99 of file Value.cs.
Referenced by Yarn.Value.CompareTo(), Yarn.Value.Equals(), Yarn.Value.operator%(), Yarn.Value.operator*(), Yarn.Value.operator+(), Yarn.Value.operator-(), Yarn.Value.operator/(), and Yarn.Value.Value().
: this(null) { }
Yarn.Value.Value (object value)
Definition at line 102 of file Value.cs.
References Yarn.Value.boolValue, Yarn.Value.numberValue, Yarn.Value.stringValue, Yarn.Value.type, Yarn.Value.Value(), and Yarn.Value.variableName.
        {
            // Copy an existing value
            if (typeof(Value).IsInstanceOfType(value)) {
                var otherValue = value as Value;
                type = otherValue.type;
                switch (type) {
                case Type.Number:
                    numberValue = otherValue.numberValue;
                    break;
                case Type.String:
                    stringValue = otherValue.stringValue;
                    break;
                case Type.Bool:
                    boolValue = otherValue.boolValue;
                    break;
                case Type.Variable:
                    variableName = otherValue.variableName;
                    break;
                case Type.Null:
                    break;
                default:
                    throw new ArgumentOutOfRangeException ();
                }
                return;
            }
            if (value == null) {
                type = Type.Null;
                return;
            }
            if (value.GetType() == typeof(string)) {
                type = Type.String;
                stringValue = System.Convert.ToString(value);
                return;
            }
            if (value.GetType() == typeof(int) ||
                value.GetType() == typeof(float) ||
                value.GetType() == typeof(double)) {
                type = Type.Number;
                numberValue = System.Convert.ToSingle(value);
                return;
            }
            if (value.GetType() == typeof(bool)) {
                type = Type.Bool;
                boolValue = System.Convert.ToBoolean(value);
                return;
            }
            var error = string.Format("Attempted to create a Value using a {0}; currently, " +
                "Values can only be numbers, strings, bools or null.", value.GetType().Name);
            throw new YarnException(error);
        }
Member Function Documentation
virtual int Yarn.Value.CompareTo (object obj) [virtual]
Definition at line 155 of file Value.cs.
References Yarn.Value.Value().
                                                 {
            if (obj == null) return 1;
            // soft, fast coercion
            var other = obj as Value;
            // not a value
            if(other == null) throw new ArgumentException("Object is not a Value");
            // it is a value!
            return this.CompareTo(other);
        }
virtual int Yarn.Value.CompareTo (Value other) [virtual]
Definition at line 168 of file Value.cs.
References Yarn.Value.type.
                                                  {
            if (other == null) {
                return 1;
            }
            if (other.type == this.type) {
                switch (this.type) {
                case Type.Null:
                    return 0;
                case Type.String:
                    return this.stringValue.CompareTo (other.stringValue);
                case Type.Number:
                    return this.numberValue.CompareTo (other.numberValue);
                case Type.Bool:
                    return this.boolValue.CompareTo (other.boolValue);
                }
            }
            // try to do a string test at that point!
            return this.AsString.CompareTo(other.AsString);
        }
override bool Yarn.Value.Equals (object obj)
Definition at line 190 of file Value.cs.
References Yarn.Value.type, and Yarn.Value.Value().
        {
            if (obj == null || GetType() != obj.GetType()) {
                return false;
            }
            var other = (Value)obj;
            switch (this.type) {
            case Type.Number:
                return this.AsNumber == other.AsNumber;
            case Type.String:
                return this.AsString == other.AsString;
            case Type.Bool:
                return this.AsBool == other.AsBool;
            case Type.Null:
                return other.type == Type.Null || other.AsNumber == 0 || other.AsBool == false;
            default:
                throw new ArgumentOutOfRangeException ();
            }
        }
override int Yarn.Value.GetHashCode ()
Definition at line 214 of file Value.cs.
        {
            var backing = this.backingValue;
            // TODO: yeah hay maybe fix this
            if(backing != null) {
                return backing.GetHashCode();
            }
            return 0;
        }
static Value Yarn.Value.operator% (Value a, Value b) [static]
Definition at line 297 of file Value.cs.
References Yarn.Value.AsNumber, Yarn.Value.type, and Yarn.Value.Value().
                                                         {
            if (a.type == Type.Number && (b.type == Type.Number || b.type ==
      Type.Null) ||
                b.type == Type.Number && (a.type == Type.Number || a.type ==
      Type.Null)) {
                return new Value (a.AsNumber % b.AsNumber);
            }
            throw new System.ArgumentException(
                string.Format("Cannot modulo types {0} and {1}.", a.type, b.type)
            );
        }
static Value Yarn.Value.operator* (Value a, Value b) [static]
Definition at line 273 of file Value.cs.
References Yarn.Value.AsNumber, Yarn.Value.type, and Yarn.Value.Value().
                                                         {
            if (a.type == Type.Number && (b.type == Type.Number || b.type ==
      Type.Null) ||
                b.type == Type.Number && (a.type == Type.Number || a.type ==
      Type.Null)
            ) {
                return new Value(a.AsNumber * b.AsNumber);
            }
            throw new System.ArgumentException(
                string.Format("Cannot multiply types {0} and {1}.", a.type, b.type)
            );
        }
static Value Yarn.Value.operator+ (Value a, Value b) [static]
Definition at line 231 of file Value.cs.
References Yarn.Value.AsNumber, Yarn.Value.AsString, Yarn.Value.type, and Yarn.Value.Value().
                                                         {
            // catches:
            // undefined + string
            // number + string
            // string + string
            // bool + string
            // null + string
            if (a.type == Type.String || b.type == Type.String) {
                // we're headed for string town!
                return new Value(a.AsString + b.AsString);
            }
            // catches:
            // number + number
            // bool (=> 0 or 1) + number
            // null (=> 0) + number
            // bool (=> 0 or 1) + bool (=> 0 or 1)
            // null (=> 0) + null (=> 0)
            if ((a.type == Type.Number || b.type == Type.Number) ||
                (a.type == Type.Bool && b.type == Type.Bool) ||
                (a.type == Type.Null && b.type == Type.Null)
            ) {
                return new Value(a.AsNumber + b.AsNumber);
            }
            throw new System.ArgumentException(
                string.Format("Cannot add types {0} and {1}.", a.type, b.type)
            );
        }
static Value Yarn.Value.operator- (Value a, Value b) [static]
Definition at line 261 of file Value.cs.
References Yarn.Value.AsNumber, Yarn.Value.type, and Yarn.Value.Value().
                                                         {
            if (a.type == Type.Number && (b.type == Type.Number || b.type ==
      Type.Null) ||
                b.type == Type.Number && (a.type == Type.Number || a.type ==
      Type.Null)
            ) {
                return new Value(a.AsNumber - b.AsNumber);
            }
            throw new System.ArgumentException(
                string.Format("Cannot subtract types {0} and {1}.", a.type, b.type)
            );
        }
static Value Yarn.Value.operator- (Value a) [static]
Definition at line 307 of file Value.cs.
References Yarn.Value.AsNumber, Yarn.Value.AsString, Yarn.Value.type, and Yarn.Value.Value().
                                                {
            if(a.type == Type.Number) {
                return new Value(-a.AsNumber);
            }
            if (a.type == Type.Null &&
                a.type == Type.String &&
               (a.AsString == null || a.AsString.Trim() == "")
            ) {
                return new Value(-0);
            }
            return new Value(float.NaN);
        }
static Value Yarn.Value.operator/ (Value a, Value b) [static]
Definition at line 285 of file Value.cs.
References Yarn.Value.AsNumber, Yarn.Value.type, and Yarn.Value.Value().
                                                         {
            if (a.type == Type.Number && (b.type == Type.Number || b.type ==
      Type.Null) ||
                b.type == Type.Number && (a.type == Type.Number || a.type ==
      Type.Null)
            ) {
                return new Value(a.AsNumber / b.AsNumber);
            }
            throw new System.ArgumentException(
                string.Format("Cannot divide types {0} and {1}.", a.type, b.type)
            );
        }
static bool Yarn.Value.operator< (Value operand1, Value operand2) [static]
Definition at line 327 of file Value.cs.
        {
            return operand1.CompareTo(operand2) == -1;
        }
static bool Yarn.Value.operator<= (Value operand1, Value operand2) [static]
Definition at line 339 of file Value.cs.
        {
            return operand1.CompareTo(operand2) <= 0;
        }
static bool Yarn.Value.operator> (Value operand1, Value operand2) [static]
Definition at line 321 of file Value.cs.
        {
            return operand1.CompareTo(operand2) == 1;
        }
static bool Yarn.Value.operator>= (Value operand1, Value operand2) [static]
Definition at line 333 of file Value.cs.
        {
            return operand1.CompareTo(operand2) >= 0;
        }
override string Yarn.Value.ToString ()
Definition at line 226 of file Value.cs.
References Yarn.Value.AsBool, Yarn.Value.AsNumber, Yarn.Value.AsString, and Yarn.Value.type.
        {
            return string.Format ("[Value: type={0}, AsNumber={1}, AsBool={2}, AsString={3}]",
      type, AsNumber, AsBool, AsString);
        }
Member Data Documentation
readonly Value Yarn.Value.NULL = new Value() [static]
Definition at line 8 of file Value.cs.
Referenced by Yarn.MemoryVariableStore.GetValue(), Yarn.FunctionInfo.InvokeWithArray(), Yarn.VirtualMachine.RunInstruction(), and Yarn.Parser.ValueNode.UseToken().
Property Documentation
bool Yarn.Value.AsBool [get]
Definition at line 61 of file Value.cs.
Referenced by Yarn.YarnSpinnerConsole.CreateDialogue(), and Yarn.Value.ToString().
float Yarn.Value.AsNumber [get]
Definition at line 40 of file Value.cs.
Referenced by Yarn.Value.operator%(), Yarn.Value.operator*(), Yarn.Value.operator+(), Yarn.Value.operator-(), Yarn.Value.operator/(), and Yarn.Value.ToString().
string Yarn.Value.AsString [get]
Definition at line 78 of file Value.cs.
Referenced by Yarn.Value.operator+(), Yarn.Value.operator-(), and Yarn.Value.ToString().
object Yarn.Value.backingValue [get], [private]
Definition at line 26 of file Value.cs.
bool Yarn.Value.boolValue [get], [set], [package]
Definition at line 24 of file Value.cs.
Referenced by Yarn.Parser.ValueNode.PrintTree(), and Yarn.Value.Value().
float Yarn.Value.numberValue [get], [set], [package]
Definition at line 21 of file Value.cs.
Referenced by Yarn.Parser.ValueNode.PrintTree(), and Yarn.Value.Value().
string Yarn.Value.stringValue [get], [set], [package]
Definition at line 23 of file Value.cs.
Referenced by Yarn.Parser.ValueNode.PrintTree(), and Yarn.Value.Value().
Value.Type Yarn.Value.type [get], [set]
Definition at line 18 of file Value.cs.
Referenced by Yarn.Value.CompareTo(), Yarn.Value.Equals(), Yarn.Value.operator%(), Yarn.Value.operator*(), Yarn.Value.operator+(), Yarn.Value.operator-(), Yarn.Value.operator/(), Yarn.Parser.ValueNode.PrintTree(), Yarn.Value.ToString(), and Yarn.Value.Value().
string Yarn.Value.variableName [get], [set], [package]
Definition at line 22 of file Value.cs.
Referenced by Yarn.Parser.ValueNode.PrintTree(), and Yarn.Value.Value().
The documentation for this class was generated from the following file:
YarnSpinner/Value.cs