Yarn.Program Class Reference
Public Member Functions
void LoadStrings (Dictionary< string, string > newStrings)
Loads a new string table into the program.
string RegisterString (string theString, string nodeName, string lineID, int lineNumber, bool localisable)
string GetString (string key)
string DumpCode (Library l)
string GetTextForNode (string nodeName)
IEnumerable< string > GetTagsForNode (string nodeName)
void Include (Program otherProgram)
Package Attributes
Dictionary< string, string > strings = new Dictionary<string, string>()
Dictionary< string, LineInfo > lineInfo = new Dictionary<string, LineInfo>()
Dictionary< string, Node > nodes = new Dictionary<string, Node>()
Properties
Dictionary< string, string > untaggedStrings [get]
Private Attributes
int stringCount = 0
Detailed Description
Definition at line 84 of file Program.cs.
Member Function Documentation
string Yarn.Program.DumpCode (Library l)
Definition at line 162 of file Program.cs.
References Yarn.Program.lineInfo, Yarn.Program.nodes, and Yarn.Program.strings.
        {
            var sb = new System.Text.StringBuilder();
            foreach (var entry in nodes)
            {
                sb.AppendLine("Node " + entry.Key + ":");
                int instructionCount = 0;
                foreach (var instruction in entry.Value.instructions)
                {
                    string instructionText;
                    if (instruction.operation == ByteCode.Label)
                    {
                        instructionText = instruction.ToString(this, l);
                    }
                    else
                    {
                        instructionText = " " + instruction.ToString(this, l);
                    }
                    string preface;
                    if (instructionCount % 5 == 0 || instructionCount == entry.Value.instructions.Count - 1
      )
                    {
                        preface = string.Format(CultureInfo.InvariantCulture, "{0,6} ", instructionCount)
      ;
                    }
                    else
                    {
                        preface = string.Format(CultureInfo.InvariantCulture, "{0,6} ", " ");
                    }
                    sb.AppendLine(preface + instructionText);
                    instructionCount++;
                }
                sb.AppendLine();
            }
            sb.AppendLine("String table:");
            foreach (var entry in strings)
            {
                var lineInfo = this.lineInfo[entry.Key];
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "{0}: {1} ({2}:{3})", entry.Key,
      entry.Value, lineInfo.nodeName, lineInfo.lineNumber));
            }
            return sb.ToString();
        }
string Yarn.Program.GetString (string key)
Definition at line 155 of file Program.cs.
        {
            string value = null;
            strings.TryGetValue(key, out value);
            return value;
        }
IEnumerable<string> Yarn.Program.GetTagsForNode (string nodeName)
Definition at line 221 of file Program.cs.
References Yarn.Program.nodes.
        {
            return nodes[nodeName].tags;
        }
string Yarn.Program.GetTextForNode (string nodeName)
Definition at line 216 of file Program.cs.
References Yarn.Program.nodes.
        {
            return this.GetString(nodes[nodeName].sourceTextStringID);
        }
void Yarn.Program.Include (Program otherProgram)
Definition at line 226 of file Program.cs.
References Yarn.Program.nodes, and Yarn.Program.strings.
        {
            foreach (var otherNodeName in otherProgram.nodes)
            {
                if (nodes.ContainsKey(otherNodeName.Key))
                {
                    throw new InvalidOperationException(string.Format(CultureInfo.CurrentCulture, "This
       program already contains a node named {0}", otherNodeName.Key));
                }
                nodes[otherNodeName.Key] = otherNodeName.Value;
            }
            foreach (var otherString in otherProgram.strings)
            {
                if (nodes.ContainsKey(otherString.Key))
                {
                    throw new InvalidOperationException(string.Format(CultureInfo.CurrentCulture, "This
       program already contains a string with key {0}", otherString.Key));
                }
                strings[otherString.Key] = otherString.Value;
            }
        }
void Yarn.Program.LoadStrings (Dictionary< string, string > newStrings)
Loads a new string table into the program.
The string table is merged with any existing strings, with the new table taking precedence over the old.
Definition at line 125 of file Program.cs.
References Yarn.Program.strings.
        {
            foreach (var entry in newStrings)
            {
                strings[entry.Key] = entry.Value;
            }
        }
string Yarn.Program.RegisterString (string theString, string nodeName, string lineID, int lineNumber, bool localisable)
Definition at line 133 of file Program.cs.
References Yarn.Program.stringCount.
        {
            string key;
            if (lineID == null)
                key = string.Format(CultureInfo.InvariantCulture, "{0}-{1}", nodeName,
      stringCount++);
            else
                key = lineID;
            // It's not in the list; append it
            strings.Add(key, theString);
            if (localisable)
            {
                // Additionally, keep info about this string around
                lineInfo.Add(key, new LineInfo(nodeName, lineNumber));
            }
            return key;
        }
Member Data Documentation
Dictionary<string, LineInfo> Yarn.Program.lineInfo = new Dictionary<string, LineInfo>() [package]
Definition at line 88 of file Program.cs.
Referenced by Yarn.Program.DumpCode().
Dictionary<string, Node> Yarn.Program.nodes = new Dictionary<string, Node>() [package]
Definition at line 91 of file Program.cs.
Referenced by Yarn.Compiler.CompileNode(), Yarn.Program.DumpCode(), Yarn.Dialogue.GetTagsForAllNodes(), Yarn.Program.GetTagsForNode(), Yarn.Dialogue.GetTagsForNode(), Yarn.Dialogue.GetTextForAllNodes(), Yarn.Program.GetTextForNode(), Yarn.Dialogue.GetTextForNode(), Yarn.Program.Include(), Yarn.Dialogue.NodeExists(), and Yarn.VirtualMachine.SetNode().
int Yarn.Program.stringCount = 0 [private]
Definition at line 119 of file Program.cs.
Referenced by Yarn.Program.RegisterString().
Dictionary<string, string> Yarn.Program.strings = new Dictionary<string, string>() [package]
Definition at line 87 of file Program.cs.
Referenced by Yarn.Program.DumpCode(), Yarn.Program.Include(), and Yarn.Program.LoadStrings().
Property Documentation
Dictionary<string, string> Yarn.Program.untaggedStrings [get], [package]
Definition at line 103 of file Program.cs.
The documentation for this class was generated from the following file:
YarnSpinner/Program.cs