Yarn.VirtualMachine Class Reference
Classes
class SpecialVariables
class State
Public Types
enum ExecutionState { ExecutionState.Stopped,
ExecutionState.WaitingOnOptionSelection,
ExecutionState.Running
 }
Public Member Functions
delegate void LineHandler (Dialogue.LineResult line)
delegate void OptionsHandler (Dialogue.OptionSetResult options)
delegate void CommandHandler (Dialogue.CommandResult command)
delegate void NodeCompleteHandler (Dialogue.NodeCompleteResult complete)
bool SetNode (string nodeName)
void Stop ()
Public Attributes
LineHandler lineHandler
OptionsHandler optionsHandler
CommandHandler commandHandler
NodeCompleteHandler nodeCompleteHandler
Package Functions
VirtualMachine (Dialogue d, Program p)
void RunNext ()
Executes the next instruction in the current node.
int FindInstructionPointForLabel (string labelName)
Looks up the instruction number for a named label in the current node.
void RunInstruction (Instruction i)
Properties
string currentNodeName [get]
ExecutionState executionState [get, set]
Private Member Functions
void ResetState ()
Reset the state of the VM.
Private Attributes
Dialogue dialogue
Program program
State state = new State()
Random random = new Random()
ExecutionState _executionState
Node currentNode
Detailed Description
Definition at line 7 of file VirtualMachine.cs.
Class Documentation
class Yarn::VirtualMachine::SpecialVariables
Definition at line 49 of file VirtualMachine.cs.
Class Members
const string
ShuffleOptions
Member Enumeration Documentation
enum Yarn.VirtualMachine.ExecutionState
Enumerator
Stopped
 Stopped.
WaitingOnOptionSelection
 Waiting on option selection.
Running
 Running.
Definition at line 88 of file VirtualMachine.cs.
                                   {
            Stopped,
            WaitingOnOptionSelection,
            Running
        }
Constructor & Destructor Documentation
Yarn.VirtualMachine.VirtualMachine (Dialogue d, Program p) [package]
Definition at line 53 of file VirtualMachine.cs.
References Yarn.VirtualMachine.dialogue, Yarn.VirtualMachine.program, and Yarn.VirtualMachine.state.
        {
            program = p;
            dialogue = d;
            state = new State ();
        }
Member Function Documentation
delegate void Yarn.VirtualMachine.CommandHandler (Dialogue.CommandResult command)
int Yarn.VirtualMachine.FindInstructionPointForLabel (string labelName) [package]
Looks up the instruction number for a named label in the current node.
Definition at line 164 of file VirtualMachine.cs.
References Yarn.VirtualMachine.currentNode, Yarn.VirtualMachine.State.currentNodeName, Yarn.Node.labels, and Yarn.VirtualMachine.state.
Referenced by Yarn.VirtualMachine.RunInstruction().
                                                                    {
            if (currentNode.labels.ContainsKey(labelName) == false) {
                // Couldn't find the node..
                throw new IndexOutOfRangeException ("Unknown label " +
                    labelName + " in node " + state.currentNodeName);
            }
            return currentNode.labels [labelName];
        }
delegate void Yarn.VirtualMachine.LineHandler (Dialogue.LineResult line)
delegate void Yarn.VirtualMachine.NodeCompleteHandler (Dialogue.NodeCompleteResult complete)
delegate void Yarn.VirtualMachine.OptionsHandler (Dialogue.OptionSetResult options)
void Yarn.VirtualMachine.ResetState () [private]
Reset the state of the VM.
Definition at line 61 of file VirtualMachine.cs.
References Yarn.VirtualMachine.state.
Referenced by Yarn.VirtualMachine.SetNode().
                          {
            state = new State();
        }
void Yarn.VirtualMachine.RunInstruction (Instruction i) [package]
Label
No-op, used as a destination for JumpTo and Jump.
JumpTo
Jumps to a named label
RunLine
Looks up a string from the string table and passes it to the client as a line
RunCommand
Passes a string to the client as a custom command
PushString
Pushes a string value onto the stack. The operand is an index into the string table, so that's looked up first.
PushNumber
Pushes a number onto the stack.
PushBool
Pushes a boolean value onto the stack.
PushNull
Pushes a null value onto the stack.
JumpIfFalse
Jumps to a named label if the value on the top of the stack evaluates to the boolean value 'false'.
Jump
Jumps to a label whose name is on the stack.
Pop
Pops a value from the stack.
CallFunc
Call a function, whose parameters are expected to be on the stack. Pushes the function's return value, if it returns one.
PushVariable
Get the contents of a variable, push that onto the stack.
StoreVariable
Store the top value on the stack in a variable.
Stop
Immediately stop execution, and report that fact.
RunNode
Run a node
AddOption
Add an option to the current state.
ShowOptions
If we have no options to show, immediately stop.
If we have a single option, and it has no label, select it immediately and continue execution
default
Whoa, no idea what bytecode this is. Stop the program and throw an exception.
Definition at line 176 of file VirtualMachine.cs.
References Yarn.VirtualMachine.commandHandler, Yarn.Dialogue.continuity, Yarn.VirtualMachine.State.currentOptions, Yarn.VirtualMachine.dialogue, Yarn.VirtualMachine.executionState, Yarn.VirtualMachine.FindInstructionPointForLabel(), Yarn.Library.GetFunction(), Yarn.VariableStorage.GetValue(), Yarn.Dialogue.library, Yarn.VirtualMachine.lineHandler, Yarn.VirtualMachine.nodeCompleteHandler, Yarn.Value.NULL, Yarn.Instruction.operandA, Yarn.Instruction.operation, Yarn.VirtualMachine.optionsHandler, Yarn.VirtualMachine.State.PeekValue(), Yarn.VirtualMachine.State.PopValue(), Yarn.VirtualMachine.random, Yarn.VirtualMachine.SetNode(), Yarn.VariableStorage.SetValue(), Yarn.VirtualMachine.SpecialVariables.ShuffleOptions, and Yarn.VirtualMachine.state.
Referenced by Yarn.VirtualMachine.RunNext().
                                                    {
            switch (i.operation) {
            case ByteCode.Label:
                break;
            case ByteCode.JumpTo:
                state.programCounter = FindInstructionPointForLabel ((string)i.
      operandA);
                break;
            case ByteCode.RunLine:
                var lineText = program.GetString ((string)i.operandA);
                if (lineText == null) {
                    dialogue.LogErrorMessage("No loaded string table includes line " + i.operandA);
                    break;
                }
                lineHandler (new Dialogue.LineResult (lineText));
                break;
            case ByteCode.RunCommand:
                commandHandler (
                    new Dialogue.CommandResult ((string)i.operandA)
                );
                break;
            case ByteCode.PushString:
                state.PushValue (program.GetString ((string)i.operandA));
                break;
            case ByteCode.PushNumber:
                state.PushValue (Convert.ToSingle(i.operandA, CultureInfo.InvariantCulture));
                break;
            case ByteCode.PushBool:
                state.PushValue (Convert.ToBoolean(i.operandA, CultureInfo.InvariantCulture));
                break;
            case ByteCode.PushNull:
                state.PushValue (Value.NULL);
                break;
            case ByteCode.JumpIfFalse:
                if (state.PeekValue ().AsBool == false) {
                    state.programCounter = FindInstructionPointForLabel ((
      string)i.operandA);
                }
                break;
            case ByteCode.Jump:
                var jumpDestination = state.PeekValue ().AsString;
                state.programCounter = FindInstructionPointForLabel (
      jumpDestination);
                break;
            case ByteCode.Pop:
                state.PopValue ();
                break;
            case ByteCode.CallFunc:
                var functionName = (string)i.operandA;
                var function = dialogue.library.GetFunction (functionName);
                {
                    var paramCount = function.paramCount;
                    // If this function takes "-1" parameters, it is variadic.
                    // Expect the compiler to have placed the number of parameters
                    // actually passed at the top of the stack.
                    if (paramCount == -1) {
                        paramCount = (int)state.PopValue ().AsNumber;
                    }
                    Value result;
                    if (paramCount == 0) {
                        result = function.Invoke();
                    } else {
                        // Get the parameters, which were pushed in reverse
                        Value[] parameters = new Value[paramCount];
                        for (int param = paramCount - 1; param >= 0; param--) {
                            parameters [param] = state.PopValue ();
                        }
                        // Invoke the function
                        result = function.InvokeWithArray (parameters);
                    }
                    // If the function returns a value, push it
                    if (function.returnsValue) {
                        state.PushValue (result);
                    }
                }
                break;
            case ByteCode.PushVariable:
                var variableName = (string)i.operandA;
                var loadedValue = dialogue.continuity.GetValue (variableName);
                state.PushValue (loadedValue);
                break;
            case ByteCode.StoreVariable:
                var topValue = state.PeekValue ();
                var destinationVariableName = (string)i.operandA;
                dialogue.continuity.SetValue (destinationVariableName, topValue);
                break;
            case ByteCode.Stop:
                nodeCompleteHandler (new Dialogue.NodeCompleteResult (null));
                executionState = ExecutionState.Stopped;
                break;
            case ByteCode.RunNode:
                string nodeName;
                if (string.IsNullOrEmpty((string) i.operandA)) {
                    // Get a string from the stack, and jump to a node with that name.
                     nodeName = state.PeekValue ().AsString;
                } else {
                    // jump straight to the node
                    nodeName = (string)i.operandA;
                }
                nodeCompleteHandler (new Dialogue.NodeCompleteResult (nodeName));
                SetNode (nodeName);
                break;
            case ByteCode.AddOption:
                state.currentOptions.Add (new KeyValuePair<string, string> ((string)i.operandA, (string)
      i.operandB));
                break;
            case ByteCode.ShowOptions:
                if (state.currentOptions.Count == 0) {
                    nodeCompleteHandler(new Dialogue.NodeCompleteResult(null));
                    executionState = ExecutionState.Stopped;
                    break;
                }
                if (state.currentOptions.Count == 1 && state.
      currentOptions[0].Key == null) {
                    var destinationNode = state.currentOptions[0].Value;
                    state.PushValue(destinationNode);
                    state.currentOptions.Clear();
                    break;
                }
                if (dialogue.continuity.GetValue(SpecialVariables.ShuffleOptions)
      .AsBool) {
                    // Shuffle the dialog options if needed
                    var n = state.currentOptions.Count;
                    for (int opt1 = 0; opt1 < n; opt1++) {
                        int opt2 = opt1 + (int)(random.NextDouble () * (n - opt1)); // r.Next(0,
       state.currentOptions.Count-1);
                        var temp = state.currentOptions [opt2];
                        state.currentOptions [opt2] = state.currentOptions [opt1];
                        state.currentOptions [opt1] = temp;
                    }
                }
                // Otherwise, present the list of options to the user and let them pick
                var optionStrings = new List<string> ();
                foreach (var option in state.currentOptions) {
                    optionStrings.Add (program.GetString (option.Key));
                }
                // We can't continue until our client tell us which option to pick
                executionState = ExecutionState.WaitingOnOptionSelection;
                // Pass the options set to the client, as well as a delegate for them to call when the
                // user has made a selection
                optionsHandler (new Dialogue.OptionSetResult (optionStrings, delegate (int
      selectedOption) {
                    // we now know what number option was selected; push the corresponding node name
                    // to the stack
                    var destinationNode = state.currentOptions[selectedOption].Value;
                    state.PushValue(destinationNode);
                    // We no longer need the accumulated list of options; clear it so that it's
                    // ready for the next one
                    state.currentOptions.Clear();
                    // We can now also keep running
                    executionState = ExecutionState.Running;
                }));
                break;
            default:
                executionState = ExecutionState.Stopped;
                throw new ArgumentOutOfRangeException ();
            }
        }
void Yarn.VirtualMachine.RunNext () [package]
Executes the next instruction in the current node.
Definition at line 138 of file VirtualMachine.cs.
References Yarn.VirtualMachine.currentNode, Yarn.VirtualMachine.executionState, Yarn.Node.instructions, Yarn.VirtualMachine.nodeCompleteHandler, Yarn.VirtualMachine.State.programCounter, Yarn.VirtualMachine.RunInstruction(), and Yarn.VirtualMachine.state.
                                {
            if (executionState == ExecutionState.WaitingOnOptionSelection) {
                dialogue.LogErrorMessage ("Cannot continue running dialogue. Still waiting on option
       selection.");
                executionState = ExecutionState.Stopped;
                return;
            }
            if (executionState == ExecutionState.Stopped)
                executionState = ExecutionState.Running;
            Instruction currentInstruction = currentNode.instructions [state.programCounter];
            RunInstruction (currentInstruction);
            state.programCounter++;
            if (state.programCounter >= currentNode.
      instructions.Count) {
                executionState = ExecutionState.Stopped;
                nodeCompleteHandler(new Dialogue.NodeCompleteResult(null));
                dialogue.LogDebugMessage ("Run complete.");
            }
        }
bool Yarn.VirtualMachine.SetNode (string nodeName)
Definition at line 112 of file VirtualMachine.cs.
References Yarn.VirtualMachine.currentNode, Yarn.VirtualMachine.executionState, Yarn.Program.nodes, Yarn.VirtualMachine.program, Yarn.VirtualMachine.ResetState(), and Yarn.VirtualMachine.SpecialVariables.ShuffleOptions.
Referenced by Yarn.Dialogue.Run(), and Yarn.VirtualMachine.RunInstruction().
                                             {
            if (program.nodes.ContainsKey(nodeName) == false) {
                var error = "No node named " + nodeName;
                dialogue.LogErrorMessage(error);
                executionState = ExecutionState.Stopped;
                return false;
            }
            dialogue.LogDebugMessage ("Running node " + nodeName);
            // Clear the special variables
            dialogue.continuity.SetValue(SpecialVariables.ShuffleOptions,
      new Value(false));
            currentNode = program.nodes [nodeName];
            ResetState ();
            state.currentNodeName = nodeName;
            return true;
        }
void Yarn.VirtualMachine.Stop ()
Definition at line 133 of file VirtualMachine.cs.
References Yarn.VirtualMachine.executionState.
                           {
            executionState = ExecutionState.Stopped;
        }
Member Data Documentation
ExecutionState Yarn.VirtualMachine._executionState [private]
Definition at line 97 of file VirtualMachine.cs.
CommandHandler Yarn.VirtualMachine.commandHandler
Definition at line 72 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.RunInstruction().
Node Yarn.VirtualMachine.currentNode [private]
Definition at line 110 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.FindInstructionPointForLabel(), Yarn.VirtualMachine.RunNext(), and Yarn.VirtualMachine.SetNode().
Dialogue Yarn.VirtualMachine.dialogue [private]
Definition at line 75 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.RunInstruction(), and Yarn.VirtualMachine.VirtualMachine().
LineHandler Yarn.VirtualMachine.lineHandler
Definition at line 70 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.RunInstruction().
NodeCompleteHandler Yarn.VirtualMachine.nodeCompleteHandler
Definition at line 73 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.RunInstruction(), and Yarn.VirtualMachine.RunNext().
OptionsHandler Yarn.VirtualMachine.optionsHandler
Definition at line 71 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.RunInstruction().
Program Yarn.VirtualMachine.program [private]
Definition at line 77 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.SetNode(), and Yarn.VirtualMachine.VirtualMachine().
Random Yarn.VirtualMachine.random = new Random() [private]
Definition at line 80 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.RunInstruction().
State Yarn.VirtualMachine.state = new State() [private]
Definition at line 78 of file VirtualMachine.cs.
Referenced by Yarn.VirtualMachine.FindInstructionPointForLabel(), Yarn.VirtualMachine.ResetState(), Yarn.VirtualMachine.RunInstruction(), Yarn.VirtualMachine.RunNext(), and Yarn.VirtualMachine.VirtualMachine().
Property Documentation
string Yarn.VirtualMachine.currentNodeName [get]
Definition at line 82 of file VirtualMachine.cs.
ExecutionState Yarn.VirtualMachine.executionState [get], [set]
Definition at line 98 of file VirtualMachine.cs.
Referenced by Yarn.Dialogue.Run(), Yarn.VirtualMachine.RunInstruction(), Yarn.VirtualMachine.RunNext(), Yarn.VirtualMachine.SetNode(), and Yarn.VirtualMachine.Stop().
The documentation for this class was generated from the following file:
YarnSpinner/VirtualMachine.cs