Yarn.Parser.Statement Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Types
enum Type {
*
Type.CustomCommand,
Type.ShortcutOptionGroup,
Type.Block,
Type.IfStatement,
*
Type.OptionStatement,
Type.AssignmentStatement,
Type.Line
 }
Package Functions
Statement (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
Statement.Type type [get, set]
Block block [get, set]
IfStatement ifStatement [get, set]
OptionStatement optionStatement [get, set]
AssignmentStatement assignmentStatement [get, set]
CustomCommand customCommand [get, set]
string line [get, set]
ShortcutOptionGroup shortcutOptionGroup [get, set]
Detailed Description
Definition at line 163 of file Parser.cs.
Member Enumeration Documentation
enum Yarn.Parser.Statement.Type [package]
Enumerator
CustomCommand
ShortcutOptionGroup
Block
IfStatement
OptionStatement
AssignmentStatement
Line
Definition at line 165 of file Parser.cs.
                               {
                CustomCommand,
                ShortcutOptionGroup,
                Block,
                IfStatement,
                OptionStatement,
                AssignmentStatement,
                Line
            }
Constructor & Destructor Documentation
Yarn.Parser.Statement.Statement (ParseNode parent, Parser p) [package]
Definition at line 186 of file Parser.cs.
References Yarn.Parser.Statement.AssignmentStatement, Yarn.Parser.Statement.assignmentStatement, Yarn.Parser.Statement.Block, Yarn.Parser.Statement.block, Yarn.Parser.CustomCommand.CanParse(), Yarn.Parser.ShortcutOptionGroup.CanParse(), Yarn.Parser.Block.CanParse(), Yarn.Parser.OptionStatement.CanParse(), Yarn.Parser.IfStatement.CanParse(), Yarn.Parser.AssignmentStatement.CanParse(), Yarn.Parser.Statement.CustomCommand, Yarn.Parser.Statement.customCommand, Yarn.Parser.Statement.IfStatement, Yarn.Parser.Statement.ifStatement, Yarn.Parser.Statement.line, Yarn.Parser.NextSymbolIs(), Yarn.Parser.Statement.OptionStatement, Yarn.Parser.Statement.optionStatement, Yarn.Parser.Statement.ShortcutOptionGroup, Yarn.Parser.Statement.shortcutOptionGroup, Yarn.Parser.ParseNode.tags, Yarn.Parser.tokens, and Yarn.Parser.Statement.type.
                                                           : base(parent, p) {
                if (Block.CanParse(p)) {
                    type = Type.Block;
                    block = new Block(this, p);
                } else if (IfStatement.CanParse(p)) {
                    type = Type.IfStatement;
                    ifStatement = new IfStatement(this, p);
                } else if (OptionStatement.CanParse(p)) {
                    type = Type.OptionStatement;
                    optionStatement = new OptionStatement(this, p);
                } else if (AssignmentStatement.CanParse(p)) {
                    type = Type.AssignmentStatement;
                    assignmentStatement = new
      AssignmentStatement(this, p);
                } else if (ShortcutOptionGroup.CanParse(p)) {
                    type = Type.ShortcutOptionGroup;
                    shortcutOptionGroup = new
      ShortcutOptionGroup(this, p);
                } else if (CustomCommand.CanParse(p)) {
                    type = Type.CustomCommand;
                    customCommand = new CustomCommand(this, p);
                } else if (p.NextSymbolIs(TokenType.Text)) {
                    line = p.ExpectSymbol(TokenType.Text).value as string;
                    type = Type.Line;
                } else {
                    throw ParseException.Make(p.tokens.Peek(), "Expected a statement here but got " + p.
      tokens.Peek().ToString() +" instead (was there an unbalanced if statement earlier?)");
                }
                // Parse the optional tags that follow this statement
                var tags = new List<string>();
                while (p.NextSymbolIs(TokenType.TagMarker)) {
                    p.ExpectSymbol(TokenType.TagMarker);
                    var tag = p.ExpectSymbol(TokenType.Identifier).value;
                    tags.Add(tag);
                }
                if (tags.Count > 0)
                    this.tags = tags.ToArray();
            }
Member Function Documentation
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 100 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.Statement.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 226 of file Parser.cs.
References Yarn.Parser.Statement.line, Yarn.Parser.Tab(), Yarn.Parser.ParseNode.TagsToString(), and Yarn.Parser.Statement.type.
            {
                StringBuilder s = new StringBuilder ();
                switch (type) {
                case Type.Block:
                    s.Append(block.PrintTree (indentLevel));
                    break;
                case Type.IfStatement:
                    s.Append (ifStatement.PrintTree (indentLevel));
                    break;
                case Type.OptionStatement:
                    s.Append (optionStatement.PrintTree (indentLevel));
                    break;
                case Type.AssignmentStatement:
                    s.Append (assignmentStatement.PrintTree (indentLevel));
                    break;
                case Type.ShortcutOptionGroup:
                    s.Append (shortcutOptionGroup.PrintTree (indentLevel));
                    break;
                case Type.CustomCommand:
                    s.Append (customCommand.PrintTree (indentLevel));
                    break;
                case Type.Line:
                    s.Append (Tab (indentLevel, "Line: " + line));
                    break;
                default:
                    throw new ArgumentNullException ();
                }
                s.Append (TagsToString (indentLevel));
                return s.ToString ();
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 78 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 94 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 61 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 58 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 76 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Property Documentation
AssignmentStatement Yarn.Parser.Statement.assignmentStatement [get], [set], [package]
Definition at line 181 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
Block Yarn.Parser.Statement.block [get], [set], [package]
Definition at line 178 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
CustomCommand Yarn.Parser.Statement.customCommand [get], [set], [package]
Definition at line 182 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
IfStatement Yarn.Parser.Statement.ifStatement [get], [set], [package]
Definition at line 179 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
string Yarn.Parser.Statement.line [get], [set], [package]
Definition at line 183 of file Parser.cs.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.Statement.Statement().
OptionStatement Yarn.Parser.Statement.optionStatement [get], [set], [package]
Definition at line 180 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
ShortcutOptionGroup Yarn.Parser.Statement.shortcutOptionGroup [get], [set], [package]
Definition at line 184 of file Parser.cs.
Referenced by Yarn.Parser.Statement.Statement().
Statement.Type Yarn.Parser.Statement.type [get], [set], [package]
Definition at line 175 of file Parser.cs.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.Statement.Statement().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs