Yarn.Parser.Operator Class Reference
Classes
struct OperatorInfo
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Types
enum Associativity { Associativity.Left,
Associativity.Right,
Associativity.None
 }
Package Functions
Operator (ParseNode parent, TokenType t, Parser p)
Operator (ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Static Package Functions
static OperatorInfo InfoForOperator (TokenType op)
static bool IsOperator (TokenType type)
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
TokenType operatorType [get, set]
static TokenType[] OperatorTypes [get]
Detailed Description
Definition at line 1145 of file Parser.cs.
Member Enumeration Documentation
enum Yarn.Parser.Operator.Associativity [package]
Enumerator
Left
Right
None
Definition at line 1148 of file Parser.cs.
                                        {
                Left, // resolve leftmost operand first
                Right, // resolve rightmost operand first
                None // special-case (like "(", ")", ","
            }
Constructor & Destructor Documentation
Yarn.Parser.Operator.Operator (ParseNode parent, TokenType t, Parser p) [package]
Definition at line 1241 of file Parser.cs.
References Yarn.Parser.Operator.operatorType.
                                                                       : base(
      parent, p) {
                operatorType = t;
            }
Yarn.Parser.Operator.Operator (ParseNode parent, Parser p) [package]
Definition at line 1245 of file Parser.cs.
References Yarn.Parser.Operator.operatorType, and Yarn.Parser.Operator.OperatorTypes.
                                                          : base(parent, p) {
                operatorType = p.ExpectSymbol(Operator.OperatorTypes).
      type;
            }
Member Function Documentation
static OperatorInfo Yarn.Parser.Operator.InfoForOperator (TokenType op) [static], [package]
Definition at line 1166 of file Parser.cs.
References Yarn.Parser.Operator.OperatorTypes.
                                                                       {
                if (Array.IndexOf(OperatorTypes, op) == -1) {
                    throw new ParseException (op.ToString () + " is not a valid operator");
                }
                // Determine the precendence, associativity and
                // number of operands that each operator has.
                switch (op) {
                case TokenType.Not:
                case TokenType.UnaryMinus:
                    return new OperatorInfo (Associativity.Right, 30, 1);
                case TokenType.Multiply:
                case TokenType.Divide:
                case TokenType.Modulo:
                    return new OperatorInfo(Associativity.Left, 20,2);
                case TokenType.Add:
                case TokenType.Minus:
                    return new OperatorInfo(Associativity.Left, 15,2);
                case TokenType.GreaterThan:
                case TokenType.LessThan:
                case TokenType.GreaterThanOrEqualTo:
                case TokenType.LessThanOrEqualTo:
                    return new OperatorInfo(Associativity.Left, 10,2);
                case TokenType.EqualTo:
                case TokenType.EqualToOrAssign:
                case TokenType.NotEqualTo:
                    return new OperatorInfo(Associativity.Left, 5,2);
                case TokenType.And:
                    return new OperatorInfo(Associativity.Left, 4,2);
                case TokenType.Or:
                    return new OperatorInfo(Associativity.Left, 3,2);
                case TokenType.Xor:
                    return new OperatorInfo(Associativity.Left, 2,2);
                }
                throw new InvalidOperationException ("Unknown operator " + op.ToString());
            }
static bool Yarn.Parser.Operator.IsOperator (TokenType type) [static], [package]
Definition at line 1207 of file Parser.cs.
References Yarn.Parser.Operator.OperatorTypes.
Referenced by Yarn.Parser.Expression.Parse(), and Yarn.Parser.Expression.ShouldApplyPrecedence().
                                                            {
                return Array.IndexOf (OperatorTypes, type) != -1;
            }
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.Operator.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 1249 of file Parser.cs.
References Yarn.Parser.Operator.operatorType, and Yarn.Parser.Tab().
            {
                return Tab (indentLevel, operatorType.ToString ());
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Property Documentation
TokenType Yarn.Parser.Operator.operatorType [get], [set], [package]
Definition at line 1146 of file Parser.cs.
Referenced by Yarn.Parser.Operator.Operator(), and Yarn.Parser.Operator.PrintTree().
TokenType [] Yarn.Parser.Operator.OperatorTypes [static], [get], [package]
Definition at line 1212 of file Parser.cs.
Referenced by Yarn.Parser.Operator.InfoForOperator(), Yarn.Parser.Operator.IsOperator(), Yarn.Parser.Operator.Operator(), and Yarn.Parser.Expression.Parse().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs