Yarn.Parser.Expression Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Types
enum Type { Type.Value,
Type.FunctionCall
 }
Package Functions
Expression (ParseNode parent, ValueNode value, Parser p)
Expression (ParseNode parent, FunctionInfo function, List< Expression > parameters, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Static Package Functions
static Expression Parse (ParseNode parent, Parser p)
Package Attributes
Type type
ValueNode value
FunctionInfo function
List< Expression > parameters
ParseNode parent
int lineNumber
string[] tags = {}
Static Private Member Functions
static bool ShouldApplyPrecedence (TokenType o1, Stack< Token > operatorStack)
Detailed Description
Definition at line 748 of file Parser.cs.
Member Enumeration Documentation
enum Yarn.Parser.Expression.Type [package]
Enumerator
Value
FunctionCall
Definition at line 750 of file Parser.cs.
                               {
                Value,
                FunctionCall
            }
Constructor & Destructor Documentation
Yarn.Parser.Expression.Expression (ParseNode parent, ValueNode value, Parser p) [package]
Definition at line 762 of file Parser.cs.
References Yarn.Parser.Expression.value.
Referenced by Yarn.Parser.Expression.Parse().
                                                                             : base(
      parent, p) {
                this.type = Type.Value;
                this.value = value;
            }
Yarn.Parser.Expression.Expression (ParseNode parent, FunctionInfo function, List< Expression > parameters, Parser p) [package]
Definition at line 767 of file Parser.cs.
References Yarn.Parser.Expression.parameters, and Yarn.Parser.Expression.type.
                                                                                                           
           : base(parent, p) {
                type = Type.FunctionCall;
                this.function = function;
                this.parameters = parameters;
            }
Member Function Documentation
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 101 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
static Expression Yarn.Parser.Expression.Parse (ParseNode parent, Parser p) [static], [package]
Definition at line 773 of file Parser.cs.
References Yarn.Parser.Expression.Expression(), Yarn.Function(), Yarn.Parser.Operator.IsOperator(), Yarn.FunctionInfo.IsParameterCountCorrect(), Yarn.Parser.library, Yarn.Parser.NextSymbolIs(), Yarn.Parser.Operator.OperatorTypes, Yarn.Parser.Expression.parameters, Yarn.Parser.Expression.ShouldApplyPrecedence(), Yarn.String, Yarn.Parser.tokens, and Yarn.Token.type.
                                                                         {
                // Applies Djikstra's "shunting-yard" algorithm to convert the
                // stream of infix expressions into postfix notation; we then
                // build a tree of expressions from the result
                // https://en.wikipedia.org/wiki/Shunting-yard_algorithm
                Queue<Token> _expressionRPN = new Queue<Token> ();
                var operatorStack = new Stack<Token>();
                // used for keeping count of parameters for each function
                var functionStack = new Stack<Token> ();
                var allValidTokenTypes = new List<TokenType>(
      Operator.OperatorTypes);
                allValidTokenTypes.Add(TokenType.Number);
                allValidTokenTypes.Add(TokenType.Variable);
                allValidTokenTypes.Add(TokenType.String);
                allValidTokenTypes.Add(TokenType.LeftParen);
                allValidTokenTypes.Add(TokenType.RightParen);
                allValidTokenTypes.Add(TokenType.Identifier);
                allValidTokenTypes.Add(TokenType.Comma);
                allValidTokenTypes.Add(TokenType.True);
                allValidTokenTypes.Add(TokenType.False);
                allValidTokenTypes.Add(TokenType.Null);
                Token lastToken = null;
                // Read all the contents of the expression
                while (p.tokens.Count > 0 && p.NextSymbolIs(allValidTokenTypes.ToArray())) {
                    Token nextToken = p.ExpectSymbol(allValidTokenTypes.ToArray());
                    if (nextToken.type == TokenType.Number ||
                        nextToken.type == TokenType.Variable ||
                        nextToken.type == TokenType.String ||
                        nextToken.type == TokenType.True ||
                        nextToken.type == TokenType.False ||
                        nextToken.type == TokenType.Null) {
                        // Primitive values go straight onto the output
                        _expressionRPN.Enqueue (nextToken);
                    } else if (nextToken.type == TokenType.Identifier) {
                        operatorStack.Push (nextToken);
                        functionStack.Push (nextToken);
                        // next token must be a left paren, so process that immediately
                        nextToken = p.ExpectSymbol (TokenType.LeftParen);
                        // enter that sub-expression
                        operatorStack.Push (nextToken);
                    } else if (nextToken.type == TokenType.Comma) {
                        // Resolve this sub-expression before moving on to the
                        // next parameter
                        try {
                            // pop operators until we reach a left paren
                            while (operatorStack.Peek().type != TokenType.LeftParen) {
                                _expressionRPN.Enqueue(operatorStack.Pop());
                            }
                        } catch (InvalidOperationException) {
                            // we reached the end of the stack prematurely
                            // this means unbalanced parens!
                            throw ParseException.Make(nextToken, "Error parsing expression: " +
                                "unbalanced parentheses");
                        }
                        // We expect the top of the stack to now contain the left paren that
                        // began the list of parameters
                        if (operatorStack.Peek().type != TokenType.LeftParen) {
                            throw ParseException.Make (operatorStack.Peek (), "Expression parser got " +
                                "confused dealing with a function");
                        }
                        // The next token is not allowed to be a right-paren or a comma
                        // (that is, you can't say "foo(2,,)")
                        if (p.NextSymbolIs(TokenType.RightParen,
      TokenType.Comma)) {
                            throw ParseException.Make (p.tokens.Peek(), "Expected expression");
                        }
                        // Find the closest function on the stack
                        // and increment the number of parameters
                        functionStack.Peek().parameterCount++;
                    } else if (Operator.IsOperator(nextToken.type)) {
                        // This is an operator
                        // If this is a Minus, we need to determine if it's a
                        // unary minus or a binary minus.
                        // Unary minus looks like this: "-1"
                        // Binary minus looks like this: "2 - 3"
                        // Things get complex when we say stuff like "1 + -1".
                        // But it's easier when we realise that a minus
                        // is ONLY unary when the last token was a left paren,
                        // an operator, or it's the first token.
                        if (nextToken.type == TokenType.Minus) {
                            if (lastToken == null ||
                                lastToken.type == TokenType.LeftParen ||
                                Operator.IsOperator(lastToken.type)) {
                                // This is actually a unary minus.
                                nextToken.type = TokenType.UnaryMinus;
                            }
                        }
                        // We cannot assign values inside an expression. That is,
                        // saying "$foo = 2" in an express does not assign $foo to 2
                        // and then evaluate to 2. Instead, Yarn defines this
                        // to mean "$foo == 2"
                        if (nextToken.type == TokenType.EqualToOrAssign) {
                            nextToken.type = TokenType.EqualTo;
                        }
                        // O1 = this operator
                        // O2 = the token at the top of the stack
                        // While O2 is an operator, and EITHER: 1. O1 is left-associative and
                        // has precedence <= O2, or 2. O1 is right-associative and
                        // has precedence > O2:
                        while (ShouldApplyPrecedence(nextToken.type, operatorStack)) {
                            var o = operatorStack.Pop();
                            _expressionRPN.Enqueue(o);
                        }
                        operatorStack.Push(nextToken);
                    } else if (nextToken.type == TokenType.LeftParen) {
                        // Record that we have entered a paren-delimited
                        // subexpression
                        operatorStack.Push(nextToken);
                    } else if (nextToken.type == TokenType.RightParen) {
                        // We're leaving a subexpression; time to resolve the
                        // order of operations that we saw in between the parens.
                        try {
                            // pop operators until we reach a left paren
                            while (operatorStack.Peek().type != TokenType.LeftParen) {
                                _expressionRPN.Enqueue(operatorStack.Pop());
                            }
                            // pop the left paren
                            operatorStack.Pop();
                        } catch (InvalidOperationException) {
                            // we reached the end of the stack prematurely
                            // this means unbalanced parens!
                            throw ParseException.Make(nextToken, "Error parsing expression: unbalanced
       parentheses");
                        }
                        if (operatorStack.Peek().type == TokenType.Identifier) {
                            // This whole paren-delimited subexpression is actually
                            // a function call
                            // If the last token was a left-paren, then this
                            // was a function with no parameters; otherwise, we
                            // have an additional parameter (on top of the ones we counted
                            // while encountering commas)
                            if (lastToken.type != TokenType.LeftParen) {
                                functionStack.Peek ().parameterCount++;
                            }
                            _expressionRPN.Enqueue(operatorStack.Pop());
                            functionStack.Pop ();
                        }
                    }
                    // Record this as the last token we saw; we'll use
                    // this to figure out if minuses are unary or not
                    lastToken = nextToken;
                }
                // No more tokens; pop all operators onto the output queue
                while (operatorStack.Count > 0) {
                    _expressionRPN.Enqueue(operatorStack.Pop());
                }
                // If the output queue is empty, then this is not an expression
                if (_expressionRPN.Count == 0) {
                    throw new ParseException ("Error parsing expression: no expression found!");
                }
                // We've now got this in more easily parsed RPN form;
                // time to build the expression tree.
                Token firstToken = _expressionRPN.Peek();
                var evaluationStack = new Stack<Expression>();
                while (_expressionRPN.Count > 0) {
                    var next = _expressionRPN.Dequeue();
                    if (Operator.IsOperator(next.type)) {
                        // This is an operation
                        var info = Operator.InfoForOperator(next.type);
                        if (evaluationStack.Count < info.arguments) {
                            throw ParseException.Make(next, "Error parsing expression: not enough " +
                                "arguments for operator "+next.type.ToString());
                        }
                        var parameters = new List<Expression> ();
                        for (int i = 0; i < info.arguments; i++) {
                            parameters.Add (evaluationStack.Pop ());
                        }
                        parameters.Reverse ();
                        var operatorFunc = p.library.GetFunction (next.type.ToString());
                        var expr = new Expression (parent, operatorFunc,
      parameters, p);
                        evaluationStack.Push(expr);
                    } else if (next.type == TokenType.Identifier) {
                        // This is a function call
                        FunctionInfo info = null;
                        // If we have a library, use it to check if the
                        // number of parameters provided is correct
                        if (p.library != null) {
                            info = p.library.GetFunction(next.value as String);
                            // Ensure that this call has the right number of params
                            if (info.IsParameterCountCorrect(next.parameterCount) == false) {
                                string error = string.Format(CultureInfo.CurrentCulture, "Error parsing
       expression: " +
                                    "Unsupported number of parameters for function {0} (expected {1}, got
       {2})",
                                    next.value as String,
                                    info.paramCount,
                                    next.parameterCount
                                );
                                throw ParseException.Make(next, error);
                            }
                        } else {
                            // Use a dummy FunctionInfo to represent info about the
                            // fact that a function is called; note that
                            // attempting to call this will fail
                            info = new FunctionInfo (next.value, next.parameterCount, (
      Function)null);
                        }
                        var parameterList = new List<Expression> ();
                        for (int i = 0; i < next.parameterCount; i++) {
                            parameterList.Add (evaluationStack.Pop());
                        }
                        parameterList.Reverse ();
                        var expr = new Expression (parent, info, parameterList, p);
                        evaluationStack.Push (expr);
                    } else {
                        // This is a raw value
                        var v = new ValueNode(parent, next, p);
                        Expression expr = new Expression(
      parent, v, p);
                        evaluationStack.Push(expr);
                    }
                }
                // We should now have a single expression in this stack, which is the root
                // of the expression's tree. If we have more than one, then we have a problem.
                if (evaluationStack.Count != 1) {
                    throw ParseException.Make(firstToken, "Error parsing expression " +
                        "(stack did not reduce correctly)");
                }
                // Return it
                return evaluationStack.Pop ();
            }
override string Yarn.Parser.Expression.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 1074 of file Parser.cs.
References Yarn.Parser.Expression.parameters, Yarn.Parser.Tab(), and Yarn.Parser.Expression.type.
            {
                var stringBuilder = new StringBuilder ();
                switch (type) {
                case Type.Value:
                    return value.PrintTree (indentLevel);
                case Type.FunctionCall:
                    if (parameters.Count == 0) {
                        stringBuilder.Append(Tab(indentLevel, "Function call to " + function.name + "
       (no parameters)"));
                    } else {
                        stringBuilder.Append(Tab(indentLevel, "Function call to " + function.name + " ("
       +parameters.Count+" parameters) {"));
                        foreach (var param in parameters) {
                            stringBuilder.Append(param.PrintTree(indentLevel+1));
                        }
                        stringBuilder.Append(Tab(indentLevel, "}"));
                    }
                    return stringBuilder.ToString();
                }
                return Tab(indentLevel, "<error printing expression!>");
            }
static bool Yarn.Parser.Expression.ShouldApplyPrecedence (TokenType o1, Stack< Token > operatorStack) [static], [private]
Definition at line 1047 of file Parser.cs.
References Yarn.Parser.Operator.IsOperator(), and Yarn.Parser.Expression.type.
Referenced by Yarn.Parser.Expression.Parse().
                                                                                                {
                if (operatorStack.Count == 0) {
                    return false;
                }
                if (Operator.IsOperator (o1) == false) {
                    throw new ParseException ("Internal error parsing expression");
                }
                TokenType o2 = operatorStack.Peek ().type;
                if (Operator.IsOperator (o2) == false)
                    return false;
                var o1Info = Operator.InfoForOperator (o1);
                var o2Info = Operator.InfoForOperator (o2);
                if (o1Info.associativity == Operator.Associativity.Left && o1Info.precedence <= o2Info.
      precedence) {
                    return true;
                }
                if (o1Info.associativity == Operator.Associativity.Right && o1Info.precedence < o2Info.
      precedence) {
                    return true;
                }
                return false;
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 79 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 95 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
FunctionInfo Yarn.Parser.Expression.function [package]
Definition at line 759 of file Parser.cs.
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 62 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
List<Expression> Yarn.Parser.Expression.parameters [package]
Definition at line 760 of file Parser.cs.
Referenced by Yarn.Parser.Expression.Expression(), Yarn.Parser.Expression.Parse(), and Yarn.Parser.Expression.PrintTree().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 59 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 77 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Type Yarn.Parser.Expression.type [package]
Definition at line 755 of file Parser.cs.
Referenced by Yarn.Parser.Expression.Expression(), Yarn.Parser.Expression.PrintTree(), and Yarn.Parser.Expression.ShouldApplyPrecedence().
ValueNode Yarn.Parser.Expression.value [package]
Definition at line 757 of file Parser.cs.
Referenced by Yarn.Parser.Expression.Expression().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs