Yarn.YarnSpinnerConsole Class Reference
Classes
class ConsoleRunnerImplementation
Static Public Member Functions
static void Error (params string[] messages)
static void Note (params string[] messages)
static void Warn (params string[] messages)
static void Main (string[] args)
Static Package Functions
static Dialogue CreateDialogueForUtilities ()
static void CheckFileList (IList< string > paths, List< string > allowedExtensions)
static Dialogue CreateDialogue (ExecutionOptions options, ConsoleRunnerImplementation impl)
Static Package Attributes
static List< string > ALLOWED_EXTENSIONS = new List<string>(new string[] { `.json`, `.node`, `.yarn.bytes`, `.yarn.txt` })
Static Private Member Functions
static int Run (RunOptions options)
static int Verify (VerifyOptions options)
Detailed Description
Definition at line 142 of file Main.cs.
Member Function Documentation
static void Yarn.YarnSpinnerConsole.CheckFileList (IList< string > paths, List< string > allowedExtensions) [static], [package]
Definition at line 206 of file Main.cs.
References Yarn.YarnSpinnerConsole.Error(), and Yarn.YarnSpinnerConsole.Warn().
Referenced by Yarn.YarnSpinnerConsole.Run(), and Yarn.YarnSpinnerConsole.Verify().
        {
            if (paths.Count == 0)
            {
                Warn("No files provided.");
                return;
            }
            var invalid = new List<string>();
            foreach (var path in paths)
            {
                // Does this file exist?
                var exists = System.IO.File.Exists(path);
                // Does this file have the right extension?
                var hasAllowedExtension = allowedExtensions.FindIndex(item => path.EndsWith(item,
      StringComparison.InvariantCulture)) != -1;
                if (!exists || !hasAllowedExtension)
                {
                    invalid.Add(string.Format(CultureInfo.CurrentCulture, "\"{0}\"", path));
                }
            }
            if (invalid.Count != 0)
            {
                var message = string.Format(CultureInfo.CurrentCulture, "The file{0} {1} {2}.",
                    invalid.Count == 1 ? "" : "s",
                                            string.Join(", ", invalid.ToArray()),
                    invalid.Count == 1 ? "is not valid" : "are not valid"
                );
                Error(message);
            }
        }
static Dialogue Yarn.YarnSpinnerConsole.CreateDialogue (ExecutionOptions options, ConsoleRunnerImplementation impl) [static], [package]
Definition at line 388 of file Main.cs.
References Yarn.Value.AsBool, Yarn.YarnSpinnerConsole.Error(), Yarn.ExecutionOptions.experimental, Yarn.YarnSpinnerConsole.Note(), Yarn.BaseOptions.showDebuggingInfo, and Yarn.YarnSpinnerConsole.Warn().
Referenced by Yarn.YarnSpinnerConsole.Run(), and Yarn.YarnSpinnerConsole.Verify().
        {
            // Load nodes
            var dialogue = new Dialogue(impl);
            if (options.experimental)
            {
                Warn("Running YarnSpinner in experimental mode may have unexpected behaviour.");
                dialogue.experimentalMode = true;
            }
            // Add some methods for testing
            dialogue.library.RegisterFunction("add_three_operands", 3, delegate (Value[] parameters)
            {
                return parameters[0] + parameters[1] + parameters[2];
            });
            dialogue.library.RegisterFunction("last_value", -1, delegate (Value[] parameters)
            {
                // return the last value
                return parameters[parameters.Length - 1];
            });
            dialogue.library.RegisterFunction("is_even", 1, delegate (Value[] parameters)
            {
                return (int)parameters[0].AsNumber % 2 == 0;
            });
            // Register the "assert" function, which stops execution if its parameter evaluates to false
            dialogue.library.RegisterFunction("assert", -1, delegate (Value[] parameters)
            {
                if (parameters[0].AsBool == false)
                {
                    // TODO: Include file, node and line number
                    if (parameters.Length > 1 && parameters[1].AsBool)
                    {
                        dialogue.LogErrorMessage("ASSERTION FAILED: " + parameters[1].AsString);
                    }
                    else
                    {
                        dialogue.LogErrorMessage("ASSERTION FAILED");
                    }
                    Environment.Exit(1);
                }
            });
            // Register a function to let test scripts register how many
            // options they expect to send
            dialogue.library.RegisterFunction("prepare_for_options", 2, delegate (Value[] parameters)
            {
                impl.numberOfExpectedOptions = (int)parameters[0].AsNumber;
                impl.autoSelectOptionNumber = (int)parameters[1].AsNumber;
            });
            dialogue.library.RegisterFunction("expect_line", 1, delegate (Value[] parameters)
            {
                impl.expectedNextLine = parameters[0].AsString;
            });
            dialogue.library.RegisterFunction("expect_command", 1, delegate (Value[] parameters)
            {
                impl.expectedNextCommand = parameters[0].AsString;
            });
            // If debugging is enabled, log debug messages; otherwise, ignore them
            if (options.showDebuggingInfo)
            {
                dialogue.LogDebugMessage = delegate (string message)
                {
                    Note(message);
                };
            }
            else
            {
                dialogue.LogDebugMessage = delegate (string message) { };
            }
            dialogue.LogErrorMessage = delegate (string message)
            {
                Warn("Yarn Error: " + message);
            };
            foreach (var file in options.files)
            {
                try
                {
                    dialogue.LoadFile(file, false, false, options.onlyConsiderNode);
                }
                catch (Yarn.TokeniserException e)
                {
                    Warn(e.Message);
                }
                catch (Yarn.ParseException e)
                {
                    Warn(e.Message);
                }
            }
            // Load string table
            if (options.stringTable != null)
            {
                var parsedTable = new Dictionary<string, string>();
                using (var reader = new System.IO.StreamReader(options.stringTable))
                {
                    using (var csvReader = new CsvReader(reader))
                    {
                        if (csvReader.ReadHeader() == false)
                        {
                            Error(string.Format(CultureInfo.CurrentCulture, "{0} is not a valid string
       table", options.stringTable));
                        }
                        foreach (var row in csvReader.GetRecords<LocalisedLine>())
                        {
                            parsedTable[row.LineCode] = row.LineText;
                        }
                    }
                }
                dialogue.AddStringTable(parsedTable);
            }
            return dialogue;
        }
static Dialogue Yarn.YarnSpinnerConsole.CreateDialogueForUtilities () [static], [package]
Definition at line 145 of file Main.cs.
        {
            // Note that we're passing in with a null library - this means
            // that all function checking will be disabled, and missing funcs
            // will not cause a compile error. If a func IS missing at runtime,
            // THAT will throw an exception.
            // We do this because this tool has no idea about any of the custom
            // functions that you might be using.
            Dialogue d = new Dialogue(null);
            // Debug logging goes to Note
            d.LogDebugMessage = message => YarnSpinnerConsole.Note(message);
            // When erroring, call Warn, not Error, which terminates the program
            d.LogErrorMessage = message => YarnSpinnerConsole.Warn(message);
            return d;
        }
static void Yarn.YarnSpinnerConsole.Error (params string[] messages) [static]
Definition at line 167 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.CheckFileList(), Yarn.YarnSpinnerConsole.CreateDialogue(), Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.HandleErrorMessage(), Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunCommand(), Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunLine(), Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunOptions(), and Yarn.YarnSpinnerConsole.Verify().
        {
            foreach (var message in messages)
            {
                Console.ForegroundColor = ConsoleColor.DarkRed;
                Console.Write("Error: ");
                Console.ResetColor();
                Console.WriteLine(message);
            }
            Environment.Exit(1);
        }
static void Yarn.YarnSpinnerConsole.Main (string[] args) [static]
Definition at line 244 of file Main.cs.
References Yarn.LineAdder.AddLines(), Yarn.FileFormatConverter.ConvertFormat(), Yarn.ProgramExporter.Export(), Yarn.TableGenerator.GenerateTables(), Yarn.YarnSpinnerConsole.Run(), and Yarn.YarnSpinnerConsole.Verify().
        {
            // Read and dispatch the appropriate command
            var results = CommandLine.Parser.Default.ParseArguments
            <
            RunOptions,
            VerifyOptions,
            CompileOptions,
            GenerateTableOptions,
            AddLabelsOptions,
            ConvertFormatOptions
            >(args);
            var returnCode = results.MapResult(
                (RunOptions options) => Run(options),
                (VerifyOptions options) => Verify(options),
                (CompileOptions options) => ProgramExporter.Export(options),
                (AddLabelsOptions options) => LineAdder.AddLines(options),
                (GenerateTableOptions options) => TableGenerator.GenerateTables(options),
                (ConvertFormatOptions options) => FileFormatConverter.ConvertFormat(options),
                errors => { return 1; });
            Environment.Exit(returnCode);
        }
static void Yarn.YarnSpinnerConsole.Note (params string[] messages) [static]
Definition at line 181 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.CreateDialogue(), Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.HandleDebugMessage(), Yarn.YarnSpinnerConsole.ConsoleRunnerImplementation.RunOptions(), and Yarn.YarnSpinnerConsole.Verify().
        {
            foreach (var message in messages)
            {
                Console.ForegroundColor = ConsoleColor.DarkBlue;
                Console.Write("Note: ");
                Console.ResetColor();
                Console.WriteLine(message);
            }
        }
static int Yarn.YarnSpinnerConsole.Run (RunOptions options) [static], [private]
Definition at line 275 of file Main.cs.
References Yarn.YarnSpinnerConsole.ALLOWED_EXTENSIONS, Yarn.YarnSpinnerConsole.CheckFileList(), Yarn.YarnSpinnerConsole.CreateDialogue(), Yarn.BaseOptions.files, Yarn.Dialogue.Run(), Yarn.RunOptions.waitForInput, and Yarn.YarnSpinnerConsole.Warn().
Referenced by Yarn.YarnSpinnerConsole.Main().
        {
            CheckFileList(options.files, ALLOWED_EXTENSIONS);
            // Create the object that handles callbacks
            var impl = new ConsoleRunnerImplementation(waitForLines: options.waitForInput);
            // load the default variables we got on the command line
            foreach (var variable in options.variables)
            {
                var entry = variable.Split(new char[] { '=' }, StringSplitOptions.RemoveEmptyEntries);
                float value;
                // If there aren't two parts to this or the second part isn't a float, fail
                if (entry.Length != 2 || float.TryParse(entry[1], out value) == false)
                {
                    Warn(string.Format(CultureInfo.CurrentCulture, "Skipping invalid variable {0}",
      variable));
                    continue;
                }
                var name = entry[0];
                impl.SetNumber(name, value);
            }
            if (options.automaticallySelectFirstOption == true)
            {
                impl.autoSelectFirstOption = true;
            }
            Dialogue dialogue = CreateDialogue(options, impl);
            // Run the conversation
            for (int run = 0; run < options.runTimes; run++)
            {
                foreach (var step in dialogue.Run(options.startNode))
                {
                    // It can be one of three types: a line to show, options
                    // to present to the user, or an internal command to run
                    if (step is Dialogue.LineResult)
                    {
                        var lineResult = step as Dialogue.LineResult;
                        impl.RunLine(lineResult.line);
                    }
                    else if (step is Dialogue.OptionSetResult)
                    {
                        var optionsResult = step as Dialogue.OptionSetResult;
                        impl.RunOptions(optionsResult.options, optionsResult.setSelectedOptionDelegate);
                    }
                    else if (step is Dialogue.CommandResult)
                    {
                        var commandResult = step as Dialogue.CommandResult;
                        impl.RunCommand(commandResult.command.text);
                    }
                }
                impl.DialogueComplete();
            }
            return 0;
        }
static int Yarn.YarnSpinnerConsole.Verify (VerifyOptions options) [static], [private]
Definition at line 338 of file Main.cs.
References Yarn.YarnSpinnerConsole.ALLOWED_EXTENSIONS, Yarn.YarnSpinnerConsole.CheckFileList(), Yarn.VerifyOptions.compileAndExit, Yarn.YarnSpinnerConsole.CreateDialogue(), Yarn.YarnSpinnerConsole.Error(), Yarn.BaseOptions.files, Yarn.YarnSpinnerConsole.Note(), and Yarn.YarnSpinnerConsole.Warn().
Referenced by Yarn.YarnSpinnerConsole.Main().
        {
            CheckFileList(options.files, ALLOWED_EXTENSIONS);
            Dialogue dialogue;
            try
            {
                dialogue = CreateDialogue(options, null);
            }
#pragma warning disable CA1031 // Do not catch general exception types
            catch
            {
                return 1;
            }
#pragma warning restore CA1031 // Do not catch general exception types
            if (options.compileAndExit)
            {
                var result = dialogue.GetByteCode();
                Console.WriteLine(result);
                return 0;
            }
            var context = new Yarn.Analysis.Context();
            dialogue.Analyse(context);
            foreach (var diagnosis in context.FinishAnalysis())
            {
                switch (diagnosis.severity)
                {
                    case Analysis.Diagnosis.Severity.Error:
                        Error(diagnosis.ToString(showSeverity: false));
                        break;
                    case Analysis.Diagnosis.Severity.Warning:
                        Warn(diagnosis.ToString(showSeverity: false));
                        break;
                    case Analysis.Diagnosis.Severity.Note:
                        Note(diagnosis.ToString(showSeverity: false));
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }
            return 0;
        }
static void Yarn.YarnSpinnerConsole.Warn (params string[] messages) [static]
Definition at line 195 of file Main.cs.
Referenced by Yarn.YarnSpinnerConsole.CheckFileList(), Yarn.YarnSpinnerConsole.CreateDialogue(), Yarn.YarnSpinnerConsole.Run(), and Yarn.YarnSpinnerConsole.Verify().
        {
            foreach (var message in messages)
            {
                Console.ForegroundColor = ConsoleColor.DarkYellow;
                Console.Write("Warning: ");
                Console.ResetColor();
                Console.WriteLine(message);
            }
        }
Member Data Documentation
List<string> Yarn.YarnSpinnerConsole.ALLOWED_EXTENSIONS = new List<string>(new string[] { `.json`, `.node`, `.yarn.bytes`, `.yarn.txt` }) [static], [package]
Definition at line 273 of file Main.cs.
Referenced by Yarn.LineAdder.AddLines(), Yarn.FileFormatConverter.ConvertFormat(), Yarn.ProgramExporter.Export(), Yarn.TableGenerator.GenerateTables(), Yarn.YarnSpinnerConsole.Run(), and Yarn.YarnSpinnerConsole.Verify().
The documentation for this class was generated from the following file:
YarnSpinnerConsole/Main.cs