Yarn.ParseException Class Reference
Package Functions
ParseException (string message)
Static Package Functions
static ParseException Make (Token foundToken, params TokenType[] expectedTypes)
static ParseException Make (Token mostRecentToken, string message)
static ParseException Make (Antlr4.Runtime.ParserRuleContext context, string message)
Package Attributes
int lineNumber = 0
Detailed Description
Definition at line 11 of file Program.cs.
Constructor & Destructor Documentation
Yarn.ParseException.ParseException (string message) [package]
Definition at line 67 of file Program.cs.
Referenced by Yarn.ParseException.Make().
: base(message) { }
Member Function Documentation
static ParseException Yarn.ParseException.Make (Token foundToken, params TokenType[] expectedTypes) [static], [package]
Definition at line 16 of file Program.cs.
References Yarn.ParseException.lineNumber, and Yarn.ParseException.ParseException().
        {
            var lineNumber = foundToken.lineNumber + 1;
            var expectedTypeNames = new List<String>();
            foreach (var type in expectedTypes)
            {
                expectedTypeNames.Add(type.ToString());
            }
            string possibleValues = string.Join(",", expectedTypeNames.ToArray());
            string message = string.Format(CultureInfo.CurrentCulture, "Line {0}:{1}: Expected {2}, but
       found {3}",
                                           lineNumber,
                                           foundToken.columnNumber,
                                           possibleValues,
                                           foundToken.type.ToString()
                                           );
            var e = new ParseException(message);
            e.lineNumber = lineNumber;
            return e;
        }
static ParseException Yarn.ParseException.Make (Token mostRecentToken, string message) [static], [package]
Definition at line 39 of file Program.cs.
References Yarn.ParseException.lineNumber, and Yarn.ParseException.ParseException().
        {
            var lineNumber = mostRecentToken.lineNumber + 1;
            string theMessage = string.Format(CultureInfo.CurrentCulture, "Line {0}:{1}: {2}",
                                 lineNumber,
                                mostRecentToken.columnNumber,
                                 message);
            var e = new ParseException(theMessage);
            e.lineNumber = lineNumber;
            return e;
        }
static ParseException Yarn.ParseException.Make (Antlr4.Runtime.ParserRuleContext context, string message) [static], [package]
Definition at line 51 of file Program.cs.
References Yarn.ParseException.ParseException().
        {
            int line = context.Start.Line;
            // getting the text that has the issue inside
            int start = context.Start.StartIndex;
            int end = context.Stop.StopIndex;
            string body = context.Start.InputStream.GetText(new Antlr4.Runtime.Misc.Interval(start, end));
            string theMessage = string.Format(CultureInfo.CurrentCulture, "Error on line {0}\n{1}\n{2}",
      line,body,message);
            var e = new ParseException(theMessage);
            e.lineNumber = line;
            return e;
        }
Member Data Documentation
int Yarn.ParseException.lineNumber = 0 [package]
Definition at line 14 of file Program.cs.
Referenced by Yarn.ParseException.Make().
The documentation for this class was generated from the following file:
YarnSpinner/Program.cs