Yarn.Parser.ShortcutOption Class Reference
Public Member Functions
string TagsToString (int indentLevel)
override string ToString ()
Package Functions
ShortcutOption (int optionIndex, ParseNode parent, Parser p)
override string PrintTree (int indentLevel)
Node NodeParent ()
Package Attributes
ParseNode parent
int lineNumber
string[] tags = {}
Properties
string label [get, set]
Expression condition [get, set]
Node optionNode [get, set]
Detailed Description
Definition at line 368 of file Parser.cs.
Constructor & Destructor Documentation
Yarn.Parser.ShortcutOption.ShortcutOption (int optionIndex, ParseNode parent, Parser p) [package]
Definition at line 373 of file Parser.cs.
References Yarn.Parser.ShortcutOption.condition, Yarn.Parser.ShortcutOption.label, Yarn.Parser.NextSymbolIs(), Yarn.Parser.NextSymbolsAre(), Yarn.Parser.ParseNode.NodeParent(), Yarn.Parser.ShortcutOption.optionNode, and Yarn.Parser.ParseNode.tags.
                                                                                 : base(
      parent, p) {
                p.ExpectSymbol(TokenType.ShortcutOption);
                label = p.ExpectSymbol(TokenType.Text).value as string;
                // Parse the conditional ("<<if $foo>>") if it's there
                var tags = new List<string>();
                while (
                    p.NextSymbolsAre(TokenType.BeginCommand, TokenType.If) ||
                    p.NextSymbolIs(TokenType.TagMarker)) {
                    if (p.NextSymbolsAre(TokenType.BeginCommand,
      TokenType.If)) {
                        p.ExpectSymbol(TokenType.BeginCommand);
                        p.ExpectSymbol(TokenType.If);
                        condition = Expression.Parse(this, p);
                        p.ExpectSymbol(TokenType.EndCommand);
                    } else if (p.NextSymbolIs(TokenType.TagMarker)) {
                        p.ExpectSymbol(TokenType.TagMarker);
                        var tag = p.ExpectSymbol(TokenType.Identifier).value;
                        tags.Add(tag);
                    }
                }
                this.tags = tags.ToArray();
                // Parse the statements belonging to this option if it has any
                if (p.NextSymbolIs(TokenType.Indent)) {
                    p.ExpectSymbol(TokenType.Indent);
                    optionNode = new Node(NodeParent().name + "." + optionIndex, this,
      p);
                    p.ExpectSymbol(TokenType.Dedent);
                }
            }
Member Function Documentation
Node Yarn.Parser.ParseNode.NodeParent () [package], [inherited]
Definition at line 100 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption().
                                       {
                var node = this;
                do {
                    if (node is Node) {
                        return node as Node;
                    }
                    node = node.parent;
                } while (node
                    != null);
                return null;
            }
override string Yarn.Parser.ShortcutOption.PrintTree (int indentLevel) [package], [virtual]
Implements Yarn.Parser.ParseNode.
Definition at line 409 of file Parser.cs.
References Yarn.Parser.ShortcutOption.condition, Yarn.Parser.ShortcutOption.label, Yarn.Parser.ShortcutOption.optionNode, Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.TagsToString().
            {
                var sb = new StringBuilder ();
                sb.Append (Tab (indentLevel, "Option \"" +label + "\""));
                if (condition != null) {
                    sb.Append (Tab (indentLevel + 1, "(when:"));
                    sb.Append (condition.PrintTree(indentLevel+2));
                    sb.Append (Tab (indentLevel + 1, "),"));
                }
                if (optionNode != null) {
                    sb.Append (Tab (indentLevel, "{"));
                    sb.Append (optionNode.PrintTree (indentLevel + 1));
                    sb.Append (Tab (indentLevel, "}"));
                }
                sb.Append (TagsToString (indentLevel));
                return sb.ToString ();
            }
string Yarn.Parser.ParseNode.TagsToString (int indentLevel) [inherited]
Definition at line 78 of file Parser.cs.
References Yarn.Parser.Tab(), and Yarn.Parser.ParseNode.tags.
Referenced by Yarn.Parser.Statement.PrintTree(), and Yarn.Parser.ShortcutOption.PrintTree().
            {
                if (tags.Length > 0) {
                    var s = new StringBuilder ();
                    s.Append (Tab (indentLevel + 1, "Tags:"));
                    foreach (var tag in this.tags) {
                        s.Append(Tab (indentLevel + 2, "#" + tag));
                    }
                    return s.ToString ();
                } else {
                    return "";
                }
            }
override string Yarn.Parser.ParseNode.ToString () [inherited]
Definition at line 94 of file Parser.cs.
            {
                return this.GetType ().Name;
            }
Member Data Documentation
int Yarn.Parser.ParseNode.lineNumber [package], [inherited]
Definition at line 61 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
ParseNode Yarn.Parser.ParseNode.parent [package], [inherited]
Definition at line 58 of file Parser.cs.
Referenced by Yarn.Parser.ParseNode.ParseNode().
string [] Yarn.Parser.ParseNode.tags = {} [package], [inherited]
Definition at line 76 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.ShortcutOption(), Yarn.Parser.Statement.Statement(), and Yarn.Parser.ParseNode.TagsToString().
Property Documentation
Expression Yarn.Parser.ShortcutOption.condition [get], [set], [package]
Definition at line 370 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.PrintTree(), and Yarn.Parser.ShortcutOption.ShortcutOption().
string Yarn.Parser.ShortcutOption.label [get], [set], [package]
Definition at line 369 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.PrintTree(), and Yarn.Parser.ShortcutOption.ShortcutOption().
Node Yarn.Parser.ShortcutOption.optionNode [get], [set], [package]
Definition at line 371 of file Parser.cs.
Referenced by Yarn.Parser.ShortcutOption.PrintTree(), and Yarn.Parser.ShortcutOption.ShortcutOption().
The documentation for this class was generated from the following file:
YarnSpinner/Parser.cs