Yarn.Library Class Reference
Public Member Functions
FunctionInfo GetFunction (string name)
void ImportLibrary (Library otherLibrary)
void RegisterFunction (FunctionInfo function)
void RegisterFunction (string name, int parameterCount, ReturningFunction implementation)
void RegisterFunction (string name, int parameterCount, Function implementation)
bool FunctionExists (string name)
void DeregisterFunction (string name)
Private Attributes
Dictionary< string, FunctionInfo > functions = new Dictionary<string, FunctionInfo>()
Detailed Description
Definition at line 90 of file Library.cs.
Member Function Documentation
void Yarn.Library.DeregisterFunction (string name)
Definition at line 132 of file Library.cs.
References Yarn.Library.functions.
                                                    {
            if (functions.ContainsKey(name))
                functions.Remove (name);
        }
bool Yarn.Library.FunctionExists (string name)
Definition at line 128 of file Library.cs.
                                                {
            return functions.ContainsKey (name);
        }
FunctionInfo Yarn.Library.GetFunction (string name)
Definition at line 97 of file Library.cs.
References Yarn.Library.functions.
Referenced by Yarn.VirtualMachine.RunInstruction().
                                                     {
            try {
                return functions [name];
            } catch (KeyNotFoundException) {
                throw new InvalidOperationException (name + " is not a valid function");
            }
        }
void Yarn.Library.ImportLibrary (Library otherLibrary)
Definition at line 108 of file Library.cs.
References Yarn.Library.functions.
                                                        {
            foreach (var entry in otherLibrary.functions) {
                functions [entry.Key] = entry.Value;
            }
        }
void Yarn.Library.RegisterFunction (FunctionInfo function)
Definition at line 114 of file Library.cs.
References Yarn.Library.functions.
Referenced by Yarn.Library.RegisterFunction().
                                                            {
            functions [function.name] = function;
        }
void Yarn.Library.RegisterFunction (string name, int parameterCount, ReturningFunction implementation)
Definition at line 118 of file Library.cs.
References Yarn.Library.RegisterFunction().
                                                                                                        {
            var info = new FunctionInfo (name, parameterCount, implementation);
            RegisterFunction (info);
        }
void Yarn.Library.RegisterFunction (string name, int parameterCount, Function implementation)
Definition at line 123 of file Library.cs.
References Yarn.Library.RegisterFunction().
                                                                                               {
            var info = new FunctionInfo (name, parameterCount, implementation);
            RegisterFunction (info);
        }
Member Data Documentation
Dictionary<string, FunctionInfo> Yarn.Library.functions = new Dictionary<string, FunctionInfo>() [private]
Definition at line 93 of file Library.cs.
Referenced by Yarn.Library.DeregisterFunction(), Yarn.Library.GetFunction(), Yarn.Library.ImportLibrary(), and Yarn.Library.RegisterFunction().
The documentation for this class was generated from the following file:
YarnSpinner/Library.cs