preprocessor Namespace Reference
Variables
list output_lines = []
list indents = [(0,False)]
shouldTrackNextIndentation = False
string INDENT = '\a'
string DEDENT = '\v'
string OPTION = `->`
int line_count = 1
tuple tweaked_line = line.replace('\t',' ')
tuple thisIndentation = len(tweaked_line)
tuple is_option = tweaked_line.strip()
list previousIndentation = indents[-1]
tuple topLevel = indents.pop()
tuple output = open('processed.yarn', 'w')
Variable Documentation
string preprocessor.DEDENT = '\v'
Definition at line 28 of file preprocessor.py.
Referenced by Yarn.Loader.preprocessor().
string preprocessor.INDENT = '\a'
Definition at line 27 of file preprocessor.py.
Referenced by Yarn.Loader.preprocessor().
list preprocessor.indents = [(0,False)]
Definition at line 20 of file preprocessor.py.
Referenced by Yarn.Loader.preprocessor().
tuple preprocessor.is_option = tweaked_line.strip()
Definition at line 50 of file preprocessor.py.
int preprocessor.line_count = 1
Definition at line 38 of file preprocessor.py.
string preprocessor.OPTION = `->`
Definition at line 35 of file preprocessor.py.
Referenced by Yarn.Loader.preprocessor().
tuple preprocessor.output = open('processed.yarn', 'w')
Definition at line 92 of file preprocessor.py.
Referenced by Yarn.Graph.toDot(), and Yarn.BodyVisitor.VisitFunction_statement().
list preprocessor.output_lines = []
Definition at line 16 of file preprocessor.py.
list preprocessor.previousIndentation = indents[-1]
Definition at line 52 of file preprocessor.py.
Referenced by Yarn.Lexer.TokeniseLine().
preprocessor.shouldTrackNextIndentation = False
Definition at line 22 of file preprocessor.py.
Referenced by Yarn.Loader.preprocessor().
tuple preprocessor.thisIndentation = len(tweaked_line)
Definition at line 47 of file preprocessor.py.
Referenced by Yarn.Lexer.TokeniseLine().
tuple preprocessor.topLevel = indents.pop()
Definition at line 70 of file preprocessor.py.
Referenced by Yarn.Loader.preprocessor(), and Yarn.Lexer.TokeniseLine().
tuple preprocessor.tweaked_line = line.replace('\t',' ')
Definition at line 42 of file preprocessor.py.