//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/desplesda/Work/yarnspinner/YarnSpinner.Compiler/Upgrader/Upgraders/V1toV2/YarnSpinnerV1Parser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Yarn.Compiler {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="YarnSpinnerV1Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IYarnSpinnerV1ParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.dialogue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDialogue([NotNull] YarnSpinnerV1Parser.DialogueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.dialogue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDialogue([NotNull] YarnSpinnerV1Parser.DialogueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.file_hashtag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile_hashtag([NotNull] YarnSpinnerV1Parser.File_hashtagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.file_hashtag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile_hashtag([NotNull] YarnSpinnerV1Parser.File_hashtagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNode([NotNull] YarnSpinnerV1Parser.NodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNode([NotNull] YarnSpinnerV1Parser.NodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader([NotNull] YarnSpinnerV1Parser.HeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader([NotNull] YarnSpinnerV1Parser.HeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] YarnSpinnerV1Parser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] YarnSpinnerV1Parser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] YarnSpinnerV1Parser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] YarnSpinnerV1Parser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.line_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_statement([NotNull] YarnSpinnerV1Parser.Line_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.line_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_statement([NotNull] YarnSpinnerV1Parser.Line_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.line_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_formatted_text([NotNull] YarnSpinnerV1Parser.Line_formatted_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.line_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_formatted_text([NotNull] YarnSpinnerV1Parser.Line_formatted_textContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.format_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormat_function([NotNull] YarnSpinnerV1Parser.Format_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.format_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormat_function([NotNull] YarnSpinnerV1Parser.Format_functionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>KeyValuePairNamed</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.key_value_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValuePairNamed([NotNull] YarnSpinnerV1Parser.KeyValuePairNamedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>KeyValuePairNamed</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.key_value_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValuePairNamed([NotNull] YarnSpinnerV1Parser.KeyValuePairNamedContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>KeyValuePairNumber</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.key_value_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValuePairNumber([NotNull] YarnSpinnerV1Parser.KeyValuePairNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>KeyValuePairNumber</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.key_value_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValuePairNumber([NotNull] YarnSpinnerV1Parser.KeyValuePairNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.hashtag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHashtag([NotNull] YarnSpinnerV1Parser.HashtagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.hashtag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHashtag([NotNull] YarnSpinnerV1Parser.HashtagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.line_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_condition([NotNull] YarnSpinnerV1Parser.Line_conditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.line_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_condition([NotNull] YarnSpinnerV1Parser.Line_conditionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expParens</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpParens([NotNull] YarnSpinnerV1Parser.ExpParensContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expParens</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpParens([NotNull] YarnSpinnerV1Parser.ExpParensContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expMultDivMod</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpMultDivMod([NotNull] YarnSpinnerV1Parser.ExpMultDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expMultDivMod</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpMultDivMod([NotNull] YarnSpinnerV1Parser.ExpMultDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expMultDivModEquals</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpMultDivModEquals([NotNull] YarnSpinnerV1Parser.ExpMultDivModEqualsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expMultDivModEquals</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpMultDivModEquals([NotNull] YarnSpinnerV1Parser.ExpMultDivModEqualsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expComparison</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpComparison([NotNull] YarnSpinnerV1Parser.ExpComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expComparison</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpComparison([NotNull] YarnSpinnerV1Parser.ExpComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expNegative</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpNegative([NotNull] YarnSpinnerV1Parser.ExpNegativeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expNegative</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpNegative([NotNull] YarnSpinnerV1Parser.ExpNegativeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expAndOrXor</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpAndOrXor([NotNull] YarnSpinnerV1Parser.ExpAndOrXorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expAndOrXor</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpAndOrXor([NotNull] YarnSpinnerV1Parser.ExpAndOrXorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expPlusMinusEquals</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpPlusMinusEquals([NotNull] YarnSpinnerV1Parser.ExpPlusMinusEqualsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expPlusMinusEquals</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpPlusMinusEquals([NotNull] YarnSpinnerV1Parser.ExpPlusMinusEqualsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expAddSub</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpAddSub([NotNull] YarnSpinnerV1Parser.ExpAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expAddSub</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpAddSub([NotNull] YarnSpinnerV1Parser.ExpAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expNot</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpNot([NotNull] YarnSpinnerV1Parser.ExpNotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expNot</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpNot([NotNull] YarnSpinnerV1Parser.ExpNotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expValue</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpValue([NotNull] YarnSpinnerV1Parser.ExpValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expValue</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpValue([NotNull] YarnSpinnerV1Parser.ExpValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>expEquality</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpEquality([NotNull] YarnSpinnerV1Parser.ExpEqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>expEquality</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpEquality([NotNull] YarnSpinnerV1Parser.ExpEqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueNumber([NotNull] YarnSpinnerV1Parser.ValueNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueNumber([NotNull] YarnSpinnerV1Parser.ValueNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueTrue([NotNull] YarnSpinnerV1Parser.ValueTrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueTrue([NotNull] YarnSpinnerV1Parser.ValueTrueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueFalse([NotNull] YarnSpinnerV1Parser.ValueFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueFalse([NotNull] YarnSpinnerV1Parser.ValueFalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueVar</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueVar([NotNull] YarnSpinnerV1Parser.ValueVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueVar</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueVar([NotNull] YarnSpinnerV1Parser.ValueVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueString([NotNull] YarnSpinnerV1Parser.ValueStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueString([NotNull] YarnSpinnerV1Parser.ValueStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNull</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueNull([NotNull] YarnSpinnerV1Parser.ValueNullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNull</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueNull([NotNull] YarnSpinnerV1Parser.ValueNullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueFunc</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueFunc([NotNull] YarnSpinnerV1Parser.ValueFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueFunc</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueFunc([NotNull] YarnSpinnerV1Parser.ValueFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] YarnSpinnerV1Parser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] YarnSpinnerV1Parser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] YarnSpinnerV1Parser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] YarnSpinnerV1Parser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] YarnSpinnerV1Parser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] YarnSpinnerV1Parser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_clause([NotNull] YarnSpinnerV1Parser.If_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_clause([NotNull] YarnSpinnerV1Parser.If_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.else_if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_if_clause([NotNull] YarnSpinnerV1Parser.Else_if_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.else_if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_if_clause([NotNull] YarnSpinnerV1Parser.Else_if_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_clause([NotNull] YarnSpinnerV1Parser.Else_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_clause([NotNull] YarnSpinnerV1Parser.Else_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>setVariableToValue</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.set_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetVariableToValue([NotNull] YarnSpinnerV1Parser.SetVariableToValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>setVariableToValue</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.set_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetVariableToValue([NotNull] YarnSpinnerV1Parser.SetVariableToValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>setExpression</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.set_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExpression([NotNull] YarnSpinnerV1Parser.SetExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>setExpression</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.set_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExpression([NotNull] YarnSpinnerV1Parser.SetExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_statement([NotNull] YarnSpinnerV1Parser.Call_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_statement([NotNull] YarnSpinnerV1Parser.Call_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.command_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand_statement([NotNull] YarnSpinnerV1Parser.Command_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.command_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand_statement([NotNull] YarnSpinnerV1Parser.Command_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.command_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand_formatted_text([NotNull] YarnSpinnerV1Parser.Command_formatted_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.command_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand_formatted_text([NotNull] YarnSpinnerV1Parser.Command_formatted_textContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.shortcut_option_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortcut_option_statement([NotNull] YarnSpinnerV1Parser.Shortcut_option_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.shortcut_option_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortcut_option_statement([NotNull] YarnSpinnerV1Parser.Shortcut_option_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.shortcut_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortcut_option([NotNull] YarnSpinnerV1Parser.Shortcut_optionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.shortcut_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortcut_option([NotNull] YarnSpinnerV1Parser.Shortcut_optionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OptionLink</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.option_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionLink([NotNull] YarnSpinnerV1Parser.OptionLinkContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OptionLink</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.option_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionLink([NotNull] YarnSpinnerV1Parser.OptionLinkContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OptionJump</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.option_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionJump([NotNull] YarnSpinnerV1Parser.OptionJumpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OptionJump</c>
	/// labeled alternative in <see cref="YarnSpinnerV1Parser.option_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionJump([NotNull] YarnSpinnerV1Parser.OptionJumpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YarnSpinnerV1Parser.option_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption_formatted_text([NotNull] YarnSpinnerV1Parser.Option_formatted_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YarnSpinnerV1Parser.option_formatted_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption_formatted_text([NotNull] YarnSpinnerV1Parser.Option_formatted_textContext context);
}
} // namespace Yarn.Compiler
