namespace Yarn.Compiler
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Text;
    using System.Text.RegularExpressions;
    using Antlr4.Runtime;
    using Antlr4.Runtime.Misc;
    using Antlr4.Runtime.Tree;
    using static Yarn.Instruction.Types;

    /// <summary>Specifies the result of compiling Yarn code.</summary>
    /// <remarks>This enum specifies the _type_ of success that resulted.
    /// Compilation failures will result in a <see cref="ParseException"/>,
    /// so they don't get a Status.</remarks>
    public enum CompilationStatus
    {
        /// <summary>The compilation succeeded with no errors.</summary>
        Succeeded,

        /// <summary>The compilation succeeded, but some strings do not
        /// have string tags.</summary>
        SucceededUntaggedStrings,
    }

    /// <summary>
    /// Information about a string. Stored inside a string table, which is
    /// produced from the Compiler.
    /// </summary>
    /// <remarks>
    /// You do not create instances of this class yourself. They are
    /// generated by the <see cref="Compiler"/>.
    /// </remarks>
    public struct StringInfo
    {
        /// <summary>
        /// The original text of the string.
        /// </summary>
        public string text;

        /// <summary>
        /// The name of the node that this string was found in.
        /// </summary>
        public string nodeName;

        /// <summary>
        /// The line number at which this string was found in the file.
        /// </summary>
        public int lineNumber;

        /// <summary>
        /// The name of the file this string was found in.
        /// </summary>
        public string fileName;

        /// <summary>
        /// Indicates whether this string's line ID was implicitly
        /// generated.
        /// </summary>
        /// <remarks>
        /// Implicitly generated line IDs are not guaranteed to remain the
        /// same across multiple compilations. To ensure that a line ID
        /// remains the same, you must define it by adding a [line
        /// tag]({{|ref "/docs/unity/localisation.md"|}}) to the line.
        /// </remarks>
        public bool isImplicitTag;

        /// <summary>
        /// The metadata (i.e. hashtags) associated with this string.
        /// </summary>
        /// <remarks>
        /// This array will contain any hashtags associated with this
        /// string besides the `#line:` hashtag.
        /// </remarks>
        public string[] metadata;

        /// <summary>
        /// Initializes a new instance of the <see cref="StringInfo"/>
        /// struct.
        /// </summary>
        /// <param name="text">The text of the string.</param>
        /// <param name="fileName">The file name.</param>
        /// <param name="nodeName">The node name.</param>
        /// <param name="lineNumber">The line number.</param>
        /// <param name="isImplicitTag">If `true`, this string info is
        /// stored with an implicit line ID.</param>
        /// <param name="metadata">The string's metadata.</param>
        internal StringInfo(string text, string fileName, string nodeName, int lineNumber, bool isImplicitTag, string[] metadata)
        {
            this.text = text;
            this.nodeName = nodeName;
            this.lineNumber = lineNumber;
            this.fileName = fileName;
            this.isImplicitTag = isImplicitTag;

            if (metadata != null)
            {
                this.metadata = metadata;
            }
            else
            {
                this.metadata = new string[] { };
            }

        }
    }

    public struct VariableDeclaration {
        public string name;
        public Value defaultValue;
        public Value.Type type;

        public override string ToString() {
            return $"{name} : {type} = {defaultValue}";
        }
    }

    public struct CompilationJob {

        /// <summary>
        /// Represents the contents of a file to compile.
        /// </summary>
        public struct File {
            public string FileName;
            public string Source;
        }

        /// <summary>
        /// The <see cref="File"/> structs that represent the content to
        /// parse..
        /// </summary>
        public IEnumerable<File> Files;

        /// <summary>
        /// The <see cref="Library"/> that contains declarations for
        /// functions.
        /// </summary>
        public Library Library;

        /// <summary>
        /// The declarations for variables.
        /// </summary>
        public IEnumerable<VariableDeclaration> VariableDeclarations;

        /// <summary>
        /// Creates a new <see cref="CompilationJob"/> using the contents
        /// of a collection of files.
        /// </summary>
        /// <param name="paths">The paths to the files.</param>
        /// <returns>A new <see cref="CompilationJob"/>.</returns>
        public static CompilationJob CreateFromFiles(IEnumerable<string> paths)
        {
            var fileList = new List<File>();

            // Read every file and add it to the file list
            foreach (var path in paths)
            {
                fileList.Add(new File
                {
                    FileName = System.IO.Path.GetFileNameWithoutExtension(path),
                    Source = System.IO.File.ReadAllText(path),
                });
            }

            return new CompilationJob
            {
                Files = fileList.ToArray(),
            };
        }

        public static CompilationJob CreateFromFiles(params string[] paths) {
            return CreateFromFiles((IEnumerable<string>) paths);
        }

        /// <summary>
        /// Creates a new <see cref="CompilationJob"/> using the contents
        /// of a string.
        /// </summary>
        /// <param name="fileName">The name to assign to the compiled file.</param>
        /// <param name="source">The text to compile.</param>
        /// <returns>A new <see cref="CompilationJob"/>.</returns>
        public static CompilationJob CreateFromString(string fileName, string source) {
            return new CompilationJob
            {
                Files = new List<File>
                {
                    new File {
                        Source = source, FileName = fileName
                    },
                }
            };
        }
    }

    public struct CompilationResult
    {
        public Program Program;
        public IDictionary<string, StringInfo> StringTable;
        public IEnumerable<VariableDeclaration> Declarations;
        public CompilationStatus Status;

        internal static CompilationResult CombineCompilationResults(IEnumerable<CompilationResult> results)
        {
            CompilationResult finalResult;

            var programs = new List<Program>();
            var declarations = new List<VariableDeclaration>();
            var mergedStringTable = new Dictionary<string, StringInfo>();

            var status = CompilationStatus.Succeeded;

            foreach (var result in results)
            {
                programs.Add(result.Program);
                
                if (result.Declarations != null) {
                    declarations.AddRange(result.Declarations);
                }

                foreach (var entry in result.StringTable)
                {
                    mergedStringTable.Add(entry.Key, entry.Value);
                }

                if (result.Status != CompilationStatus.Succeeded) {
                    status = result.Status;
                }
            }

            return new CompilationResult
            {
                Program = Program.Combine(programs.ToArray()),
                StringTable = mergedStringTable,
                Declarations = declarations,
                Status = status,
            };
        }
    }

    /// <summary>
    /// Compiles Yarn code.
    /// </summary>
    public class Compiler : YarnSpinnerParserBaseListener
    {
        /// <summary>A regular expression used to detect illegal characters
        /// in node titles.</summary>
        private readonly Regex invalidNodeTitleNameRegex = new Regex(@"[\[<>\]{}\|:\s#\$]");

        private int labelCount = 0;

        /// <summary>
        /// Gets the current node to which instructions are being added.
        /// </summary>
        /// <value>The current node.</value>
        internal Node CurrentNode { get; private set; }

        /// <summary>
        /// Gets whether we are currently parsing the current node as a
        /// 'raw text' node, or as a fully syntactic node.
        /// </summary>
        /// <value>Whether this is a raw text node or not.</value>
        internal bool RawTextNode { get; set; } = false;

        /// <summary>
        /// Gets the program being generated by the compiler.
        /// </summary>
        internal Program Program { get; private set; }

        /// <summary>
        /// The name of the file we are currently parsing from.
        /// </summary>
        private readonly string fileName;

        /// <summary>
        /// Indicates whether the file we are currently parsing contains
        /// string tags that were implicitly generated.
        /// </summary>
        private bool containsImplicitStringTags;

        /// <summary>
        /// The list of variable declarations known to the compiler. Supplied as part of a CompilationJob, or by <see cref="DeriveVariableDeclarations"/>
        /// </summary>
        internal IEnumerable<VariableDeclaration> VariableDeclarations = new List<VariableDeclaration>();

        internal Compiler(string fileName)
        {
            Program = new Program();
            this.fileName = fileName;
        }

#if DEBUG
        internal string parseTree;
        internal List<string> tokens;
#endif

        public static CompilationResult Compile(CompilationJob compilationJob)
        {
            var results = new List<CompilationResult>();

            // All variable declarations that we've encountered during this compilation job
            var derivedVariableDeclarations = new List<VariableDeclaration>();

            // All variable declarations that we've encountered, PLUS the ones we knew about before
            var knownVariableDeclarations = new List<VariableDeclaration>();
            if (compilationJob.VariableDeclarations != null) {
                knownVariableDeclarations.AddRange(compilationJob.VariableDeclarations);
            }

            var compiledTrees = new List<(string name, IParseTree tree)>();

            // First pass: parse all files, generate their syntax trees, and figure out what variables they've delcared
            foreach (var file in compilationJob.Files) {
                var tree = ParseSyntaxTree(file);
                IEnumerable<VariableDeclaration> newDeclarations = DeriveVariableDeclarations(tree, knownVariableDeclarations);

                derivedVariableDeclarations.AddRange(newDeclarations);
                knownVariableDeclarations.AddRange(newDeclarations);

                compiledTrees.Add((file.FileName, tree));
            }

            foreach (var parsedFile in compiledTrees) {
                CompilationResult compilationResult = GenerateCode(parsedFile.name, knownVariableDeclarations, compilationJob, parsedFile.tree);
                results.Add(compilationResult);
            }            

            var finalResult = CompilationResult.CombineCompilationResults(results);
            finalResult.Declarations = derivedVariableDeclarations;

            return finalResult;
        }

        private static IEnumerable<VariableDeclaration> DeriveVariableDeclarations(IParseTree tree, IEnumerable<VariableDeclaration> existingDeclarations)
        {
            var variableDeclarationVisitor = new VariableDeclarationVisitor(existingDeclarations);

            variableDeclarationVisitor.Visit(tree);

            // Upon exit, declarations will now contain every variable declaration we found
            return variableDeclarationVisitor.NewVariableDeclarations;
        }

        private static CompilationResult GenerateCode(string fileName, IEnumerable<VariableDeclaration> variableDeclarations, CompilationJob job, IParseTree tree)
        {
            Compiler compiler = new Compiler(fileName);

            compiler.VariableDeclarations = variableDeclarations;

            compiler.Compile(tree);

            return new CompilationResult
            {
                Program = compiler.Program,
                StringTable = compiler.StringTable,
                Status = compiler.containsImplicitStringTags ? CompilationStatus.SucceededUntaggedStrings : CompilationStatus.Succeeded,                
            };
        }

        private static IParseTree ParseSyntaxTree(CompilationJob.File file)
        {
            ICharStream input = CharStreams.fromstring(file.Source);

            YarnSpinnerLexer lexer = new YarnSpinnerLexer(input);
            CommonTokenStream tokens = new CommonTokenStream(lexer);

            YarnSpinnerParser parser = new YarnSpinnerParser(tokens);

            // turning off the normal error listener and using ours
            parser.RemoveErrorListeners();
            parser.AddErrorListener(ParserErrorListener.Instance);

            lexer.RemoveErrorListeners();
            lexer.AddErrorListener(LexerErrorListener.Instance);

            IParseTree tree;
            try
            {
                tree = parser.dialogue();
            }
            catch (ParseException e)
            {
#if DEBUG
                var tokenStringList = new List<string>();
                tokens.Reset();
                foreach (var token in tokens.GetTokens())
                {
                    tokenStringList.Add($"{token.Line}:{token.Column} {YarnSpinnerLexer.DefaultVocabulary.GetDisplayName(token.Type)} \"{token.Text}\"");
                }

                throw new ParseException($"{e.Message}\n\nTokens:\n{string.Join("\n", tokenStringList)}");
#else
                throw new ParseException(e.Message);
#endif // DEBUG
            }

            return tree;
        }

        /// <summary>
        /// Lexes a string containing source code, and returns a list of
        /// tokens found in the source code.
        /// </summary>
        /// <param name="path">The path of the file containing source code
        /// to extract tokens from.</param>
        /// <returns>The list of tokens extracted from the source
        /// code.</returns>
        internal static List<string> GetTokensFromFile(string path)
        {
            var text = File.ReadAllText(path);
            return GetTokensFromString(text);
        }

        /// <summary>
        /// Lexes a string containing source code, and returns a list of
        /// tokens found in the source code.
        /// </summary>
        /// <param name="text">The source code to extract tokens
        /// from.</param>
        /// <returns>The list of tokens extracted from the source
        /// code.</returns>
        internal static List<string> GetTokensFromString(string text)
        {
            ICharStream input = CharStreams.fromstring(text);

            YarnSpinnerLexer lexer = new YarnSpinnerLexer(input);

            var tokenStringList = new List<string>();

            var tokens = lexer.GetAllTokens();
            foreach (var token in tokens)
            {
                tokenStringList.Add($"{token.Line}:{token.Column} {YarnSpinnerLexer.DefaultVocabulary.GetDisplayName(token.Type)} \"{token.Text}\"");
            }

            return tokenStringList;
        }

        internal Dictionary<string, StringInfo> StringTable = new Dictionary<string, StringInfo>();

        /// <summary>
        /// The number of strings encountered so far during compilation.
        /// </summary>
        private int stringCount = 0;

        /// <summary>
        /// Registers a new string in the string table.
        /// </summary>
        /// <param name="text">The text of the string to register.</param>
        /// <param name="nodeName">The name of the node that this string
        /// was found in.</param>
        /// <param name="lineID">The line ID to use for this entry in the
        /// string table.</param>
        /// <param name="lineNumber">The line number that this string was
        /// found in.</param>
        /// <param name="tags">The tags to associate with this string in
        /// the string table.</param>
        /// <returns>The string ID for the newly registered
        /// string.</returns>
        /// <remarks>If `lineID` is `null`, a line ID will be generated
        /// from <see cref="fileName"/>, the `nodeName`, and <see
        /// cref="stringCount"/>.
        internal string RegisterString(string text, string nodeName, string lineID, int lineNumber, string[] tags)
        {
            string lineIDUsed;

            bool isImplicit;

            if (lineID == null)
            {
                lineIDUsed = $"{this.fileName}-{nodeName}-{this.stringCount}";

                this.stringCount += 1;

                // Note that we had to make up a tag for this string, which
                // may not be the same on future compilations
                this.containsImplicitStringTags = true;

                isImplicit = true;
            }
            else
            {
                lineIDUsed = lineID;

                isImplicit = false;
            }

            var theString = new StringInfo(text, this.fileName, nodeName, lineNumber, isImplicit, tags);

            // Finally, add this to the string table, and return the line
            // ID.
            this.StringTable.Add(lineIDUsed, theString);

            return lineIDUsed;
        }


        /// <summary>
        /// Generates a unique label name to use in the program.
        /// </summary>
        /// <param name="commentary">Any additional text to append to the
        /// end of the label.</param>
        /// <returns>The new label name.</returns>
        internal string RegisterLabel(string commentary = null)
        {
            return "L" + labelCount++ + commentary;
        }

        /// <summary>
        /// Creates a new instruction, and appends it to a node in the <see
        /// cref="Program" />.
        /// </summary>
        /// <param name="node">The node to append instructions to.</param>
        /// <param name="code">The opcode of the instruction.</param>
        /// <param name="operands">The operands to associate with the
        /// instruction.</param>
        void Emit(Node node, OpCode code, params Operand[] operands)
        {
            var instruction = new Instruction
            {
                Opcode = code
            };

            instruction.Operands.Add(operands);

            node.Instructions.Add(instruction);
        }

        /// <summary>
        /// Creates a new instruction, and appends it to the current node
        /// in the <see cref="Program"/>. Called by instances of <see
        /// cref="CodeGenerationVisitor"/> while walking the parse tree.
        /// </summary>
        /// <param name="code">The opcode of the instruction.</param>
        /// <param name="operands">The operands to associate with the
        /// instruction.</param>
        internal void Emit(OpCode code, params Operand[] operands)
        {
            Emit(this.CurrentNode, code, operands);
        }

        /// <summary>
        /// Extracts a line ID from a <see
        /// cref="YarnSpinnerParser.HashtagContext"/>, if one exists.
        /// </summary>
        /// <param name="context">The hashtag parsing context.</param>
        /// <returns>The line ID if one is present in the hashtag context,
        /// otherwise `null`.</returns>
        internal string GetLineID(YarnSpinnerParser.HashtagContext[] context)
        {
            // if there are any hashtags
            if (context != null)
            {
                foreach (var hashtag in context)
                {
                    string tagText = hashtag.text.Text;
                    if (tagText.StartsWith("line:", StringComparison.InvariantCulture))
                    {
                        return tagText;
                    }
                }
            }
            return null;
        }

        // this replaces the CompileNode from the old compiler will start
        // walking the parse tree emitting byte code as it goes along this
        // will all get stored into our program var needs a tree to walk,
        // this comes from the ANTLR Parser/Lexer steps
        internal void Compile(IParseTree tree)
        {
            ParseTreeWalker walker = new ParseTreeWalker();
            walker.Walk(this, tree);
        }

        // we have found a new node set up the currentNode var ready to
        // hold it and otherwise continue
        public override void EnterNode(YarnSpinnerParser.NodeContext context)
        {
            CurrentNode = new Node();
            RawTextNode = false;
        }
        // have left the current node store it into the program wipe the
        // var and make it ready to go again
        public override void ExitNode(YarnSpinnerParser.NodeContext context)
        {
            Program.Nodes[CurrentNode.Name] = CurrentNode;
            CurrentNode = null;
            RawTextNode = false;
        }


        // have finished with the header so about to enter the node body
        // and all its statements do the initial setup required before
        // compiling that body statements eg emit a new startlabel
        public override void ExitHeader(YarnSpinnerParser.HeaderContext context)
        {
            var headerKey = context.header_key.Text;

            // Use the header value if provided, else fall back to the
            // empty string. This means that a header like "foo: \n" will
            // be stored as 'foo', '', consistent with how it was typed.
            // That is, it's not null, because a header was provided, but
            // it was written as an empty line.
            var headerValue = context.header_value?.Text ?? "";

            if (headerKey.Equals("title", StringComparison.InvariantCulture))
            {
                // Set the name of the node
                CurrentNode.Name = headerValue;

                // Throw an exception if this node name contains illegal
                // characters
                if (invalidNodeTitleNameRegex.IsMatch(CurrentNode.Name))
                {
                    throw new ParseException($"The node '{CurrentNode.Name}' contains illegal characters in its title.");
                }
            }

            if (headerKey.Equals("tags", StringComparison.InvariantCulture))
            {
                // Split the list of tags by spaces, and use that
                var tags = headerValue.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

                CurrentNode.Tags.Add(tags);

                if (CurrentNode.Tags.Contains("rawText"))
                {
                    // This is a raw text node. Flag it as such for future
                    // compilation.
                    RawTextNode = true;
                }

            }

        }

        // have entered the body the header should have finished being
        // parsed and currentNode ready all we do is set up a body visitor
        // and tell it to run through all the statements it handles
        // everything from that point onwards
        public override void EnterBody(YarnSpinnerParser.BodyContext context)
        {
            // if it is a regular node
            if (!RawTextNode)
            {
                // This is the start of a node that we can jump to. Add a
                // label at this point.
                CurrentNode.Labels.Add(RegisterLabel(), CurrentNode.Instructions.Count);

                CodeGenerationVisitor visitor = new CodeGenerationVisitor(this);

                foreach (var statement in context.statement())
                {
                    visitor.Visit(statement);
                }
            }
            // we are a rawText node turn the body into text save that into
            // the node perform no compilation TODO: oh glob! there has to
            // be a better way
            else
            {
                CurrentNode.SourceTextStringID = RegisterString(context.GetText(), CurrentNode.Name, "line:" + CurrentNode.Name, context.Start.Line, null);
            }
        }

        // exiting the body of the node, time for last minute work before
        // moving onto the next node Does this node end after emitting
        // AddOptions codes without calling ShowOptions?
        public override void ExitBody(YarnSpinnerParser.BodyContext context)
        {
            // if it is a regular node
            if (!RawTextNode)
            {
                // Note: this only works when we know that we don't have
                // AddOptions and then Jump up back into the code to run
                // them. TODO: A better solution would be for the parser to
                // flag whether a node has Options at the end.
                var hasRemainingOptions = false;
                foreach (var instruction in CurrentNode.Instructions)
                {
                    if (instruction.Opcode == OpCode.AddOption)
                    {
                        hasRemainingOptions = true;
                    }
                    if (instruction.Opcode == OpCode.ShowOptions)
                    {
                        hasRemainingOptions = false;
                    }
                }

                // If this compiled node has no lingering options to show
                // at the end of the node, then stop at the end
                if (hasRemainingOptions == false)
                {
                    Emit(CurrentNode, OpCode.Stop);
                }
                else
                {
                    // Otherwise, show the accumulated nodes and then jump
                    // to the selected node
                    Emit(CurrentNode, OpCode.ShowOptions);

                    // Showing options will make the execution stop; the
                    // user will have invoked code that pushes the name of
                    // a node onto the stack, which RunNode handles
                    Emit(CurrentNode, OpCode.RunNode);
                }
            }
        }
    }

    // the visitor for the body of the node does not really return ints,
    // just has to return something might be worth later investigating
    // returning Instructions
    internal partial class CodeGenerationVisitor : YarnSpinnerParserBaseVisitor<int>
    {
        internal Compiler compiler;

        public CodeGenerationVisitor(Compiler compiler)
        {
            this.compiler = compiler;
            this.loadOperators();
        }

        private void GenerateFormattedText(IList<IParseTree> nodes, out string outputString, out int expressionCount)
        {
            expressionCount = 0;
            StringBuilder composedString = new StringBuilder();

            // First, visit all of the nodes, which are either terminal
            // text nodes or expressions. if they're expressions, we
            // evaluate them, and inject a positional reference into the
            // final string.
            foreach (var child in nodes)
            {
                if (child is ITerminalNode)
                {
                    composedString.Append(child.GetText());
                }
                else if (child is ParserRuleContext)
                {
                    // assume that this is an expression (the parser only
                    // permits them to be expressions, but we can't specify
                    // that here) - visit it, and we will emit code that
                    // pushes the final value of this expression onto the
                    // stack. running the line will pop these expressions
                    // off the stack.
                    //
                    // Expressions in the final string are denoted as the
                    // index of the expression, surrounded by braces { }.
                    // However, we don't need to write the braces here
                    // ourselves, because the text itself that the parser
                    // captured already has them. So, we just need to write
                    // the expression count.
                    Visit(child);
                    composedString.Append(expressionCount);
                    expressionCount += 1;
                }
            }

            outputString = composedString.ToString().Trim();
        }

        private string[] GetHashtagTexts(YarnSpinnerParser.HashtagContext[] hashtags)
        {
            // Add hashtag
            var hashtagText = new List<string>();
            foreach (var tag in hashtags)
            {
                hashtagText.Add(tag.HASHTAG_TEXT().GetText());
            }
            return hashtagText.ToArray();
        }

        // a regular ol' line of text
        public override int VisitLine_statement(YarnSpinnerParser.Line_statementContext context)
        {
            // TODO: add support for line conditions:
            //
            // Mae: here's a line <<if true>>
            //
            // is identical to
            //
            // <<if true>>
            // Mae: here's a line
            // <<endif>>

            // Convert the formatted string into a string with
            // placeholders, and evaluate the inline expressions and push
            // the results onto the stack.
            GenerateFormattedText(context.line_formatted_text().children, out var composedString, out var expressionCount);

            // Get the lineID for this string from the hashtags if it has
            // one; otherwise, a new one will be created
            string lineID = compiler.GetLineID(context.hashtag());

            var hashtagText = GetHashtagTexts(context.hashtag());

            int lineNumber = context.Start.Line;

            string stringID = compiler.RegisterString(
                composedString.ToString(),
                compiler.CurrentNode.Name,
                lineID,
                lineNumber,
                hashtagText);

            compiler.Emit(OpCode.RunLine, new Operand(stringID), new Operand(expressionCount));

            return 0;
        }

        // a jump statement [[ NodeName ]]
        public override int VisitOptionJump(YarnSpinnerParser.OptionJumpContext context)
        {
            string destination = context.NodeName.Text.Trim();
            compiler.Emit(OpCode.RunNode, new Operand(destination));
            return 0;
        }

        public override int VisitOptionLink(YarnSpinnerParser.OptionLinkContext context)
        {

            // Create the formatted string and evaluate any inline
            // expressions            
            GenerateFormattedText(context.option_formatted_text().children, out var composedString, out var expressionCount);

            string destination = context.NodeName.Text.Trim();
            string label = composedString;

            int lineNumber = context.Start.Line;

            // getting the lineID from the hashtags if it has one
            string lineID = compiler.GetLineID(context.hashtag());

            var hashtagText = GetHashtagTexts(context.hashtag());

            string stringID = compiler.RegisterString(label, compiler.CurrentNode.Name, lineID, lineNumber, hashtagText);

            compiler.Emit(OpCode.AddOption, new Operand(stringID), new Operand(destination), new Operand(expressionCount));

            return 0;
        }

        // A set command: explicitly setting a value to an expression <<set
        // $foo to 1>>
        public override int VisitSetVariableToValue(YarnSpinnerParser.SetVariableToValueContext context)
        {
            // add the expression (whatever it resolves to)
            Visit(context.expression());

            // validate the type of this expression
            var expressionTypeVisitor = new ExpressionTypeVisitor(compiler.VariableDeclarations, false);
            var expressionType = expressionTypeVisitor.Visit(context.expression());
            var variableType = expressionTypeVisitor.Visit(context.variable());

            if (expressionType != variableType) {
                throw new TypeException(context, $"{context.variable().GetText()} ({variableType}) cannot be assigned a {expressionType}");
            }

            // now store the variable and clean up the stack
            string variableName = context.variable().GetText();
            compiler.Emit(OpCode.StoreVariable, new Operand(variableName));
            compiler.Emit(OpCode.Pop);
            return 0;
        }

        // A set command: evaluating an expression where the operator is an
        // assignment-type
        public override int VisitSetExpression(YarnSpinnerParser.SetExpressionContext context)
        {
            // checking the expression is of the correct form
            var expression = context.expression();
            // TODO: is there really no more elegant way of doing this?!
            if (expression is YarnSpinnerParser.ExpMultDivModEqualsContext ||
                expression is YarnSpinnerParser.ExpPlusMinusEqualsContext)
            {
                // run the expression, it handles it from here
                Visit(expression);
            }
            else
            {
                // throw an error
                throw new ParseException(context, "Invalid expression inside assignment statement");
            }
            return 0;
        }

        public override int VisitCall_statement(YarnSpinnerParser.Call_statementContext context)
        {
            // Visit our function call, which will invoke the function
            Visit(context.function());

            // TODO: if this function returns a value, it will be pushed
            // onto the stack, but there's no way for the compiler to know
            // that, so the stack will not be tidied up. is there a way for
            // that to work?
            return 0;
        }

        // semi-free form text that gets passed along to the game for
        // things like <<turn fred left>> or <<unlockAchievement
        // FacePlant>>
        public override int VisitCommand_statement(YarnSpinnerParser.Command_statementContext context)
        {
            GenerateFormattedText(context.command_formatted_text().children, out var composedString, out var expressionCount);

            // TODO: look into replacing this as it seems a bit odd
            switch (composedString)
            {
                case "stop":
                    // "stop" is a special command that immediately stops
                    // execution
                    compiler.Emit(OpCode.Stop);
                    break;
                default:
                    compiler.Emit(OpCode.RunCommand, new Operand(composedString), new Operand(expressionCount));
                    break;
            }

            return 0;
        }

        // emits the required bytecode for the function call
        private void HandleFunction(string functionName, YarnSpinnerParser.ExpressionContext[] parameters)
        {
            // generate the instructions for all of the parameters
            foreach (var parameter in parameters)
            {
                Visit(parameter);
            }

            // push the number of parameters onto the stack
            compiler.Emit(OpCode.PushFloat, new Operand(parameters.Length));

            // then call the function itself
            compiler.Emit(OpCode.CallFunc, new Operand(functionName));
        }
        // handles emiting the correct instructions for the function
        public override int VisitFunction(YarnSpinnerParser.FunctionContext context)
        {
            string functionName = context.FUNC_ID().GetText();

            this.HandleFunction(functionName, context.expression());

            return 0;
        }

        // if statement ifclause (elseifclause)* (elseclause)? <<endif>>
        public override int VisitIf_statement(YarnSpinnerParser.If_statementContext context)
        {
            // label to give us a jump point for when the if finishes
            string endOfIfStatementLabel = compiler.RegisterLabel("endif");

            // handle the if
            var ifClause = context.if_clause();
            generateClause(endOfIfStatementLabel, ifClause.statement(), ifClause.expression());

            // all elseifs
            foreach (var elseIfClause in context.else_if_clause())
            {
                generateClause(endOfIfStatementLabel, elseIfClause.statement(), elseIfClause.expression());
            }

            // the else, if there is one
            var elseClause = context.else_clause();
            if (elseClause != null)
            {
                generateClause(endOfIfStatementLabel, elseClause.statement(), null);
            }

            compiler.CurrentNode.Labels.Add(endOfIfStatementLabel, compiler.CurrentNode.Instructions.Count);

            return 0;
        }
        internal void generateClause(string jumpLabel, YarnSpinnerParser.StatementContext[] children, YarnSpinnerParser.ExpressionContext expression)
        {
            string endOfClauseLabel = compiler.RegisterLabel("skipclause");

            // handling the expression (if it has one) will only be called
            // on ifs and elseifs
            if (expression != null)
            {
                // Validate the expression's type
                new ExpressionTypeVisitor(compiler.VariableDeclarations, false).Visit(expression);

                // Code-generate the expression
                Visit(expression);
                                
                compiler.Emit(OpCode.JumpIfFalse, new Operand(endOfClauseLabel));
            }

            // running through all of the children statements
            foreach (var child in children)
            {
                Visit(child);
            }

            compiler.Emit(OpCode.JumpTo, new Operand(jumpLabel));

            if (expression != null)
            {
                compiler.CurrentNode.Labels.Add(endOfClauseLabel, compiler.CurrentNode.Instructions.Count);
                compiler.Emit(OpCode.Pop);
            }
        }

        // for the shortcut options (-> line of text <<if expression>>
        // indent statements dedent)+
        public override int VisitShortcut_option_statement(YarnSpinnerParser.Shortcut_option_statementContext context)
        {

            string endOfGroupLabel = compiler.RegisterLabel("group_end");

            var labels = new List<string>();

            int optionCount = 0;

            // For each option, create an internal destination label that,
            // if the user selects the option, control flow jumps to. Then,
            // evaluate its associated line_statement, and use that as the
            // option text. Finally, add this option to the list of
            // upcoming options.
            foreach (var shortcut in context.shortcut_option())
            {
                // Generate the name of internal label that we'll jump to
                // if this option is selected. We'll emit the label itself
                // later.
                string optionDestinationLabel = compiler.RegisterLabel($"shortcutoption_{compiler.CurrentNode.Name ?? "node"}_{optionCount + 1}");
                labels.Add(optionDestinationLabel);

                // This line statement may have a condition on it. If it
                // does, emit code that evaluates the condition, and skips
                // over the code that prepares and adds the option.
                string endOfClauseLabel = null;
                if (shortcut.line_statement().line_condition() != null)
                {
                    // Register the label we'll jump to if the condition
                    // fails. We'll add it later.
                    endOfClauseLabel = compiler.RegisterLabel("conditional_" + optionCount);

                    // Evaluate the condition, and jump to the end of
                    // clause if it evaluates to false.

                    Visit(shortcut.line_statement().line_condition().expression());

                    compiler.Emit(OpCode.JumpIfFalse, new Operand(endOfClauseLabel));
                }

                // We can now prepare and add the option.

                // Start by figuring out the text that we want to add. This
                // will involve evaluating any inline expressions.
                GenerateFormattedText(shortcut.line_statement().line_formatted_text().children, out var composedString, out var expressionCount);

                // Get the line ID from the hashtags if it has one
                string lineID = compiler.GetLineID(shortcut.line_statement().hashtag());

                // Get the hashtags for the line
                var hashtags = GetHashtagTexts(shortcut.line_statement().hashtag());

                // Register this string
                string labelStringID = compiler.RegisterString(composedString, compiler.CurrentNode.Name, lineID, shortcut.Start.Line, hashtags);

                // And add this option to the list.
                compiler.Emit(OpCode.AddOption, new Operand(labelStringID), new Operand(optionDestinationLabel), new Operand(expressionCount));

                // If we had a line condition, now's the time to generate
                // the label that we'd jump to if its condition is false.
                if (shortcut.line_statement().line_condition() != null)
                {
                    compiler.CurrentNode.Labels.Add(endOfClauseLabel, compiler.CurrentNode.Instructions.Count);

                    // JumpIfFalse doesn't change the stack, so we need to
                    // tidy up            
                    compiler.Emit(OpCode.Pop);
                }

                optionCount++;
            }

            // All of the options that we intend to show are now ready to
            // go.
            compiler.Emit(OpCode.ShowOptions);

            // The top of the stack now contains the name of the label we
            // want to jump to. Jump to it now.
            compiler.Emit(OpCode.Jump);

            // We'll now emit the labels and code associated with each
            // option.
            optionCount = 0;
            foreach (var shortcut in context.shortcut_option())
            {
                // Emit the label for this option's code
                compiler.CurrentNode.Labels.Add(labels[optionCount], compiler.CurrentNode.Instructions.Count);

                // Run through all the children statements of the shortcut
                // option.
                foreach (var child in shortcut.statement())
                {
                    Visit(child);
                }

                // Jump to the end of this shortcut option group.
                compiler.Emit(OpCode.JumpTo, new Operand(endOfGroupLabel));

                optionCount++;
            }

            // We made it to the end! Mark the end of the group, so we can
            // jump to it.
            compiler.CurrentNode.Labels.Add(endOfGroupLabel, compiler.CurrentNode.Instructions.Count);
            compiler.Emit(OpCode.Pop);

            return 0;
        }

        // the calls for the various operations and expressions first the
        // special cases (), unary -, !, and if it is just a value by
        // itself
        #region specialCaseCalls
        // (expression)
        public override int VisitExpParens(YarnSpinnerParser.ExpParensContext context)
        {
            return Visit(context.expression());
        }
        // -expression
        public override int VisitExpNegative(YarnSpinnerParser.ExpNegativeContext context)
        {
            Visit(context.expression());

            // TODO: temp operator call

            // Indicate that we are pushing one parameter
            compiler.Emit(OpCode.PushFloat, new Operand(1));

            compiler.Emit(OpCode.CallFunc, new Operand(TokenType.UnaryMinus.ToString()));

            return 0;
        }
        // (not NOT !)expression
        public override int VisitExpNot(YarnSpinnerParser.ExpNotContext context)
        {
            Visit(context.expression());

            // TODO: temp operator call

            // Indicate that we are pushing one parameter
            compiler.Emit(OpCode.PushFloat, new Operand(1));

            compiler.Emit(OpCode.CallFunc, new Operand(TokenType.Not.ToString()));

            return 0;
        }
        // variable
        public override int VisitExpValue(YarnSpinnerParser.ExpValueContext context)
        {
            return Visit(context.value());
        }
        #endregion

        // left OPERATOR right style expressions the most common form of
        // expressions for things like 1 + 3
        #region lValueOperatorrValueCalls
        internal void genericExpVisitor(YarnSpinnerParser.ExpressionContext left, YarnSpinnerParser.ExpressionContext right, int op)
        {
            Visit(left);
            Visit(right);

            // TODO: temp operator call

            // Indicate that we are pushing two items for comparison
            compiler.Emit(OpCode.PushFloat, new Operand(2));

            compiler.Emit(OpCode.CallFunc, new Operand(tokens[op].ToString()));
        }
        // * / %
        public override int VisitExpMultDivMod(YarnSpinnerParser.ExpMultDivModContext context)
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.Type);

            return 0;
        }
        // + -
        public override int VisitExpAddSub(YarnSpinnerParser.ExpAddSubContext context)
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.Type);

            return 0;
        }
        // < <= > >=
        public override int VisitExpComparison(YarnSpinnerParser.ExpComparisonContext context)
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.Type);

            return 0;
        }
        // == !=
        public override int VisitExpEquality(YarnSpinnerParser.ExpEqualityContext context)
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.Type);

            return 0;
        }
        // and && or || xor ^
        public override int VisitExpAndOrXor(YarnSpinnerParser.ExpAndOrXorContext context)
        {
            genericExpVisitor(context.expression(0), context.expression(1), context.op.Type);

            return 0;
        }
        #endregion

        // operatorEquals style operators, eg += these two should only be
        // called during a SET operation eg << set $var += 1 >> the left
        // expression has to be a variable the right value can be anything
        #region operatorEqualsCalls
        // generic helper for these types of expressions
        internal void opEquals(string varName, YarnSpinnerParser.ExpressionContext expression, int op)
        {
            // Get the current value of the variable
            compiler.Emit(OpCode.PushVariable, new Operand(varName));

            // run the expression
            Visit(expression);

            // Stack now contains [currentValue, expressionValue]

            // Indicate that we are pushing two items for comparison
            compiler.Emit(OpCode.PushFloat, new Operand(2));

            // now we evaluate the operator op will match to one of + - / *
            // %
            compiler.Emit(OpCode.CallFunc, new Operand(tokens[op].ToString()));

            // Stack now has the destination value now store the variable
            // and clean up the stack
            compiler.Emit(OpCode.StoreVariable, new Operand(varName));
            compiler.Emit(OpCode.Pop);
        }
        // *= /= %=
        public override int VisitExpMultDivModEquals(YarnSpinnerParser.ExpMultDivModEqualsContext context)
        {
            // call the helper to deal with this
            opEquals(context.variable().GetText(), context.expression(), context.op.Type);
            return 0;
        }
        // += -=
        public override int VisitExpPlusMinusEquals(YarnSpinnerParser.ExpPlusMinusEqualsContext context)
        {
            // call the helper to deal with this
            opEquals(context.variable().GetText(), context.expression(), context.op.Type);

            return 0;
        }
        #endregion

        // the calls for the various value types this is a wee bit messy
        // but is easy to extend, easy to read and requires minimal
        // checking as ANTLR has already done all that does have code
        // duplication though
        #region valueCalls
        public override int VisitValueVar(YarnSpinnerParser.ValueVarContext context)
        {
            return Visit(context.variable());
        }
        public override int VisitValueNumber(YarnSpinnerParser.ValueNumberContext context)
        {
            float number = float.Parse(context.NUMBER().GetText(), CultureInfo.InvariantCulture);
            compiler.Emit(OpCode.PushFloat, new Operand(number));

            return 0;
        }
        public override int VisitValueTrue(YarnSpinnerParser.ValueTrueContext context)
        {
            compiler.Emit(OpCode.PushBool, new Operand(true));

            return 0;
        }
        public override int VisitValueFalse(YarnSpinnerParser.ValueFalseContext context)
        {
            compiler.Emit(OpCode.PushBool, new Operand(false));
            return 0;
        }
        public override int VisitVariable(YarnSpinnerParser.VariableContext context)
        {
            string variableName = context.VAR_ID().GetText();
            compiler.Emit(OpCode.PushVariable, new Operand(variableName));

            return 0;
        }
        public override int VisitValueString(YarnSpinnerParser.ValueStringContext context)
        {
            // stripping the " off the front and back actually is this what
            // we want?
            string stringVal = context.STRING().GetText().Trim('"');

            compiler.Emit(OpCode.PushString, new Operand(stringVal));

            return 0;
        }
        // all we need do is visit the function itself, it will handle
        // everything
        public override int VisitValueFunc(YarnSpinnerParser.ValueFuncContext context)
        {
            Visit(context.function());

            return 0;
        }
        // null value
        public override int VisitValueNull(YarnSpinnerParser.ValueNullContext context)
        {
            compiler.Emit(OpCode.PushNull);
            return 0;
        }
        #endregion

        // TODO: figure out a better way to do operators
        Dictionary<int, TokenType> tokens = new Dictionary<int, TokenType>();
        private void loadOperators()
        {
            // operators for the standard expressions
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_LESS_THAN_EQUALS] = TokenType.LessThanOrEqualTo;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_GREATER_THAN_EQUALS] = TokenType.GreaterThanOrEqualTo;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_LESS] = TokenType.LessThan;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_GREATER] = TokenType.GreaterThan;

            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_EQUALS] = TokenType.EqualTo;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_NOT_EQUALS] = TokenType.NotEqualTo;

            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_AND] = TokenType.And;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_OR] = TokenType.Or;
            tokens[YarnSpinnerLexer.OPERATOR_LOGICAL_XOR] = TokenType.Xor;

            tokens[YarnSpinnerLexer.OPERATOR_MATHS_ADDITION] = TokenType.Add;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_SUBTRACTION] = TokenType.Minus;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_MULTIPLICATION] = TokenType.Multiply;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_DIVISION] = TokenType.Divide;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_MODULUS] = TokenType.Modulo;
            // operators for the set expressions these map directly to the
            // operator if they didn't have the =
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_ADDITION_EQUALS] = TokenType.Add;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_SUBTRACTION_EQUALS] = TokenType.Minus;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_MULTIPLICATION_EQUALS] = TokenType.Multiply;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_DIVISION_EQUALS] = TokenType.Divide;
            tokens[YarnSpinnerLexer.OPERATOR_MATHS_MODULUS_EQUALS] = TokenType.Modulo;
        }
    }

    public class Graph
    {
        public ArrayList<String> nodes = new ArrayList<String>();
        public MultiMap<String, String> edges = new MultiMap<String, String>();
        public string graphName = "G";

        public void edge(String source, String target)
        {
            edges.Map(source, target);
        }
        public String toDot()
        {
            StringBuilder buf = new StringBuilder();
            buf.AppendFormat("digraph {0} ", graphName);
            buf.Append("{\n");
            buf.Append("  ");
            foreach (String node in nodes)
            { // print all nodes first
                buf.Append(node);
                buf.Append("; ");
            }
            buf.Append("\n");
            foreach (String src in edges.Keys)
            {
                IList<string> output;
                if (edges.TryGetValue(src, out output))
                {
                    foreach (String trg in output)
                    {
                        buf.Append("  ");
                        buf.Append(src);
                        buf.Append(" -> ");
                        buf.Append(trg);
                        buf.Append(";\n");
                    }
                }
            }
            buf.Append("}\n");
            return buf.ToString();
        }
    }
    public class GraphListener : YarnSpinnerParserBaseListener
    {
        String currentNode = null;
        public Graph graph = new Graph();

        public override void EnterHeader(YarnSpinnerParser.HeaderContext context)
        {
            if (context.header_key.Text == "title")
            {
                currentNode = context.header_value.Text;
            }
        }

        public override void ExitNode(YarnSpinnerParser.NodeContext context)
        {
            // Add this node to the graph
            graph.nodes.Add(currentNode);
        }
        public override void ExitOptionJump(YarnSpinnerParser.OptionJumpContext context)
        {
            graph.edge(currentNode, context.NodeName.Text);
        }

        public override void ExitOptionLink(YarnSpinnerParser.OptionLinkContext context)
        {
            graph.edge(currentNode, context.NodeName.Text);
        }

    }
}
